/**
 * "Blindtest Musical" — curated answers + iTunes search queries.
 *
 * Audio is fetched at runtime from the iTunes Search API (30s previews), so
 * there are no files to host. Each entry pairs a clean ANSWER (what players
 * guess) with a search QUERY. Dead/empty queries are auto-skipped in game,
 * so a few misses never block a party.
 */

export type BlindtestCategory =
  | 'anime' | 'cartoon' | 'music' | 'film' | 'jeuxvideo' | 'disney'
  | 'kpop' | 'retro' | 'series' | 'rapfr';

export const CATEGORY_META: Record<
  BlindtestCategory,
  { label: string; emoji: string; color: string }
> = {
  anime: { label: 'Anime', emoji: '🎌', color: '#f43f5e' },
  cartoon: { label: 'Dessin animé', emoji: '📺', color: '#22d3ee' },
  music: { label: 'Musique', emoji: '🎵', color: '#a855f7' },
  film: { label: 'Film', emoji: '🎬', color: '#fbbf24' },
  jeuxvideo: { label: 'Jeux Vidéo', emoji: '🎮', color: '#34d399' },
  disney: { label: 'Disney', emoji: '🏰', color: '#38bdf8' },
  kpop: { label: 'K-Pop', emoji: '🇰🇷', color: '#f472b6' },
  retro: { label: 'Années 80-90', emoji: '📼', color: '#fb923c' },
  series: { label: 'Séries TV', emoji: '🎞️', color: '#60a5fa' },
  rapfr: { label: 'Rap FR', emoji: '🎤', color: '#a3e635' },
};

export interface BlindtestEntry {
  answer: string;
  category: BlindtestCategory;
  query: string;
  hint?: string;
}

const ANIME: BlindtestEntry[] = [
  { answer: 'Naruto', category: 'anime', query: 'Blue Bird Ikimonogakari' },
  { answer: "L'Attaque des Titans", category: 'anime', query: 'Guren no Yumiya Linked Horizon' },
  { answer: 'Demon Slayer', category: 'anime', query: 'Gurenge LiSA' },
  { answer: 'One Piece', category: 'anime', query: 'We Are Hiroshi Kitadani' },
  { answer: 'Jujutsu Kaisen', category: 'anime', query: 'Kaikai Kitan Eve' },
  { answer: 'My Hero Academia', category: 'anime', query: 'Peace Sign Kenshi Yonezu' },
  { answer: 'Dragon Ball Z', category: 'anime', query: 'Cha-La Head-Cha-La Hironobu Kageyama' },
  { answer: 'Death Note', category: 'anime', query: 'the WORLD Nightmare' },
  { answer: 'Tokyo Ghoul', category: 'anime', query: 'Unravel TK ling tosite sigure' },
  { answer: 'Sword Art Online', category: 'anime', query: 'Crossing Field LiSA' },
  { answer: 'Fullmetal Alchemist', category: 'anime', query: 'Again Yui' },
  { answer: 'Hunter x Hunter', category: 'anime', query: 'Departure Masatoshi Ono' },
  { answer: 'Chainsaw Man', category: 'anime', query: 'Kick Back Kenshi Yonezu' },
  { answer: 'Spy x Family', category: 'anime', query: 'Mixed Nuts Official Hige Dandism' },
  { answer: 'Bleach', category: 'anime', query: 'Asterisk Orange Range' },
  { answer: 'Evangelion', category: 'anime', query: "A Cruel Angel's Thesis Yoko Takahashi" },
  { answer: 'Fairy Tail', category: 'anime', query: 'Snow Fairy Funkist' },
  { answer: 'Black Clover', category: 'anime', query: 'Black Catcher Vickeblanka' },
  { answer: 'Haikyuu', category: 'anime', query: 'Imagination Spyair' },
  { answer: 'Tokyo Revengers', category: 'anime', query: 'Cry Baby Official Hige Dandism' },
  { answer: "JoJo's Bizarre Adventure", category: 'anime', query: 'Bloody Stream Coda' },
  { answer: 'Cowboy Bebop', category: 'anime', query: 'Tank Seatbelts Yoko Kanno' },
  { answer: 'Mob Psycho 100', category: 'anime', query: '99 Mob Choir' },
  { answer: 'One Punch Man', category: 'anime', query: 'The Hero JAM Project' },
  { answer: 'Steins;Gate', category: 'anime', query: 'Hacking to the Gate Kanako Ito' },
  { answer: 'Re:Zero', category: 'anime', query: 'Redo Konomi Suzuki' },
  { answer: 'Vinland Saga', category: 'anime', query: 'Mukanjyo Survive Said The Prophet' },
  { answer: 'Blue Lock', category: 'anime', query: 'Chaos Lulu Unfair' },
  { answer: 'Code Geass', category: 'anime', query: 'Colors Flow' },
  { answer: 'Gurren Lagann', category: 'anime', query: 'Sorairo Days Shoko Nakagawa' },
  { answer: 'Fate/Zero', category: 'anime', query: 'oath sign LiSA' },
  { answer: 'Your Name', category: 'anime', query: 'Zenzenzense RADWIMPS' },
  { answer: 'Angel Beats', category: 'anime', query: 'My Soul Your Beats Lia' },
  { answer: 'Seven Deadly Sins', category: 'anime', query: 'Netsujou no Spectrum Ikimonogakari' },
  { answer: 'Assassination Classroom', category: 'anime', query: 'Seishun Satsubatsuron 3-nen E-gumi Utatan' },
  { answer: 'Erased', category: 'anime', query: 'Re:Re: Asian Kung-Fu Generation' },
  { answer: 'Your Lie in April', category: 'anime', query: 'Hikaru Nara Goose House' },
  { answer: 'Madoka Magica', category: 'anime', query: 'Connect ClariS' },
  { answer: 'Konosuba', category: 'anime', query: 'fantastic dreamer Machico' },
  { answer: 'The Promised Neverland', category: 'anime', query: 'Touch off UVERworld' },
  { answer: 'Dr. Stone', category: 'anime', query: 'Good Morning World Burnout Syndromes' },
  { answer: 'Fire Force', category: 'anime', query: 'Inferno Mrs. Green Apple' },
  { answer: 'Kaguya-sama', category: 'anime', query: 'Love Dramatic Masayuki Suzuki' },
  { answer: 'Bocchi the Rock', category: 'anime', query: 'Seishun Complex Kessoku Band' },
  { answer: 'Oshi no Ko', category: 'anime', query: 'Idol YOASOBI' },
  { answer: 'Frieren', category: 'anime', query: 'Yuusha YOASOBI' },
  { answer: 'Sailor Moon', category: 'anime', query: 'Moonlight Densetsu Dali' },
  { answer: 'Inuyasha', category: 'anime', query: 'Change the World V6' },
  { answer: 'Yu Yu Hakusho', category: 'anime', query: 'Hohoemi no Bakudan Matsuko Mawatari' },
  { answer: 'Detective Conan', category: 'anime', query: 'Mune ga Doki Doki The High-Lows' },
  { answer: 'Soul Eater', category: 'anime', query: 'Resonance T.M.Revolution' },
  { answer: 'Elfen Lied', category: 'anime', query: 'Lilium Elfen Lied' },
  { answer: 'Beastars', category: 'anime', query: 'Wild Side Ali' },
  { answer: 'Devilman Crybaby', category: 'anime', query: 'Man Human Kensuke Ushio' },
];

const CARTOON: BlindtestEntry[] = [
  // Vrais dessins animés (pas d'anime) — génériques VF quand ils existent
  { answer: 'Bob l’éponge', category: 'cartoon', query: 'Bob l’éponge générique français' },
  { answer: 'Inspecteur Gadget', category: 'cartoon', query: 'Inspecteur Gadget générique français' },
  { answer: 'Les Tortues Ninja', category: 'cartoon', query: 'Tortues Ninja générique Bernard Minet' },
  { answer: 'Code Lyoko', category: 'cartoon', query: 'Un Monde Sans Danger Code Lyoko' },
  { answer: 'Wakfu', category: 'cartoon', query: 'Wakfu générique' },
  { answer: 'Totally Spies', category: 'cartoon', query: 'Totally Spies générique français' },
  { answer: 'Oggy et les cafards', category: 'cartoon', query: 'Oggy et les cafards générique' },
  { answer: 'Titeuf', category: 'cartoon', query: 'Titeuf générique' },
  { answer: 'Foot 2 Rue', category: 'cartoon', query: 'Foot 2 Rue générique' },
  { answer: 'Il était une fois la vie', category: 'cartoon', query: 'Il était une fois la vie générique' },
  { answer: "Les Mystérieuses Cités d'Or", category: 'cartoon', query: "Les Mystérieuses Cités d'Or générique" },
  { answer: 'Ulysse 31', category: 'cartoon', query: 'Ulysse 31 générique' },
  { answer: 'Les Mondes Engloutis', category: 'cartoon', query: 'Les Mondes Engloutis générique' },
  { answer: 'Les Schtroumpfs', category: 'cartoon', query: 'Les Schtroumpfs générique français' },
  { answer: 'Lucky Luke', category: 'cartoon', query: 'Lucky Luke générique' },
  { answer: 'Astérix', category: 'cartoon', query: 'Astérix générique' },
  { answer: 'Babar', category: 'cartoon', query: 'Babar générique français' },
  { answer: 'T’choupi', category: 'cartoon', query: 'Tchoupi générique' },
  { answer: 'Boule et Bill', category: 'cartoon', query: 'Boule et Bill générique' },
  { answer: 'Cédric', category: 'cartoon', query: 'Cédric générique' },
  { answer: 'Le Petit Nicolas', category: 'cartoon', query: 'Le Petit Nicolas générique' },
  { answer: 'Denver le dernier dinosaure', category: 'cartoon', query: 'Denver le dernier dinosaure générique' },
  { answer: 'Les Entrechats', category: 'cartoon', query: 'Les Entrechats générique' },
  { answer: 'Pollux', category: 'cartoon', query: 'Le Manège enchanté Pollux générique' },
  { answer: 'Les Minipouss', category: 'cartoon', query: 'Les Minipouss générique' },
  { answer: 'Dora l’exploratrice', category: 'cartoon', query: 'Dora l’exploratrice générique' },
  { answer: 'Pat’ Patrouille', category: 'cartoon', query: 'Pat Patrouille générique français' },
  { answer: 'Winx Club', category: 'cartoon', query: 'Winx Club générique français' },
  { answer: 'Miraculous', category: 'cartoon', query: 'Miraculous Ladybug générique français' },
  { answer: 'Sam le pompier', category: 'cartoon', query: 'Sam le pompier générique' },
  { answer: 'Petit Ours Brun', category: 'cartoon', query: 'Petit Ours Brun générique' },
  { answer: 'Trotro', category: 'cartoon', query: 'Trotro générique' },
  { answer: 'Les P’tits Diables', category: 'cartoon', query: "Les P'tits Diables générique" },
  { answer: 'MASK', category: 'cartoon', query: 'MASK générique français' },
  // Cartoons US (thèmes connus)
  { answer: 'Les Simpson', category: 'cartoon', query: 'The Simpsons Theme Danny Elfman' },
  { answer: 'Tom et Jerry', category: 'cartoon', query: 'Tom and Jerry Scott Bradley' },
  { answer: 'Scooby-Doo', category: 'cartoon', query: 'Scooby Doo Where Are You' },
  { answer: 'Les Razmoket', category: 'cartoon', query: 'Rugrats Theme' },
  { answer: 'Les Supers Nanas', category: 'cartoon', query: 'Powerpuff Girls Theme' },
  { answer: 'Ben 10', category: 'cartoon', query: 'Ben 10 Theme' },
  { answer: 'Gravity Falls', category: 'cartoon', query: 'Gravity Falls Theme' },
  { answer: 'Rick et Morty', category: 'cartoon', query: 'Rick and Morty Theme' },
  { answer: 'Phineas et Ferb', category: 'cartoon', query: 'Phineas and Ferb Theme' },
  { answer: 'Kim Possible', category: 'cartoon', query: 'Call Me Beep Me Kim Possible' },
  { answer: 'Teen Titans', category: 'cartoon', query: 'Teen Titans Theme Puffy AmiYumi' },
  { answer: 'La Bande à Picsou', category: 'cartoon', query: 'DuckTales Theme' },
  { answer: 'Les Pierrafeu', category: 'cartoon', query: 'Meet the Flintstones' },
  { answer: 'Looney Tunes', category: 'cartoon', query: 'Looney Tunes Merrily We Roll Along' },
  { answer: 'South Park', category: 'cartoon', query: 'South Park Theme Primus' },
  { answer: 'Les Griffin', category: 'cartoon', query: 'Family Guy Theme' },
  { answer: 'Mr Bean', category: 'cartoon', query: 'Mr Bean Animated Series Theme' },
];

const MUSIC: BlindtestEntry[] = [
  { answer: 'Blinding Lights', category: 'music', query: 'Blinding Lights The Weeknd' },
  { answer: 'Bad Guy', category: 'music', query: 'bad guy Billie Eilish' },
  { answer: 'Shape of You', category: 'music', query: 'Shape of You Ed Sheeran' },
  { answer: 'Uptown Funk', category: 'music', query: 'Uptown Funk Bruno Mars' },
  { answer: 'Rolling in the Deep', category: 'music', query: 'Rolling in the Deep Adele' },
  { answer: 'Believer', category: 'music', query: 'Believer Imagine Dragons' },
  { answer: 'Levitating', category: 'music', query: 'Levitating Dua Lipa' },
  { answer: 'Smells Like Teen Spirit', category: 'music', query: 'Smells Like Teen Spirit Nirvana' },
  { answer: 'Billie Jean', category: 'music', query: 'Billie Jean Michael Jackson' },
  { answer: 'Seven Nation Army', category: 'music', query: 'Seven Nation Army The White Stripes' },
  { answer: 'Bohemian Rhapsody', category: 'music', query: 'Bohemian Rhapsody Queen' },
  { answer: "Sweet Child O' Mine", category: 'music', query: 'Sweet Child O Mine Guns N Roses' },
  { answer: 'Wonderwall', category: 'music', query: 'Wonderwall Oasis' },
  { answer: 'Take On Me', category: 'music', query: 'Take On Me a-ha' },
  { answer: 'Viva la Vida', category: 'music', query: 'Viva la Vida Coldplay' },
  { answer: 'Get Lucky', category: 'music', query: 'Get Lucky Daft Punk' },
  { answer: 'Lose Yourself', category: 'music', query: 'Lose Yourself Eminem' },
  { answer: 'Shake It Off', category: 'music', query: 'Shake It Off Taylor Swift' },
  { answer: 'Despacito', category: 'music', query: 'Despacito Luis Fonsi' },
  { answer: 'Gangnam Style', category: 'music', query: 'Gangnam Style PSY' },
  { answer: 'Dynamite', category: 'music', query: 'Dynamite BTS' },
  { answer: 'As It Was', category: 'music', query: 'As It Was Harry Styles' },
  { answer: 'Flowers', category: 'music', query: 'Flowers Miley Cyrus' },
  { answer: 'Happy', category: 'music', query: 'Happy Pharrell Williams' },
  { answer: 'Someone Like You', category: 'music', query: 'Someone Like You Adele' },
  { answer: 'Counting Stars', category: 'music', query: 'Counting Stars OneRepublic' },
  { answer: 'Radioactive', category: 'music', query: 'Radioactive Imagine Dragons' },
  { answer: 'Roar', category: 'music', query: 'Roar Katy Perry' },
  { answer: 'Bad Romance', category: 'music', query: 'Bad Romance Lady Gaga' },
  { answer: 'Toxic', category: 'music', query: 'Toxic Britney Spears' },
  { answer: 'Hey Ya!', category: 'music', query: 'Hey Ya OutKast' },
  { answer: 'In the End', category: 'music', query: 'In the End Linkin Park' },
  { answer: 'Boulevard of Broken Dreams', category: 'music', query: 'Boulevard of Broken Dreams Green Day' },
  { answer: 'Mr. Brightside', category: 'music', query: 'Mr Brightside The Killers' },
  { answer: 'Stairway to Heaven', category: 'music', query: 'Stairway to Heaven Led Zeppelin' },
  { answer: 'Hotel California', category: 'music', query: 'Hotel California Eagles' },
  { answer: 'Imagine', category: 'music', query: 'Imagine John Lennon' },
  { answer: 'Africa', category: 'music', query: 'Africa Toto' },
  { answer: "Don't Stop Believin'", category: 'music', query: 'Dont Stop Believin Journey' },
  { answer: 'Thriller', category: 'music', query: 'Thriller Michael Jackson' },
  { answer: 'Sweet Dreams', category: 'music', query: 'Sweet Dreams Eurythmics' },
  { answer: 'Wannabe', category: 'music', query: 'Wannabe Spice Girls' },
  { answer: "Livin' on a Prayer", category: 'music', query: 'Livin on a Prayer Bon Jovi' },
  { answer: 'Old Town Road', category: 'music', query: 'Old Town Road Lil Nas X' },
  { answer: 'Sunflower', category: 'music', query: 'Sunflower Post Malone Swae Lee' },
  { answer: 'Stay', category: 'music', query: 'Stay The Kid LAROI Justin Bieber' },
  { answer: 'Alors on danse', category: 'music', query: 'Alors on danse Stromae' },
  { answer: 'Dernière danse', category: 'music', query: 'Dernière danse Indila' },
  { answer: 'Djadja', category: 'music', query: 'Djadja Aya Nakamura' },
  { answer: 'Balance ton quoi', category: 'music', query: 'Balance ton quoi Angèle' },
  { answer: 'La Vie en rose', category: 'music', query: 'La Vie en rose Edith Piaf' },
  { answer: 'Christine', category: 'music', query: 'Christine Christine and the Queens' },
  // ── batch +80 (hits internationaux & FR, tous sur iTunes) ──
  { answer: 'Rockstar', category: 'music', query: 'rockstar Post Malone 21 Savage' },
  { answer: 'Closer', category: 'music', query: 'Closer The Chainsmokers Halsey' },
  { answer: 'Faded', category: 'music', query: 'Faded Alan Walker' },
  { answer: 'Titanium', category: 'music', query: 'Titanium David Guetta Sia' },
  { answer: 'Wake Me Up', category: 'music', query: 'Wake Me Up Avicii' },
  { answer: 'Waves', category: 'music', query: 'Waves Mr Probz Robin Schulz' },
  { answer: 'Lean On', category: 'music', query: 'Lean On Major Lazer DJ Snake' },
  { answer: 'Turn Down for What', category: 'music', query: 'Turn Down for What DJ Snake Lil Jon' },
  { answer: 'Animals', category: 'music', query: 'Animals Martin Garrix' },
  { answer: 'Feel So Close', category: 'music', query: 'Feel So Close Calvin Harris' },
  { answer: 'One Dance', category: 'music', query: 'One Dance Drake' },
  { answer: 'God\'s Plan', category: 'music', query: 'Gods Plan Drake' },
  { answer: 'Hotline Bling', category: 'music', query: 'Hotline Bling Drake' },
  { answer: 'Sicko Mode', category: 'music', query: 'Sicko Mode Travis Scott' },
  { answer: 'Humble', category: 'music', query: 'HUMBLE Kendrick Lamar' },
  { answer: 'Not Like Us', category: 'music', query: 'Not Like Us Kendrick Lamar' },
  { answer: 'Industry Baby', category: 'music', query: 'Industry Baby Lil Nas X' },
  { answer: 'Montero', category: 'music', query: 'Montero Lil Nas X' },
  { answer: 'Save Your Tears', category: 'music', query: 'Save Your Tears The Weeknd' },
  { answer: 'Starboy', category: 'music', query: 'Starboy The Weeknd' },
  { answer: 'Anti-Hero', category: 'music', query: 'Anti-Hero Taylor Swift' },
  { answer: 'Cruel Summer', category: 'music', query: 'Cruel Summer Taylor Swift' },
  { answer: 'Blank Space', category: 'music', query: 'Blank Space Taylor Swift' },
  { answer: 'Espresso', category: 'music', query: 'Espresso Sabrina Carpenter' },
  { answer: 'Vampire', category: 'music', query: 'vampire Olivia Rodrigo' },
  { answer: 'Good 4 U', category: 'music', query: 'good 4 u Olivia Rodrigo' },
  { answer: 'Watermelon Sugar', category: 'music', query: 'Watermelon Sugar Harry Styles' },
  { answer: 'Dance Monkey', category: 'music', query: 'Dance Monkey Tones and I' },
  { answer: 'Señorita', category: 'music', query: 'Senorita Shawn Mendes Camila Cabello' },
  { answer: 'Havana', category: 'music', query: 'Havana Camila Cabello' },
  { answer: 'Sugar', category: 'music', query: 'Sugar Maroon 5' },
  { answer: 'Payphone', category: 'music', query: 'Payphone Maroon 5' },
  { answer: 'Moves Like Jagger', category: 'music', query: 'Moves Like Jagger Maroon 5' },
  { answer: 'Danza Kuduro', category: 'music', query: 'Danza Kuduro Don Omar' },
  { answer: 'Waka Waka', category: 'music', query: 'Waka Waka Shakira' },
  { answer: 'Hips Don\'t Lie', category: 'music', query: 'Hips Dont Lie Shakira' },
  { answer: 'Umbrella', category: 'music', query: 'Umbrella Rihanna' },
  { answer: 'Diamonds', category: 'music', query: 'Diamonds Rihanna' },
  { answer: 'We Found Love', category: 'music', query: 'We Found Love Rihanna Calvin Harris' },
  { answer: 'Firework', category: 'music', query: 'Firework Katy Perry' },
  { answer: 'Dark Horse', category: 'music', query: 'Dark Horse Katy Perry' },
  { answer: 'Poker Face', category: 'music', query: 'Poker Face Lady Gaga' },
  { answer: 'Shallow', category: 'music', query: 'Shallow Lady Gaga Bradley Cooper' },
  { answer: 'Just Dance', category: 'music', query: 'Just Dance Lady Gaga' },
  { answer: 'Call Me Maybe', category: 'music', query: 'Call Me Maybe Carly Rae Jepsen' },
  { answer: 'Sorry', category: 'music', query: 'Sorry Justin Bieber' },
  { answer: 'Love Yourself', category: 'music', query: 'Love Yourself Justin Bieber' },
  { answer: 'Peaches', category: 'music', query: 'Peaches Justin Bieber' },
  { answer: 'Perfect', category: 'music', query: 'Perfect Ed Sheeran' },
  { answer: 'Photograph', category: 'music', query: 'Photograph Ed Sheeran' },
  { answer: 'Thinking Out Loud', category: 'music', query: 'Thinking Out Loud Ed Sheeran' },
  { answer: 'Cheap Thrills', category: 'music', query: 'Cheap Thrills Sia' },
  { answer: 'Chandelier', category: 'music', query: 'Chandelier Sia' },
  { answer: 'Elastic Heart', category: 'music', query: 'Elastic Heart Sia' },
  { answer: 'Roses', category: 'music', query: 'Roses SAINt JHN Imanbek' },
  { answer: 'Astronomia', category: 'music', query: 'Astronomia Tony Igy Vicetone' },
  { answer: 'Sweet but Psycho', category: 'music', query: 'Sweet but Psycho Ava Max' },
  { answer: 'Physical', category: 'music', query: 'Physical Dua Lipa' },
  { answer: 'Don\'t Start Now', category: 'music', query: 'Dont Start Now Dua Lipa' },
  { answer: 'Watch Me', category: 'music', query: 'Watch Me Whip Silento' },
  { answer: 'Happier', category: 'music', query: 'Happier Marshmello Bastille' },
  { answer: 'Alone', category: 'music', query: 'Alone Marshmello' },
  { answer: 'Wellerman', category: 'music', query: 'Wellerman Nathan Evans' },
  { answer: 'Heat Waves', category: 'music', query: 'Heat Waves Glass Animals' },
  { answer: 'Unstoppable', category: 'music', query: 'Unstoppable Sia' },
  { answer: 'Thunder', category: 'music', query: 'Thunder Imagine Dragons' },
  { answer: 'Demons', category: 'music', query: 'Demons Imagine Dragons' },
  { answer: 'Enemy', category: 'music', query: 'Enemy Imagine Dragons JID' },
  { answer: "Can't Help Falling in Love", category: 'music', query: 'Cant Help Falling in Love Elvis Presley' },
  { answer: 'La Bohème', category: 'music', query: 'La Bohème Charles Aznavour' },
  { answer: 'Ne me quitte pas', category: 'music', query: 'Ne me quitte pas Jacques Brel' },
  { answer: 'Formidable', category: 'music', query: 'Formidable Stromae' },
  { answer: 'Papaoutai', category: 'music', query: 'Papaoutai Stromae' },
  { answer: 'Tout oublier', category: 'music', query: 'Tout oublier Angèle' },
  { answer: 'Sapés comme jamais', category: 'music', query: 'Sapés comme jamais Maître Gims' },
  { answer: 'Bella', category: 'music', query: 'Bella Maître Gims' },
  { answer: 'Pookie', category: 'music', query: 'Pookie Aya Nakamura' },
  { answer: 'Copines', category: 'music', query: 'Copines Aya Nakamura' },
  { answer: 'Basique', category: 'music', query: 'Basique Orelsan' },
  { answer: 'La Terre est ronde', category: 'music', query: 'La Terre est ronde Orelsan' },
];

const FILM: BlindtestEntry[] = [
  { answer: 'Star Wars', category: 'film', query: 'Star Wars Main Title John Williams' },
  { answer: 'Pirates des Caraïbes', category: 'film', query: "He's a Pirate Klaus Badelt" },
  { answer: 'Harry Potter', category: 'film', query: "Hedwig's Theme John Williams" },
  { answer: 'Jurassic Park', category: 'film', query: 'Jurassic Park Theme John Williams' },
  { answer: 'Interstellar', category: 'film', query: 'Cornfield Chase Hans Zimmer' },
  { answer: 'Titanic', category: 'film', query: 'My Heart Will Go On Celine Dion' },
  { answer: 'Le Parrain', category: 'film', query: 'The Godfather Waltz Nino Rota' },
  { answer: 'Mission Impossible', category: 'film', query: 'Mission Impossible Theme' },
  { answer: 'James Bond', category: 'film', query: 'James Bond Theme' },
  { answer: 'Indiana Jones', category: 'film', query: 'Raiders March John Williams' },
  { answer: 'Retour vers le futur', category: 'film', query: 'Back to the Future Theme Alan Silvestri' },
  { answer: 'Rocky', category: 'film', query: 'Gonna Fly Now Rocky' },
  { answer: 'Le Seigneur des Anneaux', category: 'film', query: 'Concerning Hobbits Howard Shore' },
  { answer: 'Gladiator', category: 'film', query: 'Now We Are Free Hans Zimmer' },
  { answer: 'Le Bon, la Brute et le Truand', category: 'film', query: 'The Good the Bad and the Ugly Ennio Morricone' },
  { answer: 'Inception', category: 'film', query: 'Time Hans Zimmer Inception' },
  { answer: 'The Dark Knight', category: 'film', query: 'Why So Serious Hans Zimmer' },
  { answer: 'Avengers', category: 'film', query: 'The Avengers Theme Alan Silvestri' },
  { answer: 'Pulp Fiction', category: 'film', query: 'Misirlou Dick Dale' },
  { answer: 'Forrest Gump', category: 'film', query: 'Forrest Gump Suite Alan Silvestri' },
  { answer: 'E.T.', category: 'film', query: 'E.T. Flying Theme John Williams' },
  { answer: 'Les Dents de la mer', category: 'film', query: 'Jaws Theme John Williams' },
  { answer: 'Halloween', category: 'film', query: 'Halloween Theme John Carpenter' },
  { answer: 'Requiem for a Dream', category: 'film', query: 'Lux Aeterna Clint Mansell' },
  { answer: 'La Liste de Schindler', category: 'film', query: "Schindler's List Theme John Williams" },
  { answer: 'Tron Legacy', category: 'film', query: 'Derezzed Daft Punk Tron' },
  { answer: 'Blade Runner', category: 'film', query: 'Blade Runner Blues Vangelis' },
  { answer: 'Amélie Poulain', category: 'film', query: "Comptine d'un autre été Yann Tiersen" },
  { answer: 'Intouchables', category: 'film', query: 'Una Mattina Ludovico Einaudi' },
  { answer: 'La La Land', category: 'film', query: 'City of Stars La La Land' },
  { answer: 'Whiplash', category: 'film', query: 'Caravan Whiplash' },
  { answer: 'The Greatest Showman', category: 'film', query: 'This Is Me Greatest Showman' },
  { answer: 'Joker', category: 'film', query: 'Joker Hildur Gudnadottir' },
  { answer: 'Top Gun', category: 'film', query: 'Danger Zone Kenny Loggins' },
  { answer: 'Ghostbusters', category: 'film', query: 'Ghostbusters Ray Parker Jr' },
  { answer: 'Men in Black', category: 'film', query: 'Men in Black Will Smith' },
  { answer: 'Grease', category: 'film', query: "You're the One That I Want Grease" },
  { answer: 'Dirty Dancing', category: 'film', query: 'Time of My Life Dirty Dancing' },
  { answer: 'Footloose', category: 'film', query: 'Footloose Kenny Loggins' },
  { answer: 'Saturday Night Fever', category: 'film', query: "Stayin' Alive Bee Gees" },
  { answer: 'The Matrix', category: 'film', query: 'Clubbed to Death Matrix' },
  { answer: 'Kill Bill', category: 'film', query: 'Bang Bang Nancy Sinatra Kill Bill' },
  { answer: 'Cinema Paradiso', category: 'film', query: 'Cinema Paradiso Ennio Morricone' },
  { answer: 'Mad Max Fury Road', category: 'film', query: 'Brothers in Arms Junkie XL Mad Max' },
  { answer: 'Dunkerque', category: 'film', query: 'Supermarine Hans Zimmer Dunkirk' },
  { answer: 'Gladiator', category: 'film', query: 'Now We Are Free Gladiator Lisa Gerrard' },
  { answer: 'Spider-Man', category: 'film', query: 'Spider-Man Theme Danny Elfman 2002' },
  { answer: 'Superman', category: 'film', query: 'Superman March John Williams' },
  { answer: '2001 l’Odyssée de l’espace', category: 'film', query: 'Also Sprach Zarathustra Strauss 2001' },
  { answer: 'Le Roi Arthur', category: 'film', query: 'King Arthur Hans Zimmer' },
  { answer: 'Once Upon a Time in the West', category: 'film', query: "Once Upon a Time in the West Ennio Morricone" },
];

const JEUXVIDEO: BlindtestEntry[] = [
  { answer: 'Super Mario Bros', category: 'jeuxvideo', query: 'Super Mario Bros Theme Koji Kondo' },
  { answer: 'The Legend of Zelda', category: 'jeuxvideo', query: 'The Legend of Zelda Main Theme Koji Kondo' },
  { answer: 'Tetris', category: 'jeuxvideo', query: 'Tetris Theme Korobeiniki' },
  { answer: 'Minecraft', category: 'jeuxvideo', query: 'Minecraft Sweden C418' },
  { answer: 'Sonic the Hedgehog', category: 'jeuxvideo', query: 'Sonic Green Hill Zone' },
  { answer: 'Undertale', category: 'jeuxvideo', query: 'Megalovania Toby Fox' },
  { answer: 'Final Fantasy', category: 'jeuxvideo', query: 'One Winged Angel Nobuo Uematsu' },
  { answer: 'Skyrim', category: 'jeuxvideo', query: 'Dragonborn Skyrim Jeremy Soule' },
  { answer: 'The Last of Us', category: 'jeuxvideo', query: 'The Last of Us Theme Gustavo Santaolalla' },
  { answer: 'Halo', category: 'jeuxvideo', query: "Halo Theme Martin O'Donnell" },
  { answer: 'Doom', category: 'jeuxvideo', query: "At Doom's Gate Mick Gordon" },
  { answer: 'Animal Crossing', category: 'jeuxvideo', query: 'Animal Crossing Main Theme' },
  { answer: 'Mario Kart', category: 'jeuxvideo', query: 'Mario Kart 8 Main Theme' },
  { answer: 'Kingdom Hearts', category: 'jeuxvideo', query: 'Simple and Clean Utada Hikaru' },
  { answer: 'Chrono Trigger', category: 'jeuxvideo', query: 'Chrono Trigger Main Theme Yasunori Mitsuda' },
  { answer: 'Castlevania', category: 'jeuxvideo', query: 'Vampire Killer Castlevania' },
  { answer: 'Mega Man 2', category: 'jeuxvideo', query: 'Mega Man 2 Dr Wily Stage' },
  { answer: 'Street Fighter', category: 'jeuxvideo', query: "Guile's Theme Street Fighter" },
  { answer: 'Mortal Kombat', category: 'jeuxvideo', query: 'Techno Syndrome Mortal Kombat' },
  { answer: 'Donkey Kong Country', category: 'jeuxvideo', query: 'Aquatic Ambience David Wise' },
  { answer: 'Metroid', category: 'jeuxvideo', query: 'Metroid Brinstar Theme' },
  { answer: 'Kirby', category: 'jeuxvideo', query: 'Green Greens Kirby' },
  { answer: 'Splatoon', category: 'jeuxvideo', query: 'Splattack Splatoon' },
  { answer: 'Celeste', category: 'jeuxvideo', query: 'Resurrections Lena Raine Celeste' },
  { answer: 'Hollow Knight', category: 'jeuxvideo', query: 'Hornet Christopher Larkin Hollow Knight' },
  { answer: 'Cuphead', category: 'jeuxvideo', query: 'Die House Kristofer Maddigan Cuphead' },
  { answer: 'Persona 5', category: 'jeuxvideo', query: 'Last Surprise Persona 5' },
  { answer: 'NieR Automata', category: 'jeuxvideo', query: 'Weight of the World NieR Automata' },
  { answer: 'The Witcher 3', category: 'jeuxvideo', query: 'Toss a Coin to Your Witcher' },
  { answer: 'Red Dead Redemption', category: 'jeuxvideo', query: "That's the Way It Is Daniel Lanois" },
  { answer: 'Assassin’s Creed', category: 'jeuxvideo', query: "Ezio's Family Jesper Kyd" },
  { answer: 'Elden Ring', category: 'jeuxvideo', query: 'Elden Ring Main Theme' },
  { answer: 'Dark Souls', category: 'jeuxvideo', query: 'Gwyn Lord of Cinder Dark Souls' },
  { answer: 'God of War', category: 'jeuxvideo', query: 'Memories of Mother Bear McCreary God of War' },
  { answer: 'League of Legends', category: 'jeuxvideo', query: 'POP/STARS K/DA League of Legends' },
  { answer: 'Genshin Impact', category: 'jeuxvideo', query: 'Genshin Impact Main Theme' },
  { answer: 'Portal', category: 'jeuxvideo', query: 'Still Alive Jonathan Coulton Portal' },
  { answer: 'Civilization IV', category: 'jeuxvideo', query: 'Baba Yetu Christopher Tin' },
  { answer: 'Gran Turismo', category: 'jeuxvideo', query: 'Moon Over the Castle Gran Turismo' },
  { answer: 'Pac-Man', category: 'jeuxvideo', query: 'Pac-Man Theme' },
  { answer: 'Crash Bandicoot', category: 'jeuxvideo', query: 'Crash Bandicoot Theme' },
  { answer: 'Banjo-Kazooie', category: 'jeuxvideo', query: 'Banjo-Kazooie Main Theme Grant Kirkhope' },
  { answer: 'Stardew Valley', category: 'jeuxvideo', query: 'Stardew Valley Overture' },
  { answer: 'Cyberpunk 2077', category: 'jeuxvideo', query: 'I Really Want to Stay at Your House Cyberpunk' },
  { answer: 'Fallout', category: 'jeuxvideo', query: 'Fallout Main Theme Mark Morgan' },
  { answer: 'Bioshock', category: 'jeuxvideo', query: 'Bioshock The Ocean on His Shoulders' },
  { answer: 'Overwatch', category: 'jeuxvideo', query: 'Overwatch Main Theme' },
  { answer: 'Sea of Thieves', category: 'jeuxvideo', query: 'Sea of Thieves Maiden Voyage' },
  { answer: 'Mario 64', category: 'jeuxvideo', query: 'Super Mario 64 Bob-omb Battlefield' },
  { answer: 'Pokémon (jeu)', category: 'jeuxvideo', query: 'Pokemon Red Blue Battle Theme' },
  { answer: 'Tomb Raider', category: 'jeuxvideo', query: 'Tomb Raider Main Theme Nathan McCree' },
];

const DISNEY: BlindtestEntry[] = [
  { answer: 'La Reine des Neiges', category: 'disney', query: 'Let It Go Idina Menzel Frozen' },
  { answer: 'Le Roi Lion', category: 'disney', query: 'Circle of Life Lion King' },
  { answer: 'Aladdin', category: 'disney', query: 'A Whole New World Aladdin' },
  { answer: 'La Petite Sirène', category: 'disney', query: 'Part of Your World Little Mermaid' },
  { answer: 'La Belle et la Bête', category: 'disney', query: 'Beauty and the Beast Celine Dion' },
  { answer: 'Vaiana', category: 'disney', query: "How Far I'll Go Moana" },
  { answer: 'Toy Story', category: 'disney', query: "You've Got a Friend in Me Randy Newman" },
  { answer: 'Coco', category: 'disney', query: 'Remember Me Coco' },
  { answer: 'Encanto', category: 'disney', query: "We Don't Talk About Bruno Encanto" },
  { answer: 'Mulan', category: 'disney', query: 'Reflection Mulan' },
  { answer: 'Hercule', category: 'disney', query: 'Go the Distance Hercules' },
  { answer: 'Pocahontas', category: 'disney', query: 'Colors of the Wind Pocahontas' },
  { answer: 'La Reine des Neiges 2', category: 'disney', query: 'Into the Unknown Idina Menzel' },
  { answer: 'Raiponce', category: 'disney', query: 'I See the Light Tangled' },
  { answer: 'La Princesse et la Grenouille', category: 'disney', query: 'Almost There Princess and the Frog' },
  { answer: 'Mary Poppins', category: 'disney', query: 'Supercalifragilisticexpialidocious Mary Poppins' },
  { answer: 'Le Livre de la Jungle', category: 'disney', query: 'I Wanna Be Like You Jungle Book' },
  { answer: 'Cendrillon', category: 'disney', query: 'Bibbidi-Bobbidi-Boo Cinderella' },
  { answer: 'Blanche-Neige', category: 'disney', query: 'Heigh-Ho Snow White' },
  { answer: 'Pinocchio', category: 'disney', query: 'When You Wish Upon a Star Pinocchio' },
  { answer: 'Peter Pan', category: 'disney', query: 'You Can Fly Peter Pan' },
  { answer: 'Dumbo', category: 'disney', query: 'Baby Mine Dumbo' },
  { answer: 'La Belle au bois dormant', category: 'disney', query: 'Once Upon a Dream Sleeping Beauty' },
  { answer: 'Les Aristochats', category: 'disney', query: 'Everybody Wants to Be a Cat Aristocats' },
  { answer: 'Robin des Bois', category: 'disney', query: 'Oo-De-Lally Robin Hood Disney' },
  { answer: 'Les 101 Dalmatiens', category: 'disney', query: 'Cruella De Vil 101 Dalmatians' },
  { answer: 'Le Bossu de Notre-Dame', category: 'disney', query: 'Out There Hunchback of Notre Dame' },
  { answer: 'Tarzan', category: 'disney', query: "You'll Be in My Heart Phil Collins" },
  { answer: 'Lilo et Stitch', category: 'disney', query: 'Hawaiian Roller Coaster Ride Lilo Stitch' },
  { answer: 'Frère des ours', category: 'disney', query: 'On My Way Phil Collins Brother Bear' },
  { answer: 'Le Monde de Nemo', category: 'disney', query: 'Finding Nemo Thomas Newman' },
  { answer: 'Là-haut', category: 'disney', query: 'Married Life Up Michael Giacchino' },
  { answer: 'Les Indestructibles', category: 'disney', query: 'The Incredibles Michael Giacchino' },
  { answer: 'Ratatouille', category: 'disney', query: 'Le Festin Camille Ratatouille' },
  { answer: 'WALL-E', category: 'disney', query: 'Down to Earth Peter Gabriel WALL-E' },
  { answer: 'Monstres et Cie', category: 'disney', query: 'Monsters Inc Randy Newman' },
  { answer: 'Cars', category: 'disney', query: 'Life is a Highway Rascal Flatts Cars' },
  { answer: 'Rebelle', category: 'disney', query: 'Touch the Sky Brave Pixar' },
  { answer: 'Vice-Versa', category: 'disney', query: 'Bundle of Joy Inside Out Michael Giacchino' },
  { answer: 'Soul', category: 'disney', query: 'Soul Trent Reznor Atticus Ross' },
  { answer: 'Zootopie', category: 'disney', query: 'Try Everything Shakira Zootopia' },
  { answer: 'Les Mondes de Ralph', category: 'disney', query: 'Wreck-It Ralph Theme' },
  { answer: 'Kuzco', category: 'disney', query: "Perfect World Sting Emperor's New Groove" },
  { answer: 'Mulan 2', category: 'disney', query: 'Lesson Number One Mulan 2' },
  { answer: 'Hannah Montana', category: 'disney', query: 'The Best of Both Worlds Hannah Montana' },
  { answer: 'High School Musical', category: 'disney', query: "We're All in This Together High School Musical" },
  { answer: 'Camp Rock', category: 'disney', query: 'This Is Me Demi Lovato Camp Rock' },
  { answer: 'Descendants', category: 'disney', query: 'Rotten to the Core Descendants' },
  { answer: 'Luca', category: 'disney', query: 'Luca Dan Romer Pixar' },
  { answer: 'En avant', category: 'disney', query: 'Onward Mychael Danna Pixar' },
];

/* ═══════════ EXPANSION BATCHES ═══════════ */
const MUSIC2: BlindtestEntry[] = [
  { answer: 'We Are the Champions', category: 'music', query: 'We Are the Champions Queen' },
  { answer: "Don't Stop Me Now", category: 'music', query: 'Dont Stop Me Now Queen' },
  { answer: 'Numb', category: 'music', query: 'Numb Linkin Park' },
  { answer: 'Chop Suey!', category: 'music', query: 'Chop Suey System of a Down' },
  { answer: 'Zombie', category: 'music', query: 'Zombie The Cranberries' },
  { answer: 'Losing My Religion', category: 'music', query: 'Losing My Religion R.E.M.' },
  { answer: 'With or Without You', category: 'music', query: 'With or Without You U2' },
  { answer: 'Every Breath You Take', category: 'music', query: 'Every Breath You Take The Police' },
  { answer: 'Purple Rain', category: 'music', query: 'Purple Rain Prince' },
  { answer: 'I Wanna Dance with Somebody', category: 'music', query: 'I Wanna Dance with Somebody Whitney Houston' },
  { answer: 'I Will Always Love You', category: 'music', query: 'I Will Always Love You Whitney Houston' },
  { answer: 'Like a Prayer', category: 'music', query: 'Like a Prayer Madonna' },
  { answer: 'Material Girl', category: 'music', query: 'Material Girl Madonna' },
  { answer: 'Y.M.C.A.', category: 'music', query: 'YMCA Village People' },
  { answer: 'Dancing Queen', category: 'music', query: 'Dancing Queen ABBA' },
  { answer: 'Mamma Mia', category: 'music', query: 'Mamma Mia ABBA' },
  { answer: 'Waterloo', category: 'music', query: 'Waterloo ABBA' },
  { answer: 'September', category: 'music', query: 'September Earth Wind and Fire' },
  { answer: 'Heroes', category: 'music', query: 'Heroes David Bowie' },
  { answer: 'Space Oddity', category: 'music', query: 'Space Oddity David Bowie' },
  { answer: 'Sweet Caroline', category: 'music', query: 'Sweet Caroline Neil Diamond' },
  { answer: 'Take Me Home Country Roads', category: 'music', query: 'Take Me Home Country Roads John Denver' },
  { answer: 'What a Wonderful World', category: 'music', query: 'What a Wonderful World Louis Armstrong' },
  { answer: 'Hey Jude', category: 'music', query: 'Hey Jude The Beatles' },
  { answer: 'Let It Be', category: 'music', query: 'Let It Be The Beatles' },
  { answer: 'Come Together', category: 'music', query: 'Come Together The Beatles' },
  { answer: 'Paint It Black', category: 'music', query: 'Paint It Black The Rolling Stones' },
  { answer: '(I Can\'t Get No) Satisfaction', category: 'music', query: 'Satisfaction The Rolling Stones' },
  { answer: 'Smoke on the Water', category: 'music', query: 'Smoke on the Water Deep Purple' },
  { answer: 'Highway to Hell', category: 'music', query: 'Highway to Hell AC DC' },
  { answer: 'Back in Black', category: 'music', query: 'Back in Black AC DC' },
  { answer: 'Thunderstruck', category: 'music', query: 'Thunderstruck AC DC' },
  { answer: 'Enter Sandman', category: 'music', query: 'Enter Sandman Metallica' },
  { answer: 'Nothing Else Matters', category: 'music', query: 'Nothing Else Matters Metallica' },
  { answer: 'Sweet Home Alabama', category: 'music', query: 'Sweet Home Alabama Lynyrd Skynyrd' },
  { answer: 'Another Brick in the Wall', category: 'music', query: 'Another Brick in the Wall Pink Floyd' },
  { answer: 'Wish You Were Here', category: 'music', query: 'Wish You Were Here Pink Floyd' },
  { answer: 'Comfortably Numb', category: 'music', query: 'Comfortably Numb Pink Floyd' },
  { answer: 'Hallelujah', category: 'music', query: 'Hallelujah Jeff Buckley' },
  { answer: 'Creep', category: 'music', query: 'Creep Radiohead' },
  { answer: 'Californication', category: 'music', query: 'Californication Red Hot Chili Peppers' },
  { answer: 'Under the Bridge', category: 'music', query: 'Under the Bridge Red Hot Chili Peppers' },
  { answer: 'American Idiot', category: 'music', query: 'American Idiot Green Day' },
  { answer: 'Wake Me Up When September Ends', category: 'music', query: 'Wake Me Up When September Ends Green Day' },
  { answer: 'In Da Club', category: 'music', query: 'In Da Club 50 Cent' },
  { answer: 'Without Me', category: 'music', query: 'Without Me Eminem' },
  { answer: "Gangsta's Paradise", category: 'music', query: 'Gangstas Paradise Coolio' },
  { answer: 'California Love', category: 'music', query: 'California Love 2Pac' },
  { answer: 'Empire State of Mind', category: 'music', query: 'Empire State of Mind Jay-Z Alicia Keys' },
  { answer: 'Grace Kelly', category: 'music', query: 'Grace Kelly Mika' },
  { answer: 'Elle me dit', category: 'music', query: 'Elle me dit Mika' },
  { answer: 'Prayer in C', category: 'music', query: 'Prayer in C Lilly Wood Robin Schulz' },
  { answer: 'Stole the Show', category: 'music', query: 'Stole the Show Kygo' },
  { answer: 'Firestone', category: 'music', query: 'Firestone Kygo' },
  { answer: 'La Grenade', category: 'music', query: 'La Grenade Clara Luciani' },
  { answer: 'Joe le taxi', category: 'music', query: 'Joe le taxi Vanessa Paradis' },
  { answer: 'Voyage voyage', category: 'music', query: 'Voyage voyage Desireless' },
  { answer: "Ella, elle l'a", category: 'music', query: 'Ella elle la France Gall' },
  { answer: 'Foule sentimentale', category: 'music', query: 'Foule sentimentale Alain Souchon' },
  { answer: 'Les Champs-Élysées', category: 'music', query: 'Les Champs Elysées Joe Dassin' },
  { answer: 'La Javanaise', category: 'music', query: 'La Javanaise Serge Gainsbourg' },
  { answer: 'Mistral gagnant', category: 'music', query: 'Mistral gagnant Renaud' },
  { answer: 'Santiano', category: 'music', query: 'Santiano Hugues Aufray' },
  { answer: 'Belle', category: 'music', query: 'Belle Notre-Dame de Paris Garou' },
  { answer: 'Comme d\'habitude', category: 'music', query: 'Comme dhabitude Claude François' },
  { answer: 'Alexandrie Alexandra', category: 'music', query: 'Alexandrie Alexandra Claude François' },
  { answer: 'Get Lucky', category: 'music', query: 'One More Time Daft Punk' },
  { answer: 'Around the World', category: 'music', query: 'Around the World Daft Punk' },
  { answer: 'Bella Ciao', category: 'music', query: 'Bella Ciao' },
  { answer: 'Wonderwall', category: 'music', query: "Don't Look Back in Anger Oasis" },
  { answer: 'Numb / Encore', category: 'music', query: 'Numb Encore Jay-Z Linkin Park' },
];

const ANIME2: BlindtestEntry[] = [
  { answer: 'Kill la Kill', category: 'anime', query: 'Sirius Eir Aoi' },
  { answer: 'No Game No Life', category: 'anime', query: 'This Game Konomi Suzuki' },
  { answer: 'Darling in the Franxx', category: 'anime', query: 'Kiss of Death Mika Nakashima Hyde' },
  { answer: 'Yuri on Ice', category: 'anime', query: 'History Maker Dean Fujioka' },
  { answer: 'Violet Evergarden', category: 'anime', query: 'Sincerely TRUE Violet Evergarden' },
  { answer: 'A Silent Voice', category: 'anime', query: 'Koe no Katachi Lit' },
  { answer: 'Weathering with You', category: 'anime', query: 'Grand Escape RADWIMPS' },
  { answer: 'Suzume', category: 'anime', query: 'Suzume RADWIMPS Toaka' },
  { answer: 'Bungou Stray Dogs', category: 'anime', query: 'Trash Candy Granrodeo' },
  { answer: 'The Rising of the Shield Hero', category: 'anime', query: 'Faith Madkid Shield Hero' },
  { answer: 'That Time I Got Reincarnated as a Slime', category: 'anime', query: 'Nameless Story Takuma Terashima' },
  { answer: 'Anohana', category: 'anime', query: 'Aoi Shiori Galileo Galilei' },
  { answer: 'Free!', category: 'anime', query: 'Rage On Oldcodex' },
  { answer: 'Clannad', category: 'anime', query: 'Toki wo Kizamu Uta Lia' },
  { answer: 'K-On!', category: 'anime', query: 'Cagayake Girls Ho-kago Tea Time' },
  { answer: 'Lucky Star', category: 'anime', query: 'Motteke Sailor Fuku' },
  { answer: 'The Melancholy of Haruhi Suzumiya', category: 'anime', query: 'Bouken Desho Desho Aya Hirano' },
  { answer: 'Toradora', category: 'anime', query: 'Pre-Parade Toradora' },
  { answer: 'Nisekoi', category: 'anime', query: 'Click Claris Nisekoi' },
  { answer: 'Overlord', category: 'anime', query: 'Clattanoia OxT' },
  { answer: 'Akame ga Kill', category: 'anime', query: 'Skyreach Sora Amamiya' },
  { answer: 'Parasyte', category: 'anime', query: 'Let Me Hear Fear and Loathing in Las Vegas' },
  { answer: 'Noragami', category: 'anime', query: 'Goya no Machiawase Hello Sleepwalkers' },
  { answer: 'Charlotte', category: 'anime', query: 'Bravely You Lia Charlotte' },
  { answer: 'Gintama', category: 'anime', query: 'Pray Tommy heavenly6 Gintama' },
  { answer: 'Ouran High School Host Club', category: 'anime', query: 'Sakura Kiss Chieco Kawabe' },
  { answer: 'Black Lagoon', category: 'anime', query: 'Red Fraction Mell' },
  { answer: 'Made in Abyss', category: 'anime', query: 'Deep in Abyss Made in Abyss' },
  { answer: 'Goblin Slayer', category: 'anime', query: 'Rightfully Mili Goblin Slayer' },
  { answer: 'Dr. Stone', category: 'anime', query: 'Sangenshoku Dr Stone' },
  { answer: 'Ranking of Kings', category: 'anime', query: 'Boku no Kotoba King Gnu' },
  { answer: '86 Eighty-Six', category: 'anime', query: '3-pun Kankaku Hitorigoto' },
  { answer: 'Lycoris Recoil', category: 'anime', query: 'Alive Sayuri Lycoris Recoil' },
  { answer: 'Mushoku Tensei', category: 'anime', query: 'Spiral Largo Mushoku Tensei' },
  { answer: 'Slam Dunk', category: 'anime', query: 'Kimi ga Suki da to Sakebitai Baad' },
  { answer: 'Hellsing', category: 'anime', query: 'Logos Naki World Hellsing' },
  { answer: 'Trigun', category: 'anime', query: 'H.T. Tsuneo Imahori Trigun' },
  { answer: 'Baccano!', category: 'anime', query: 'Guns and Roses Paradise Lunch Baccano' },
  { answer: 'Durarara!!', category: 'anime', query: 'Uragiri no Yuuyake Theatre Brook' },
  { answer: 'Nana', category: 'anime', query: 'Rose Anna Tsuchiya Nana' },
  { answer: 'Fruits Basket', category: 'anime', query: 'Again Beverly Fruits Basket' },
  { answer: 'Given', category: 'anime', query: 'Kizuato Centimillimental Given' },
  { answer: 'Cyberpunk Edgerunners', category: 'anime', query: 'This Fffire Franz Ferdinand' },
  { answer: 'Vivy', category: 'anime', query: 'Sing My Pleasure Vivy' },
  { answer: 'Ranma 1/2', category: 'anime', query: 'Jajauma ni Sasenaide Ranma' },
  { answer: 'Dragon Ball Super', category: 'anime', query: 'Chozetsu Dynamic Dragon Ball Super' },
  { answer: 'Boruto', category: 'anime', query: 'Baku Ikimonogakari Boruto' },
  { answer: 'Digimon', category: 'anime', query: 'Butter-Fly Kouji Wada' },
  { answer: 'Yu-Gi-Oh!', category: 'anime', query: 'Voice Masami Okui Yu-Gi-Oh' },
  { answer: 'Nichijou', category: 'anime', query: 'Hyadain no Kakakata Nichijou' },
  { answer: 'Wotakoi', category: 'anime', query: 'Fiction Sumika Wotakoi' },
  { answer: 'Plastic Memories', category: 'anime', query: 'Ring of Fortune Plastic Memories' },
  { answer: 'Berserk', category: 'anime', query: 'Tell Me Why Penpals Berserk' },
  { answer: 'Fate/stay night', category: 'anime', query: 'This Illusion Fate stay night' },
  { answer: 'Highschool of the Dead', category: 'anime', query: 'Highschool of the Dead opening' },
  { answer: 'Log Horizon', category: 'anime', query: 'Database Man with a Mission Log Horizon' },
  { answer: 'Chihayafuru', category: 'anime', query: 'Youthful Chihayafuru' },
  { answer: 'ReLIFE', category: 'anime', query: 'Button Penguin Research ReLIFE' },
  { answer: 'Grand Blue', category: 'anime', query: 'Grand Blue opening' },
];

const FILM2: BlindtestEntry[] = [
  { answer: 'Le Roi Arthur', category: 'film', query: 'King Arthur Hans Zimmer' },
  { answer: 'Braveheart', category: 'film', query: 'Braveheart Main Title James Horner' },
  { answer: 'Le Dernier des Mohicans', category: 'film', query: 'Last of the Mohicans Main Theme' },
  { answer: 'La Ligne verte', category: 'film', query: 'The Green Mile Thomas Newman' },
  { answer: 'American Beauty', category: 'film', query: 'American Beauty Thomas Newman' },
  { answer: 'Le Fabuleux Destin d\'Amélie Poulain', category: 'film', query: "La Valse d'Amélie Yann Tiersen" },
  { answer: 'Le Cinquième Élément', category: 'film', query: 'The Fifth Element Diva Dance Eric Serra' },
  { answer: 'Léon', category: 'film', query: 'Léon Eric Serra Shape of My Heart' },
  { answer: 'Kill Bill vol.2', category: 'film', query: "Malaguena Salerosa Kill Bill" },
  { answer: 'Django Unchained', category: 'film', query: 'Django Unchained soundtrack' },
  { answer: 'Le Discours d\'un roi', category: 'film', query: 'The Kings Speech Alexandre Desplat' },
  { answer: 'The Grand Budapest Hotel', category: 'film', query: 'Grand Budapest Hotel Alexandre Desplat' },
  { answer: 'Slumdog Millionaire', category: 'film', query: 'Jai Ho A.R. Rahman' },
  { answer: 'Skyfall', category: 'film', query: 'Skyfall Adele' },
  { answer: 'La Môme', category: 'film', query: 'La Vie en rose Marion Cotillard La Môme' },
  { answer: 'Batman Begins', category: 'film', query: 'Batman Begins Hans Zimmer' },
  { answer: 'Man of Steel', category: 'film', query: 'Man of Steel Hans Zimmer' },
  { answer: 'Wonder Woman', category: 'film', query: 'Wonder Woman Theme Hans Zimmer' },
  { answer: 'Black Panther', category: 'film', query: 'Black Panther Ludwig Goransson' },
  { answer: 'Dune', category: 'film', query: 'Dune Hans Zimmer Paul Dream' },
  { answer: 'Le Livre de la jungle', category: 'film', query: 'The Jungle Book 2016 score' },
  { answer: 'La La Land', category: 'film', query: 'Another Day of Sun La La Land' },
  { answer: 'Bohemian Rhapsody', category: 'film', query: 'Bohemian Rhapsody film Queen Live Aid' },
  { answer: 'Rocketman', category: 'film', query: 'Rocketman Taron Egerton' },
  { answer: 'Baby Driver', category: 'film', query: 'Baby Driver soundtrack Bellbottoms' },
  { answer: 'Drive', category: 'film', query: 'Nightcall Kavinsky Drive' },
  { answer: 'Trainspotting', category: 'film', query: 'Lust for Life Iggy Pop Trainspotting' },
  { answer: 'Guardians of the Galaxy', category: 'film', query: 'Hooked on a Feeling Guardians of the Galaxy' },
  { answer: 'La Haine', category: 'film', query: 'La Haine Assassin bande originale' },
  { answer: 'Intouchables', category: 'film', query: 'Fly Ludovico Einaudi Intouchables' },
  { answer: 'Le Grand Bleu', category: 'film', query: 'Le Grand Bleu Eric Serra' },
  { answer: 'Les Choristes', category: 'film', query: 'Vois sur ton chemin Les Choristes' },
  { answer: 'Taxi', category: 'film', query: 'Taxi IAM bande originale' },
  { answer: 'Casse-Noisette', category: 'film', query: 'Nutcracker Suite Tchaikovsky' },
  { answer: 'Mommy', category: 'film', query: 'Wonderwall Oasis Mommy Xavier Dolan' },
  { answer: 'Requiem', category: 'film', query: 'Lux Aeterna Requiem for a Dream Clint Mansell' },
  { answer: 'Twilight', category: 'film', query: 'Bella Lullaby Carter Burwell Twilight' },
  { answer: 'Le Voyage de Chihiro', category: 'film', query: 'One Summer Day Joe Hisaishi Spirited Away' },
  { answer: 'Princesse Mononoké', category: 'film', query: 'Princess Mononoke Joe Hisaishi' },
  { answer: 'Le Château ambulant', category: 'film', query: 'Merry Go Round of Life Joe Hisaishi Howl' },
  { answer: 'Mon voisin Totoro', category: 'film', query: 'Tonari no Totoro Joe Hisaishi' },
];

const DISNEY2: BlindtestEntry[] = [
  { answer: 'Raiponce', category: 'disney', query: 'I See the Light Tangled' },
  { answer: 'La Reine des Neiges 2', category: 'disney', query: 'Into the Unknown Frozen 2' },
  { answer: 'Mary Poppins', category: 'disney', query: 'Supercalifragilistic Mary Poppins' },
  { answer: 'Le Livre de la Jungle', category: 'disney', query: 'The Bare Necessities Jungle Book' },
  { answer: 'Cendrillon', category: 'disney', query: 'Bibbidi-Bobbidi-Boo Cinderella' },
  { answer: 'Blanche-Neige', category: 'disney', query: 'Heigh-Ho Snow White' },
  { answer: 'Pinocchio', category: 'disney', query: 'When You Wish Upon a Star Pinocchio' },
  { answer: 'Peter Pan', category: 'disney', query: 'You Can Fly Peter Pan' },
  { answer: 'La Belle au bois dormant', category: 'disney', query: 'Once Upon a Dream Sleeping Beauty' },
  { answer: 'Les Aristochats', category: 'disney', query: 'Everybody Wants to Be a Cat Aristocats' },
  { answer: 'Robin des Bois', category: 'disney', query: 'Oo-De-Lally Robin Hood Disney' },
  { answer: 'Les 101 Dalmatiens', category: 'disney', query: 'Cruella De Vil 101 Dalmatians' },
  { answer: 'Le Bossu de Notre-Dame', category: 'disney', query: 'Out There Hunchback of Notre Dame' },
  { answer: 'Tarzan', category: 'disney', query: "You'll Be in My Heart Phil Collins" },
  { answer: 'Lilo et Stitch', category: 'disney', query: 'Hawaiian Roller Coaster Ride Lilo Stitch' },
  { answer: 'Le Monde de Nemo', category: 'disney', query: 'Finding Nemo Thomas Newman' },
  { answer: 'Là-haut', category: 'disney', query: 'Married Life Up Michael Giacchino' },
  { answer: 'Les Indestructibles', category: 'disney', query: 'The Incredibles Michael Giacchino' },
  { answer: 'Ratatouille', category: 'disney', query: 'Le Festin Camille Ratatouille' },
  { answer: 'WALL-E', category: 'disney', query: 'Down to Earth Peter Gabriel WALL-E' },
  { answer: 'Monstres et Cie', category: 'disney', query: 'Monsters Inc Randy Newman' },
  { answer: 'Cars', category: 'disney', query: 'Life is a Highway Rascal Flatts Cars' },
  { answer: 'Rebelle', category: 'disney', query: 'Touch the Sky Brave Pixar' },
  { answer: 'Vice-Versa', category: 'disney', query: 'Bundle of Joy Inside Out' },
  { answer: 'Zootopie', category: 'disney', query: 'Try Everything Shakira Zootopia' },
  { answer: 'Les Mondes de Ralph', category: 'disney', query: 'Wreck-It Ralph Theme' },
  { answer: 'Kuzco', category: 'disney', query: "Perfect World Emperor's New Groove" },
  { answer: 'High School Musical', category: 'disney', query: "We're All in This Together High School Musical" },
  { answer: 'Descendants', category: 'disney', query: 'Rotten to the Core Descendants' },
  { answer: 'Soul', category: 'disney', query: 'Soul Trent Reznor Atticus Ross' },
  { answer: 'En avant', category: 'disney', query: 'Onward Mychael Danna Pixar' },
  { answer: 'Wish', category: 'disney', query: 'This Wish Ariana DeBose Wish' },
  { answer: 'Le Roi Lion 2', category: 'disney', query: 'He Lives in You Lion King 2' },
];

const CARTOON2: BlindtestEntry[] = [
  { answer: 'Les Simpson', category: 'cartoon', query: 'The Simpsons End Credits Danny Elfman' },
  { answer: 'Futurama', category: 'cartoon', query: 'Futurama Theme Christopher Tyng' },
  { answer: 'South Park', category: 'cartoon', query: 'South Park Theme Primus' },
  { answer: 'Steven Universe', category: 'cartoon', query: 'Steven Universe Theme' },
  { answer: 'Adventure Time', category: 'cartoon', query: 'Adventure Time Theme' },
  { answer: 'Gravity Falls', category: 'cartoon', query: 'Gravity Falls Theme' },
  { answer: 'Le Monde incroyable de Gumball', category: 'cartoon', query: 'Amazing World of Gumball Theme' },
  { answer: 'We Bare Bears', category: 'cartoon', query: 'We Bare Bears Theme' },
  { answer: 'Regular Show', category: 'cartoon', query: 'Regular Show Theme' },
  { answer: 'Samouraï Jack', category: 'cartoon', query: 'Samurai Jack Theme' },
  { answer: 'Dexter', category: 'cartoon', query: "Dexter's Laboratory Theme" },
  { answer: 'Le Laboratoire de Dexter', category: 'cartoon', query: 'Dexter Laboratory end theme' },
  { answer: 'Bip Bip et Coyote', category: 'cartoon', query: 'Looney Tunes Road Runner theme' },
  { answer: 'Animaniacs', category: 'cartoon', query: 'Animaniacs Theme' },
  { answer: "Il était une fois l'homme", category: 'cartoon', query: "Il était une fois l'homme générique" },
  { answer: 'Chapi Chapo', category: 'cartoon', query: 'Chapi Chapo générique' },
  { answer: 'Barbapapa', category: 'cartoon', query: 'Barbapapa générique' },
  { answer: 'Casimir', category: 'cartoon', query: "L'Île aux enfants Casimir générique" },
  { answer: 'Kiri le clown', category: 'cartoon', query: 'Kiri le clown générique' },
  { answer: 'Nils Holgersson', category: 'cartoon', query: 'Nils Holgersson générique' },
  { answer: "Signé Cat's Eyes", category: 'cartoon', query: "Signé Cat's Eyes générique" },
  { answer: 'Les Snorky', category: 'cartoon', query: 'Les Snorky générique' },
  { answer: 'Clémentine', category: 'cartoon', query: 'Clémentine générique dessin animé' },
  { answer: 'Pole Position', category: 'cartoon', query: 'Pole Position générique' },
];

const JEUXVIDEO2: BlindtestEntry[] = [
  { answer: 'Kingdom Hearts', category: 'jeuxvideo', query: 'Dearly Beloved Kingdom Hearts' },
  { answer: 'Chrono Trigger', category: 'jeuxvideo', query: 'Chrono Trigger Main Theme Mitsuda' },
  { answer: 'Castlevania', category: 'jeuxvideo', query: 'Bloody Tears Castlevania' },
  { answer: 'Mega Man 2', category: 'jeuxvideo', query: 'Mega Man 2 Dr Wily Stage' },
  { answer: 'Street Fighter II', category: 'jeuxvideo', query: 'Ryu Theme Street Fighter II' },
  { answer: 'Mortal Kombat', category: 'jeuxvideo', query: 'Techno Syndrome Mortal Kombat' },
  { answer: 'Donkey Kong Country', category: 'jeuxvideo', query: 'Aquatic Ambience David Wise' },
  { answer: 'Metroid', category: 'jeuxvideo', query: 'Metroid Brinstar Theme' },
  { answer: 'Kirby', category: 'jeuxvideo', query: 'Green Greens Kirby' },
  { answer: 'Persona 5', category: 'jeuxvideo', query: 'Last Surprise Persona 5' },
  { answer: 'NieR Automata', category: 'jeuxvideo', query: 'Weight of the World NieR Automata' },
  { answer: 'The Witcher 3', category: 'jeuxvideo', query: 'Toss a Coin to Your Witcher' },
  { answer: 'Assassin\'s Creed 2', category: 'jeuxvideo', query: "Ezio's Family Jesper Kyd" },
  { answer: 'Elden Ring', category: 'jeuxvideo', query: 'Elden Ring Main Theme' },
  { answer: 'Dark Souls', category: 'jeuxvideo', query: 'Gwyn Lord of Cinder Dark Souls' },
  { answer: 'God of War', category: 'jeuxvideo', query: 'Memories of Mother Bear McCreary' },
  { answer: 'Cuphead', category: 'jeuxvideo', query: 'Die House Cuphead' },
  { answer: 'Hollow Knight', category: 'jeuxvideo', query: 'Hornet Hollow Knight Larkin' },
  { answer: 'Celeste', category: 'jeuxvideo', query: 'Resurrections Lena Raine Celeste' },
  { answer: 'Portal', category: 'jeuxvideo', query: 'Still Alive Portal Jonathan Coulton' },
  { answer: 'Civilization IV', category: 'jeuxvideo', query: 'Baba Yetu Christopher Tin' },
  { answer: 'Halo', category: 'jeuxvideo', query: "Halo Theme Martin O'Donnell" },
  { answer: 'Doom', category: 'jeuxvideo', query: "At Doom's Gate Mick Gordon" },
  { answer: 'League of Legends', category: 'jeuxvideo', query: 'POP/STARS K/DA League of Legends' },
  { answer: 'Genshin Impact', category: 'jeuxvideo', query: 'Genshin Impact Main Theme' },
  { answer: 'Cyberpunk 2077', category: 'jeuxvideo', query: 'I Really Want to Stay Cyberpunk' },
  { answer: 'Red Dead Redemption 2', category: 'jeuxvideo', query: "That's the Way It Is Daniel Lanois" },
  { answer: 'Crash Bandicoot', category: 'jeuxvideo', query: 'Crash Bandicoot N Sane theme' },
  { answer: 'Banjo-Kazooie', category: 'jeuxvideo', query: 'Banjo-Kazooie Main Theme Grant Kirkhope' },
  { answer: 'Stardew Valley', category: 'jeuxvideo', query: 'Stardew Valley Overture' },
];

const KPOP: BlindtestEntry[] = [
  { answer: 'Butter', category: 'kpop', query: 'Butter BTS' },
  { answer: 'Boy With Luv', category: 'kpop', query: 'Boy With Luv BTS' },
  { answer: 'Fake Love', category: 'kpop', query: 'Fake Love BTS' },
  { answer: 'DNA', category: 'kpop', query: 'DNA BTS' },
  { answer: 'Idol', category: 'kpop', query: 'Idol BTS' },
  { answer: 'Spring Day', category: 'kpop', query: 'Spring Day BTS' },
  { answer: 'Blood Sweat & Tears', category: 'kpop', query: 'Blood Sweat Tears BTS' },
  { answer: 'DDU-DU DDU-DU', category: 'kpop', query: 'DDU-DU DDU-DU BLACKPINK' },
  { answer: 'Kill This Love', category: 'kpop', query: 'Kill This Love BLACKPINK' },
  { answer: 'How You Like That', category: 'kpop', query: 'How You Like That BLACKPINK' },
  { answer: 'Pink Venom', category: 'kpop', query: 'Pink Venom BLACKPINK' },
  { answer: 'Boombayah', category: 'kpop', query: 'BOOMBAYAH BLACKPINK' },
  { answer: 'Shut Down', category: 'kpop', query: 'Shut Down BLACKPINK' },
  { answer: 'Lovesick Girls', category: 'kpop', query: 'Lovesick Girls BLACKPINK' },
  { answer: 'Fancy', category: 'kpop', query: 'Fancy TWICE' },
  { answer: 'What Is Love?', category: 'kpop', query: 'What Is Love TWICE' },
  { answer: 'TT', category: 'kpop', query: 'TT TWICE' },
  { answer: 'Feel Special', category: 'kpop', query: 'Feel Special TWICE' },
  { answer: 'Cheer Up', category: 'kpop', query: 'Cheer Up TWICE' },
  { answer: 'Growl', category: 'kpop', query: 'Growl EXO' },
  { answer: 'Love Shot', category: 'kpop', query: 'Love Shot EXO' },
  { answer: 'Psycho', category: 'kpop', query: 'Psycho Red Velvet' },
  { answer: 'Bad Boy', category: 'kpop', query: 'Bad Boy Red Velvet' },
  { answer: "God's Menu", category: 'kpop', query: 'Gods Menu Stray Kids' },
  { answer: 'Thunderous', category: 'kpop', query: 'Thunderous Stray Kids' },
  { answer: 'Ditto', category: 'kpop', query: 'Ditto NewJeans' },
  { answer: 'Hype Boy', category: 'kpop', query: 'Hype Boy NewJeans' },
  { answer: 'Super Shy', category: 'kpop', query: 'Super Shy NewJeans' },
  { answer: 'OMG', category: 'kpop', query: 'OMG NewJeans' },
  { answer: 'Tomboy', category: 'kpop', query: 'Tomboy GIDLE' },
  { answer: 'Next Level', category: 'kpop', query: 'Next Level aespa' },
  { answer: 'Savage', category: 'kpop', query: 'Savage aespa' },
  { answer: 'Spicy', category: 'kpop', query: 'Spicy aespa' },
  { answer: 'Antifragile', category: 'kpop', query: 'Antifragile LE SSERAFIM' },
  { answer: 'Fantastic Baby', category: 'kpop', query: 'Fantastic Baby BIGBANG' },
  { answer: 'Gee', category: 'kpop', query: "Gee Girls' Generation" },
];

const RETRO: BlindtestEntry[] = [
  { answer: 'Beat It', category: 'retro', query: 'Beat It Michael Jackson' },
  { answer: 'Wake Me Up Before You Go-Go', category: 'retro', query: 'Wake Me Up Before You Go-Go Wham' },
  { answer: 'Careless Whisper', category: 'retro', query: 'Careless Whisper George Michael' },
  { answer: 'Every Breath You Take', category: 'retro', query: 'Every Breath You Take The Police' },
  { answer: 'Girls Just Want to Have Fun', category: 'retro', query: 'Girls Just Want to Have Fun Cyndi Lauper' },
  { answer: 'Time After Time', category: 'retro', query: 'Time After Time Cyndi Lauper' },
  { answer: 'I Wanna Dance with Somebody', category: 'retro', query: 'I Wanna Dance with Somebody Whitney Houston' },
  { answer: 'Like a Prayer', category: 'retro', query: 'Like a Prayer Madonna' },
  { answer: 'Material Girl', category: 'retro', query: 'Material Girl Madonna' },
  { answer: 'Like a Virgin', category: 'retro', query: 'Like a Virgin Madonna' },
  { answer: 'Tainted Love', category: 'retro', query: 'Tainted Love Soft Cell' },
  { answer: "Don't You (Forget About Me)", category: 'retro', query: 'Dont You Forget About Me Simple Minds' },
  { answer: 'Never Gonna Give You Up', category: 'retro', query: 'Never Gonna Give You Up Rick Astley' },
  { answer: 'The Final Countdown', category: 'retro', query: 'The Final Countdown Europe' },
  { answer: 'Eye of the Tiger', category: 'retro', query: 'Eye of the Tiger Survivor' },
  { answer: 'Enjoy the Silence', category: 'retro', query: 'Enjoy the Silence Depeche Mode' },
  { answer: 'With or Without You', category: 'retro', query: 'With or Without You U2' },
  { answer: 'Purple Rain', category: 'retro', query: 'Purple Rain Prince' },
  { answer: 'When Doves Cry', category: 'retro', query: 'When Doves Cry Prince' },
  { answer: 'Karma Chameleon', category: 'retro', query: 'Karma Chameleon Culture Club' },
  { answer: '99 Luftballons', category: 'retro', query: '99 Luftballons Nena' },
  { answer: 'Self Control', category: 'retro', query: 'Self Control Laura Branigan' },
  { answer: 'Maniac', category: 'retro', query: 'Maniac Michael Sembello' },
  { answer: 'No Scrubs', category: 'retro', query: 'No Scrubs TLC' },
  { answer: 'Waterfalls', category: 'retro', query: 'Waterfalls TLC' },
  { answer: '...Baby One More Time', category: 'retro', query: 'Baby One More Time Britney Spears' },
  { answer: 'Believe', category: 'retro', query: 'Believe Cher' },
  { answer: 'Torn', category: 'retro', query: 'Torn Natalie Imbruglia' },
  { answer: 'Zombie', category: 'retro', query: 'Zombie The Cranberries' },
  { answer: 'Barbie Girl', category: 'retro', query: 'Barbie Girl Aqua' },
  { answer: 'What Is Love', category: 'retro', query: 'What Is Love Haddaway' },
  { answer: 'Blue (Da Ba Dee)', category: 'retro', query: 'Blue Da Ba Dee Eiffel 65' },
  { answer: 'Bitter Sweet Symphony', category: 'retro', query: 'Bitter Sweet Symphony The Verve' },
  { answer: 'Creep', category: 'retro', query: 'Creep Radiohead' },
  { answer: 'Losing My Religion', category: 'retro', query: 'Losing My Religion R.E.M.' },
];

const SERIES: BlindtestEntry[] = [
  { answer: 'Game of Thrones', category: 'series', query: 'Game of Thrones Main Title Ramin Djawadi' },
  { answer: 'Stranger Things', category: 'series', query: 'Stranger Things Kyle Dixon Michael Stein' },
  { answer: 'Friends', category: 'series', query: "I'll Be There for You The Rembrandts" },
  { answer: 'Peaky Blinders', category: 'series', query: 'Red Right Hand Nick Cave' },
  { answer: 'The Walking Dead', category: 'series', query: 'The Walking Dead Theme Bear McCreary' },
  { answer: 'Breaking Bad', category: 'series', query: 'Breaking Bad Main Title Dave Porter' },
  { answer: 'Sherlock', category: 'series', query: 'Sherlock Opening Titles David Arnold' },
  { answer: 'Doctor Who', category: 'series', query: 'Doctor Who Theme Murray Gold' },
  { answer: 'Westworld', category: 'series', query: 'Westworld Main Theme Ramin Djawadi' },
  { answer: 'The Mandalorian', category: 'series', query: 'The Mandalorian Ludwig Goransson' },
  { answer: 'House of the Dragon', category: 'series', query: 'House of the Dragon Main Title Ramin Djawadi' },
  { answer: 'The Witcher', category: 'series', query: 'Toss a Coin to Your Witcher' },
  { answer: 'Squid Game', category: 'series', query: 'Squid Game Way Back Then Jung Jae-il' },
  { answer: 'Wednesday', category: 'series', query: 'Wednesday Danny Elfman' },
  { answer: 'La Casa de Papel', category: 'series', query: 'Bella Ciao La Casa de Papel' },
  { answer: 'Dexter', category: 'series', query: 'Dexter Main Title Theme Rolfe Kent' },
  { answer: 'Lost', category: 'series', query: 'Lost Life and Death Michael Giacchino' },
  { answer: 'Twin Peaks', category: 'series', query: 'Twin Peaks Theme Angelo Badalamenti' },
  { answer: 'The X-Files', category: 'series', query: 'X-Files Theme Mark Snow' },
  { answer: 'The Simpsons', category: 'series', query: 'The Simpsons Main Title Theme Danny Elfman' },
  { answer: 'Succession', category: 'series', query: 'Succession Main Title Theme Nicholas Britell' },
  { answer: 'The Crown', category: 'series', query: 'The Crown Main Title Hans Zimmer' },
  { answer: 'Vikings', category: 'series', query: 'If I Had a Heart Fever Ray' },
  { answer: 'Narcos', category: 'series', query: 'Tuyo Rodrigo Amarante' },
  { answer: 'Better Call Saul', category: 'series', query: 'Better Call Saul Main Title Theme' },
  { answer: 'The Last of Us', category: 'series', query: 'The Last of Us Gustavo Santaolalla' },
  { answer: 'Downton Abbey', category: 'series', query: 'Downton Abbey The Suite John Lunn' },
  { answer: 'True Blood', category: 'series', query: 'Bad Things Jace Everett' },
  { answer: 'Mad Men', category: 'series', query: 'Mad Men Theme A Beautiful Mine RJD2' },
  { answer: 'Black Mirror', category: 'series', query: 'Black Mirror Main Title' },
];

const RAPFR: BlindtestEntry[] = [
  { answer: 'Bande organisée', category: 'rapfr', query: 'Bande organisée 13 Organisé' },
  { answer: 'DKR', category: 'rapfr', query: 'DKR Booba' },
  { answer: 'Au DD', category: 'rapfr', query: 'Au DD PNL' },
  { answer: 'Blanka', category: 'rapfr', query: 'Blanka PNL' },
  { answer: "À l'ammoniaque", category: 'rapfr', query: 'A lammoniaque PNL' },
  { answer: 'Onizuka', category: 'rapfr', query: 'Onizuka PNL' },
  { answer: 'Tchikita', category: 'rapfr', query: 'Tchikita Jul' },
  { answer: 'Wesh alors', category: 'rapfr', query: 'Wesh alors Jul' },
  { answer: 'Ma jolie', category: 'rapfr', query: 'Ma jolie Jul' },
  { answer: 'Lettre à une femme', category: 'rapfr', query: 'Lettre à une femme Ninho' },
  { answer: 'Jefe', category: 'rapfr', query: 'Jefe Ninho' },
  { answer: 'Macarena', category: 'rapfr', query: 'Macarena Damso' },
  { answer: 'Julien', category: 'rapfr', query: 'Julien Damso' },
  { answer: '911', category: 'rapfr', query: '911 Damso' },
  { answer: 'On verra', category: 'rapfr', query: 'On verra Nekfeu' },
  { answer: 'Égérie', category: 'rapfr', query: 'Égérie Nekfeu' },
  { answer: 'Basique', category: 'rapfr', query: 'Basique Orelsan' },
  { answer: 'La quête', category: 'rapfr', query: 'La quête Orelsan' },
  { answer: 'Tout va bien', category: 'rapfr', query: 'Tout va bien Orelsan' },
  { answer: "L'odeur de l'essence", category: 'rapfr', query: 'Lodeur de lessence Orelsan' },
  { answer: 'Bella', category: 'rapfr', query: 'Bella Maître Gims' },
  { answer: 'Sapés comme jamais', category: 'rapfr', query: 'Sapés comme jamais Maître Gims' },
  { answer: "Est-ce que tu m'aimes ?", category: 'rapfr', query: 'Est-ce que tu maimes Maître Gims' },
  { answer: 'Cosmo', category: 'rapfr', query: 'Cosmo Soprano' },
  { answer: 'Réseaux', category: 'rapfr', query: 'Réseaux Niska' },
  { answer: 'Copines', category: 'rapfr', query: 'Copines Aya Nakamura' },
  { answer: 'Pookie', category: 'rapfr', query: 'Pookie Aya Nakamura' },
  { answer: 'La Kiffance', category: 'rapfr', query: 'La Kiffance Naps' },
  { answer: 'Dommage', category: 'rapfr', query: 'Dommage Bigflo et Oli' },
  { answer: 'Petit frère', category: 'rapfr', query: 'Petit frère IAM' },
  { answer: 'Ma benz', category: 'rapfr', query: 'Ma benz NTM' },
  { answer: 'Gomorra', category: 'rapfr', query: 'Gomorra SCH' },
];

const RAW_ENTRIES: BlindtestEntry[] = [
  ...ANIME, ...ANIME2,
  ...CARTOON, ...CARTOON2,
  ...MUSIC, ...MUSIC2,
  ...FILM, ...FILM2,
  ...JEUXVIDEO, ...JEUXVIDEO2,
  ...DISNEY, ...DISNEY2,
  ...KPOP, ...RETRO, ...SERIES, ...RAPFR,
];

// Runtime dedup: duplicate answers within a category break buildOptions
// (they can generate two identical options or a wrong answerIndex).
// Keep the first occurrence of each (category, answer) pair.
const _seenEntries = new Set<string>();
export const BLINDTEST_ENTRIES: BlindtestEntry[] = RAW_ENTRIES.filter((e) => {
  const key = e.category + '|' + e.answer.toLowerCase();
  if (_seenEntries.has(key)) return false;
  _seenEntries.add(key);
  return true;
});

export const BLINDTEST_ROUNDS = 10;
export const BLINDTEST_LISTEN_MS = 20000;
export const BLINDTEST_REVEAL_MS = 6500;

/** Round-length options (ms) selectable by the host. */
export const BLINDTEST_LISTEN_OPTIONS = [10000, 20000, 30000] as const;
/** Round-count options selectable by the host. */
export const BLINDTEST_ROUND_OPTIONS = [5, 10, 15] as const;

/**
 * Points for a correct answer, rewarding speed (≈100 slow → 1100 instant).
 * `listenMs` lets the score scale to the configured round length.
 */
export function scoreFor(correct: boolean, elapsedMs: number, listenMs: number = BLINDTEST_LISTEN_MS): number {
  if (!correct) return 0;
  const frac = Math.max(0, Math.min(1, elapsedMs / listenMs));
  return Math.round(1000 * (1 - frac)) + 100;
}
