/**
 * "Blindtest Musical" — curated answers + iTunes search queries.
 *
 * Audio is fetched at runtime from the iTunes Search API (30s previews), so
 * there are no files to host. Each entry pairs a clean ANSWER (what players
 * guess) with a search QUERY. Dead/empty queries are auto-skipped in game,
 * so a few misses never block a party.
 */

export type BlindtestCategory = 'anime' | 'cartoon' | 'music' | 'film' | 'jeuxvideo' | 'disney';

export const CATEGORY_META: Record<
  BlindtestCategory,
  { label: string; emoji: string; color: string }
> = {
  anime: { label: 'Anime', emoji: '🎌', color: '#f43f5e' },
  cartoon: { label: 'Dessin animé', emoji: '📺', color: '#22d3ee' },
  music: { label: 'Musique', emoji: '🎵', color: '#a855f7' },
  film: { label: 'Film', emoji: '🎬', color: '#fbbf24' },
  jeuxvideo: { label: 'Jeux Vidéo', emoji: '🎮', color: '#34d399' },
  disney: { label: 'Disney', emoji: '🏰', color: '#38bdf8' },
};

export interface BlindtestEntry {
  answer: string;
  category: BlindtestCategory;
  query: string;
  hint?: string;
}

const ANIME: BlindtestEntry[] = [
  { answer: 'Naruto', category: 'anime', query: 'Blue Bird Ikimonogakari' },
  { answer: "L'Attaque des Titans", category: 'anime', query: 'Guren no Yumiya Linked Horizon' },
  { answer: 'Demon Slayer', category: 'anime', query: 'Gurenge LiSA' },
  { answer: 'One Piece', category: 'anime', query: 'We Are Hiroshi Kitadani' },
  { answer: 'Jujutsu Kaisen', category: 'anime', query: 'Kaikai Kitan Eve' },
  { answer: 'My Hero Academia', category: 'anime', query: 'Peace Sign Kenshi Yonezu' },
  { answer: 'Dragon Ball Z', category: 'anime', query: 'Cha-La Head-Cha-La Hironobu Kageyama' },
  { answer: 'Death Note', category: 'anime', query: 'the WORLD Nightmare' },
  { answer: 'Tokyo Ghoul', category: 'anime', query: 'Unravel TK ling tosite sigure' },
  { answer: 'Sword Art Online', category: 'anime', query: 'Crossing Field LiSA' },
  { answer: 'Fullmetal Alchemist', category: 'anime', query: 'Again Yui' },
  { answer: 'Hunter x Hunter', category: 'anime', query: 'Departure Masatoshi Ono' },
  { answer: 'Chainsaw Man', category: 'anime', query: 'Kick Back Kenshi Yonezu' },
  { answer: 'Spy x Family', category: 'anime', query: 'Mixed Nuts Official Hige Dandism' },
  { answer: 'Bleach', category: 'anime', query: 'Asterisk Orange Range' },
  { answer: 'Evangelion', category: 'anime', query: "A Cruel Angel's Thesis Yoko Takahashi" },
  { answer: 'Fairy Tail', category: 'anime', query: 'Snow Fairy Funkist' },
  { answer: 'Black Clover', category: 'anime', query: 'Black Catcher Vickeblanka' },
  { answer: 'Haikyuu', category: 'anime', query: 'Imagination Spyair' },
  { answer: 'Tokyo Revengers', category: 'anime', query: 'Cry Baby Official Hige Dandism' },
  { answer: "JoJo's Bizarre Adventure", category: 'anime', query: 'Bloody Stream Coda' },
  { answer: 'Cowboy Bebop', category: 'anime', query: 'Tank Seatbelts Yoko Kanno' },
  { answer: 'Mob Psycho 100', category: 'anime', query: '99 Mob Choir' },
  { answer: 'One Punch Man', category: 'anime', query: 'The Hero JAM Project' },
  { answer: 'Steins;Gate', category: 'anime', query: 'Hacking to the Gate Kanako Ito' },
  { answer: 'Re:Zero', category: 'anime', query: 'Redo Konomi Suzuki' },
  { answer: 'Vinland Saga', category: 'anime', query: 'Mukanjyo Survive Said The Prophet' },
  { answer: 'Blue Lock', category: 'anime', query: 'Chaos Lulu Unfair' },
  { answer: 'Code Geass', category: 'anime', query: 'Colors Flow' },
  { answer: 'Gurren Lagann', category: 'anime', query: 'Sorairo Days Shoko Nakagawa' },
  { answer: 'Fate/Zero', category: 'anime', query: 'oath sign LiSA' },
  { answer: 'Your Name', category: 'anime', query: 'Zenzenzense RADWIMPS' },
  { answer: 'Angel Beats', category: 'anime', query: 'My Soul Your Beats Lia' },
  { answer: 'Seven Deadly Sins', category: 'anime', query: 'Netsujou no Spectrum Ikimonogakari' },
  { answer: 'Assassination Classroom', category: 'anime', query: 'Seishun Satsubatsuron 3-nen E-gumi Utatan' },
  { answer: 'Erased', category: 'anime', query: 'Re:Re: Asian Kung-Fu Generation' },
  { answer: 'Your Lie in April', category: 'anime', query: 'Hikaru Nara Goose House' },
  { answer: 'Madoka Magica', category: 'anime', query: 'Connect ClariS' },
  { answer: 'Konosuba', category: 'anime', query: 'fantastic dreamer Machico' },
  { answer: 'The Promised Neverland', category: 'anime', query: 'Touch off UVERworld' },
  { answer: 'Dr. Stone', category: 'anime', query: 'Good Morning World Burnout Syndromes' },
  { answer: 'Fire Force', category: 'anime', query: 'Inferno Mrs. Green Apple' },
  { answer: 'Kaguya-sama', category: 'anime', query: 'Love Dramatic Masayuki Suzuki' },
  { answer: 'Bocchi the Rock', category: 'anime', query: 'Seishun Complex Kessoku Band' },
  { answer: 'Oshi no Ko', category: 'anime', query: 'Idol YOASOBI' },
  { answer: 'Frieren', category: 'anime', query: 'Yuusha YOASOBI' },
  { answer: 'Sailor Moon', category: 'anime', query: 'Moonlight Densetsu Dali' },
  { answer: 'Inuyasha', category: 'anime', query: 'Change the World V6' },
  { answer: 'Yu Yu Hakusho', category: 'anime', query: 'Hohoemi no Bakudan Matsuko Mawatari' },
  { answer: 'Detective Conan', category: 'anime', query: 'Mune ga Doki Doki The High-Lows' },
  { answer: 'Soul Eater', category: 'anime', query: 'Resonance T.M.Revolution' },
  { answer: 'Elfen Lied', category: 'anime', query: 'Lilium Elfen Lied' },
  { answer: 'Beastars', category: 'anime', query: 'Wild Side Ali' },
  { answer: 'Devilman Crybaby', category: 'anime', query: 'Man Human Kensuke Ushio' },
];

const CARTOON: BlindtestEntry[] = [
  // Vrais dessins animés (pas d'anime) — génériques VF quand ils existent
  { answer: 'Bob l’éponge', category: 'cartoon', query: 'Bob l’éponge générique français' },
  { answer: 'Inspecteur Gadget', category: 'cartoon', query: 'Inspecteur Gadget générique français' },
  { answer: 'Les Tortues Ninja', category: 'cartoon', query: 'Tortues Ninja générique Bernard Minet' },
  { answer: 'Code Lyoko', category: 'cartoon', query: 'Un Monde Sans Danger Code Lyoko' },
  { answer: 'Wakfu', category: 'cartoon', query: 'Wakfu générique' },
  { answer: 'Totally Spies', category: 'cartoon', query: 'Totally Spies générique français' },
  { answer: 'Oggy et les cafards', category: 'cartoon', query: 'Oggy et les cafards générique' },
  { answer: 'Titeuf', category: 'cartoon', query: 'Titeuf générique' },
  { answer: 'Foot 2 Rue', category: 'cartoon', query: 'Foot 2 Rue générique' },
  { answer: 'Il était une fois la vie', category: 'cartoon', query: 'Il était une fois la vie générique' },
  { answer: "Les Mystérieuses Cités d'Or", category: 'cartoon', query: "Les Mystérieuses Cités d'Or générique" },
  { answer: 'Ulysse 31', category: 'cartoon', query: 'Ulysse 31 générique' },
  { answer: 'Les Mondes Engloutis', category: 'cartoon', query: 'Les Mondes Engloutis générique' },
  { answer: 'Les Schtroumpfs', category: 'cartoon', query: 'Les Schtroumpfs générique français' },
  { answer: 'Lucky Luke', category: 'cartoon', query: 'Lucky Luke générique' },
  { answer: 'Astérix', category: 'cartoon', query: 'Astérix générique' },
  { answer: 'Babar', category: 'cartoon', query: 'Babar générique français' },
  { answer: 'T’choupi', category: 'cartoon', query: 'Tchoupi générique' },
  { answer: 'Boule et Bill', category: 'cartoon', query: 'Boule et Bill générique' },
  { answer: 'Cédric', category: 'cartoon', query: 'Cédric générique' },
  { answer: 'Le Petit Nicolas', category: 'cartoon', query: 'Le Petit Nicolas générique' },
  { answer: 'Denver le dernier dinosaure', category: 'cartoon', query: 'Denver le dernier dinosaure générique' },
  { answer: 'Les Entrechats', category: 'cartoon', query: 'Les Entrechats générique' },
  { answer: 'Pollux', category: 'cartoon', query: 'Le Manège enchanté Pollux générique' },
  { answer: 'Les Minipouss', category: 'cartoon', query: 'Les Minipouss générique' },
  { answer: 'Dora l’exploratrice', category: 'cartoon', query: 'Dora l’exploratrice générique' },
  { answer: 'Pat’ Patrouille', category: 'cartoon', query: 'Pat Patrouille générique français' },
  { answer: 'Winx Club', category: 'cartoon', query: 'Winx Club générique français' },
  { answer: 'Miraculous', category: 'cartoon', query: 'Miraculous Ladybug générique français' },
  { answer: 'Sam le pompier', category: 'cartoon', query: 'Sam le pompier générique' },
  { answer: 'Petit Ours Brun', category: 'cartoon', query: 'Petit Ours Brun générique' },
  { answer: 'Trotro', category: 'cartoon', query: 'Trotro générique' },
  { answer: 'Les P’tits Diables', category: 'cartoon', query: "Les P'tits Diables générique" },
  { answer: 'MASK', category: 'cartoon', query: 'MASK générique français' },
  // Cartoons US (thèmes connus)
  { answer: 'Les Simpson', category: 'cartoon', query: 'The Simpsons Theme Danny Elfman' },
  { answer: 'Tom et Jerry', category: 'cartoon', query: 'Tom and Jerry Scott Bradley' },
  { answer: 'Scooby-Doo', category: 'cartoon', query: 'Scooby Doo Where Are You' },
  { answer: 'Les Razmoket', category: 'cartoon', query: 'Rugrats Theme' },
  { answer: 'Les Supers Nanas', category: 'cartoon', query: 'Powerpuff Girls Theme' },
  { answer: 'Ben 10', category: 'cartoon', query: 'Ben 10 Theme' },
  { answer: 'Gravity Falls', category: 'cartoon', query: 'Gravity Falls Theme' },
  { answer: 'Rick et Morty', category: 'cartoon', query: 'Rick and Morty Theme' },
  { answer: 'Phineas et Ferb', category: 'cartoon', query: 'Phineas and Ferb Theme' },
  { answer: 'Kim Possible', category: 'cartoon', query: 'Call Me Beep Me Kim Possible' },
  { answer: 'Teen Titans', category: 'cartoon', query: 'Teen Titans Theme Puffy AmiYumi' },
  { answer: 'La Bande à Picsou', category: 'cartoon', query: 'DuckTales Theme' },
  { answer: 'Les Pierrafeu', category: 'cartoon', query: 'Meet the Flintstones' },
  { answer: 'Looney Tunes', category: 'cartoon', query: 'Looney Tunes Merrily We Roll Along' },
  { answer: 'South Park', category: 'cartoon', query: 'South Park Theme Primus' },
  { answer: 'Les Griffin', category: 'cartoon', query: 'Family Guy Theme' },
  { answer: 'Mr Bean', category: 'cartoon', query: 'Mr Bean Animated Series Theme' },
];

const MUSIC: BlindtestEntry[] = [
  { answer: 'Blinding Lights', category: 'music', query: 'Blinding Lights The Weeknd' },
  { answer: 'Bad Guy', category: 'music', query: 'bad guy Billie Eilish' },
  { answer: 'Shape of You', category: 'music', query: 'Shape of You Ed Sheeran' },
  { answer: 'Uptown Funk', category: 'music', query: 'Uptown Funk Bruno Mars' },
  { answer: 'Rolling in the Deep', category: 'music', query: 'Rolling in the Deep Adele' },
  { answer: 'Believer', category: 'music', query: 'Believer Imagine Dragons' },
  { answer: 'Levitating', category: 'music', query: 'Levitating Dua Lipa' },
  { answer: 'Smells Like Teen Spirit', category: 'music', query: 'Smells Like Teen Spirit Nirvana' },
  { answer: 'Billie Jean', category: 'music', query: 'Billie Jean Michael Jackson' },
  { answer: 'Seven Nation Army', category: 'music', query: 'Seven Nation Army The White Stripes' },
  { answer: 'Bohemian Rhapsody', category: 'music', query: 'Bohemian Rhapsody Queen' },
  { answer: "Sweet Child O' Mine", category: 'music', query: 'Sweet Child O Mine Guns N Roses' },
  { answer: 'Wonderwall', category: 'music', query: 'Wonderwall Oasis' },
  { answer: 'Take On Me', category: 'music', query: 'Take On Me a-ha' },
  { answer: 'Viva la Vida', category: 'music', query: 'Viva la Vida Coldplay' },
  { answer: 'Get Lucky', category: 'music', query: 'Get Lucky Daft Punk' },
  { answer: 'Lose Yourself', category: 'music', query: 'Lose Yourself Eminem' },
  { answer: 'Shake It Off', category: 'music', query: 'Shake It Off Taylor Swift' },
  { answer: 'Despacito', category: 'music', query: 'Despacito Luis Fonsi' },
  { answer: 'Gangnam Style', category: 'music', query: 'Gangnam Style PSY' },
  { answer: 'Dynamite', category: 'music', query: 'Dynamite BTS' },
  { answer: 'As It Was', category: 'music', query: 'As It Was Harry Styles' },
  { answer: 'Flowers', category: 'music', query: 'Flowers Miley Cyrus' },
  { answer: 'Happy', category: 'music', query: 'Happy Pharrell Williams' },
  { answer: 'Someone Like You', category: 'music', query: 'Someone Like You Adele' },
  { answer: 'Counting Stars', category: 'music', query: 'Counting Stars OneRepublic' },
  { answer: 'Radioactive', category: 'music', query: 'Radioactive Imagine Dragons' },
  { answer: 'Roar', category: 'music', query: 'Roar Katy Perry' },
  { answer: 'Bad Romance', category: 'music', query: 'Bad Romance Lady Gaga' },
  { answer: 'Toxic', category: 'music', query: 'Toxic Britney Spears' },
  { answer: 'Hey Ya!', category: 'music', query: 'Hey Ya OutKast' },
  { answer: 'In the End', category: 'music', query: 'In the End Linkin Park' },
  { answer: 'Boulevard of Broken Dreams', category: 'music', query: 'Boulevard of Broken Dreams Green Day' },
  { answer: 'Mr. Brightside', category: 'music', query: 'Mr Brightside The Killers' },
  { answer: 'Stairway to Heaven', category: 'music', query: 'Stairway to Heaven Led Zeppelin' },
  { answer: 'Hotel California', category: 'music', query: 'Hotel California Eagles' },
  { answer: 'Imagine', category: 'music', query: 'Imagine John Lennon' },
  { answer: 'Africa', category: 'music', query: 'Africa Toto' },
  { answer: "Don't Stop Believin'", category: 'music', query: 'Dont Stop Believin Journey' },
  { answer: 'Thriller', category: 'music', query: 'Thriller Michael Jackson' },
  { answer: 'Sweet Dreams', category: 'music', query: 'Sweet Dreams Eurythmics' },
  { answer: 'Wannabe', category: 'music', query: 'Wannabe Spice Girls' },
  { answer: "Livin' on a Prayer", category: 'music', query: 'Livin on a Prayer Bon Jovi' },
  { answer: 'Old Town Road', category: 'music', query: 'Old Town Road Lil Nas X' },
  { answer: 'Sunflower', category: 'music', query: 'Sunflower Post Malone Swae Lee' },
  { answer: 'Stay', category: 'music', query: 'Stay The Kid LAROI Justin Bieber' },
  { answer: 'Alors on danse', category: 'music', query: 'Alors on danse Stromae' },
  { answer: 'Dernière danse', category: 'music', query: 'Dernière danse Indila' },
  { answer: 'Djadja', category: 'music', query: 'Djadja Aya Nakamura' },
  { answer: 'Balance ton quoi', category: 'music', query: 'Balance ton quoi Angèle' },
  { answer: 'La Vie en rose', category: 'music', query: 'La Vie en rose Edith Piaf' },
  { answer: 'Christine', category: 'music', query: 'Christine Christine and the Queens' },
];

const FILM: BlindtestEntry[] = [
  { answer: 'Star Wars', category: 'film', query: 'Star Wars Main Title John Williams' },
  { answer: 'Pirates des Caraïbes', category: 'film', query: "He's a Pirate Klaus Badelt" },
  { answer: 'Harry Potter', category: 'film', query: "Hedwig's Theme John Williams" },
  { answer: 'Jurassic Park', category: 'film', query: 'Jurassic Park Theme John Williams' },
  { answer: 'Interstellar', category: 'film', query: 'Cornfield Chase Hans Zimmer' },
  { answer: 'Titanic', category: 'film', query: 'My Heart Will Go On Celine Dion' },
  { answer: 'Le Parrain', category: 'film', query: 'The Godfather Waltz Nino Rota' },
  { answer: 'Mission Impossible', category: 'film', query: 'Mission Impossible Theme' },
  { answer: 'James Bond', category: 'film', query: 'James Bond Theme' },
  { answer: 'Indiana Jones', category: 'film', query: 'Raiders March John Williams' },
  { answer: 'Retour vers le futur', category: 'film', query: 'Back to the Future Theme Alan Silvestri' },
  { answer: 'Rocky', category: 'film', query: 'Gonna Fly Now Rocky' },
  { answer: 'Le Seigneur des Anneaux', category: 'film', query: 'Concerning Hobbits Howard Shore' },
  { answer: 'Gladiator', category: 'film', query: 'Now We Are Free Hans Zimmer' },
  { answer: 'Le Bon, la Brute et le Truand', category: 'film', query: 'The Good the Bad and the Ugly Ennio Morricone' },
  { answer: 'Inception', category: 'film', query: 'Time Hans Zimmer Inception' },
  { answer: 'The Dark Knight', category: 'film', query: 'Why So Serious Hans Zimmer' },
  { answer: 'Avengers', category: 'film', query: 'The Avengers Theme Alan Silvestri' },
  { answer: 'Pulp Fiction', category: 'film', query: 'Misirlou Dick Dale' },
  { answer: 'Forrest Gump', category: 'film', query: 'Forrest Gump Suite Alan Silvestri' },
  { answer: 'E.T.', category: 'film', query: 'E.T. Flying Theme John Williams' },
  { answer: 'Les Dents de la mer', category: 'film', query: 'Jaws Theme John Williams' },
  { answer: 'Halloween', category: 'film', query: 'Halloween Theme John Carpenter' },
  { answer: 'Requiem for a Dream', category: 'film', query: 'Lux Aeterna Clint Mansell' },
  { answer: 'La Liste de Schindler', category: 'film', query: "Schindler's List Theme John Williams" },
  { answer: 'Tron Legacy', category: 'film', query: 'Derezzed Daft Punk Tron' },
  { answer: 'Blade Runner', category: 'film', query: 'Blade Runner Blues Vangelis' },
  { answer: 'Amélie Poulain', category: 'film', query: "Comptine d'un autre été Yann Tiersen" },
  { answer: 'Intouchables', category: 'film', query: 'Una Mattina Ludovico Einaudi' },
  { answer: 'La La Land', category: 'film', query: 'City of Stars La La Land' },
  { answer: 'Whiplash', category: 'film', query: 'Caravan Whiplash' },
  { answer: 'The Greatest Showman', category: 'film', query: 'This Is Me Greatest Showman' },
  { answer: 'Joker', category: 'film', query: 'Joker Hildur Gudnadottir' },
  { answer: 'Top Gun', category: 'film', query: 'Danger Zone Kenny Loggins' },
  { answer: 'Ghostbusters', category: 'film', query: 'Ghostbusters Ray Parker Jr' },
  { answer: 'Men in Black', category: 'film', query: 'Men in Black Will Smith' },
  { answer: 'Grease', category: 'film', query: "You're the One That I Want Grease" },
  { answer: 'Dirty Dancing', category: 'film', query: 'Time of My Life Dirty Dancing' },
  { answer: 'Footloose', category: 'film', query: 'Footloose Kenny Loggins' },
  { answer: 'Saturday Night Fever', category: 'film', query: "Stayin' Alive Bee Gees" },
  { answer: 'The Matrix', category: 'film', query: 'Clubbed to Death Matrix' },
  { answer: 'Kill Bill', category: 'film', query: 'Bang Bang Nancy Sinatra Kill Bill' },
  { answer: 'Cinema Paradiso', category: 'film', query: 'Cinema Paradiso Ennio Morricone' },
  { answer: 'Mad Max Fury Road', category: 'film', query: 'Brothers in Arms Junkie XL Mad Max' },
  { answer: 'Dunkerque', category: 'film', query: 'Supermarine Hans Zimmer Dunkirk' },
  { answer: 'Gladiator', category: 'film', query: 'Now We Are Free Gladiator Lisa Gerrard' },
  { answer: 'Spider-Man', category: 'film', query: 'Spider-Man Theme Danny Elfman 2002' },
  { answer: 'Superman', category: 'film', query: 'Superman March John Williams' },
  { answer: '2001 l’Odyssée de l’espace', category: 'film', query: 'Also Sprach Zarathustra Strauss 2001' },
  { answer: 'Le Roi Arthur', category: 'film', query: 'King Arthur Hans Zimmer' },
  { answer: 'Once Upon a Time in the West', category: 'film', query: "Once Upon a Time in the West Ennio Morricone" },
];

const JEUXVIDEO: BlindtestEntry[] = [
  { answer: 'Super Mario Bros', category: 'jeuxvideo', query: 'Super Mario Bros Theme Koji Kondo' },
  { answer: 'The Legend of Zelda', category: 'jeuxvideo', query: 'The Legend of Zelda Main Theme Koji Kondo' },
  { answer: 'Tetris', category: 'jeuxvideo', query: 'Tetris Theme Korobeiniki' },
  { answer: 'Minecraft', category: 'jeuxvideo', query: 'Minecraft Sweden C418' },
  { answer: 'Sonic the Hedgehog', category: 'jeuxvideo', query: 'Sonic Green Hill Zone' },
  { answer: 'Undertale', category: 'jeuxvideo', query: 'Megalovania Toby Fox' },
  { answer: 'Final Fantasy', category: 'jeuxvideo', query: 'One Winged Angel Nobuo Uematsu' },
  { answer: 'Skyrim', category: 'jeuxvideo', query: 'Dragonborn Skyrim Jeremy Soule' },
  { answer: 'The Last of Us', category: 'jeuxvideo', query: 'The Last of Us Theme Gustavo Santaolalla' },
  { answer: 'Halo', category: 'jeuxvideo', query: "Halo Theme Martin O'Donnell" },
  { answer: 'Doom', category: 'jeuxvideo', query: "At Doom's Gate Mick Gordon" },
  { answer: 'Animal Crossing', category: 'jeuxvideo', query: 'Animal Crossing Main Theme' },
  { answer: 'Mario Kart', category: 'jeuxvideo', query: 'Mario Kart 8 Main Theme' },
  { answer: 'Kingdom Hearts', category: 'jeuxvideo', query: 'Simple and Clean Utada Hikaru' },
  { answer: 'Chrono Trigger', category: 'jeuxvideo', query: 'Chrono Trigger Main Theme Yasunori Mitsuda' },
  { answer: 'Castlevania', category: 'jeuxvideo', query: 'Vampire Killer Castlevania' },
  { answer: 'Mega Man 2', category: 'jeuxvideo', query: 'Mega Man 2 Dr Wily Stage' },
  { answer: 'Street Fighter', category: 'jeuxvideo', query: "Guile's Theme Street Fighter" },
  { answer: 'Mortal Kombat', category: 'jeuxvideo', query: 'Techno Syndrome Mortal Kombat' },
  { answer: 'Donkey Kong Country', category: 'jeuxvideo', query: 'Aquatic Ambience David Wise' },
  { answer: 'Metroid', category: 'jeuxvideo', query: 'Metroid Brinstar Theme' },
  { answer: 'Kirby', category: 'jeuxvideo', query: 'Green Greens Kirby' },
  { answer: 'Splatoon', category: 'jeuxvideo', query: 'Splattack Splatoon' },
  { answer: 'Celeste', category: 'jeuxvideo', query: 'Resurrections Lena Raine Celeste' },
  { answer: 'Hollow Knight', category: 'jeuxvideo', query: 'Hornet Christopher Larkin Hollow Knight' },
  { answer: 'Cuphead', category: 'jeuxvideo', query: 'Die House Kristofer Maddigan Cuphead' },
  { answer: 'Persona 5', category: 'jeuxvideo', query: 'Last Surprise Persona 5' },
  { answer: 'NieR Automata', category: 'jeuxvideo', query: 'Weight of the World NieR Automata' },
  { answer: 'The Witcher 3', category: 'jeuxvideo', query: 'Toss a Coin to Your Witcher' },
  { answer: 'Red Dead Redemption', category: 'jeuxvideo', query: "That's the Way It Is Daniel Lanois" },
  { answer: 'Assassin’s Creed', category: 'jeuxvideo', query: "Ezio's Family Jesper Kyd" },
  { answer: 'Elden Ring', category: 'jeuxvideo', query: 'Elden Ring Main Theme' },
  { answer: 'Dark Souls', category: 'jeuxvideo', query: 'Gwyn Lord of Cinder Dark Souls' },
  { answer: 'God of War', category: 'jeuxvideo', query: 'Memories of Mother Bear McCreary God of War' },
  { answer: 'League of Legends', category: 'jeuxvideo', query: 'POP/STARS K/DA League of Legends' },
  { answer: 'Genshin Impact', category: 'jeuxvideo', query: 'Genshin Impact Main Theme' },
  { answer: 'Portal', category: 'jeuxvideo', query: 'Still Alive Jonathan Coulton Portal' },
  { answer: 'Civilization IV', category: 'jeuxvideo', query: 'Baba Yetu Christopher Tin' },
  { answer: 'Gran Turismo', category: 'jeuxvideo', query: 'Moon Over the Castle Gran Turismo' },
  { answer: 'Pac-Man', category: 'jeuxvideo', query: 'Pac-Man Theme' },
  { answer: 'Crash Bandicoot', category: 'jeuxvideo', query: 'Crash Bandicoot Theme' },
  { answer: 'Banjo-Kazooie', category: 'jeuxvideo', query: 'Banjo-Kazooie Main Theme Grant Kirkhope' },
  { answer: 'Stardew Valley', category: 'jeuxvideo', query: 'Stardew Valley Overture' },
  { answer: 'Cyberpunk 2077', category: 'jeuxvideo', query: 'I Really Want to Stay at Your House Cyberpunk' },
  { answer: 'Fallout', category: 'jeuxvideo', query: 'Fallout Main Theme Mark Morgan' },
  { answer: 'Bioshock', category: 'jeuxvideo', query: 'Bioshock The Ocean on His Shoulders' },
  { answer: 'Overwatch', category: 'jeuxvideo', query: 'Overwatch Main Theme' },
  { answer: 'Sea of Thieves', category: 'jeuxvideo', query: 'Sea of Thieves Maiden Voyage' },
  { answer: 'Mario 64', category: 'jeuxvideo', query: 'Super Mario 64 Bob-omb Battlefield' },
  { answer: 'Pokémon (jeu)', category: 'jeuxvideo', query: 'Pokemon Red Blue Battle Theme' },
  { answer: 'Tomb Raider', category: 'jeuxvideo', query: 'Tomb Raider Main Theme Nathan McCree' },
];

const DISNEY: BlindtestEntry[] = [
  { answer: 'La Reine des Neiges', category: 'disney', query: 'Let It Go Idina Menzel Frozen' },
  { answer: 'Le Roi Lion', category: 'disney', query: 'Circle of Life Lion King' },
  { answer: 'Aladdin', category: 'disney', query: 'A Whole New World Aladdin' },
  { answer: 'La Petite Sirène', category: 'disney', query: 'Part of Your World Little Mermaid' },
  { answer: 'La Belle et la Bête', category: 'disney', query: 'Beauty and the Beast Celine Dion' },
  { answer: 'Vaiana', category: 'disney', query: "How Far I'll Go Moana" },
  { answer: 'Toy Story', category: 'disney', query: "You've Got a Friend in Me Randy Newman" },
  { answer: 'Coco', category: 'disney', query: 'Remember Me Coco' },
  { answer: 'Encanto', category: 'disney', query: "We Don't Talk About Bruno Encanto" },
  { answer: 'Mulan', category: 'disney', query: 'Reflection Mulan' },
  { answer: 'Hercule', category: 'disney', query: 'Go the Distance Hercules' },
  { answer: 'Pocahontas', category: 'disney', query: 'Colors of the Wind Pocahontas' },
  { answer: 'La Reine des Neiges 2', category: 'disney', query: 'Into the Unknown Idina Menzel' },
  { answer: 'Raiponce', category: 'disney', query: 'I See the Light Tangled' },
  { answer: 'La Princesse et la Grenouille', category: 'disney', query: 'Almost There Princess and the Frog' },
  { answer: 'Mary Poppins', category: 'disney', query: 'Supercalifragilisticexpialidocious Mary Poppins' },
  { answer: 'Le Livre de la Jungle', category: 'disney', query: 'I Wanna Be Like You Jungle Book' },
  { answer: 'Cendrillon', category: 'disney', query: 'Bibbidi-Bobbidi-Boo Cinderella' },
  { answer: 'Blanche-Neige', category: 'disney', query: 'Heigh-Ho Snow White' },
  { answer: 'Pinocchio', category: 'disney', query: 'When You Wish Upon a Star Pinocchio' },
  { answer: 'Peter Pan', category: 'disney', query: 'You Can Fly Peter Pan' },
  { answer: 'Dumbo', category: 'disney', query: 'Baby Mine Dumbo' },
  { answer: 'La Belle au bois dormant', category: 'disney', query: 'Once Upon a Dream Sleeping Beauty' },
  { answer: 'Les Aristochats', category: 'disney', query: 'Everybody Wants to Be a Cat Aristocats' },
  { answer: 'Robin des Bois', category: 'disney', query: 'Oo-De-Lally Robin Hood Disney' },
  { answer: 'Les 101 Dalmatiens', category: 'disney', query: 'Cruella De Vil 101 Dalmatians' },
  { answer: 'Le Bossu de Notre-Dame', category: 'disney', query: 'Out There Hunchback of Notre Dame' },
  { answer: 'Tarzan', category: 'disney', query: "You'll Be in My Heart Phil Collins" },
  { answer: 'Lilo et Stitch', category: 'disney', query: 'Hawaiian Roller Coaster Ride Lilo Stitch' },
  { answer: 'Frère des ours', category: 'disney', query: 'On My Way Phil Collins Brother Bear' },
  { answer: 'Le Monde de Nemo', category: 'disney', query: 'Finding Nemo Thomas Newman' },
  { answer: 'Là-haut', category: 'disney', query: 'Married Life Up Michael Giacchino' },
  { answer: 'Les Indestructibles', category: 'disney', query: 'The Incredibles Michael Giacchino' },
  { answer: 'Ratatouille', category: 'disney', query: 'Le Festin Camille Ratatouille' },
  { answer: 'WALL-E', category: 'disney', query: 'Down to Earth Peter Gabriel WALL-E' },
  { answer: 'Monstres et Cie', category: 'disney', query: 'Monsters Inc Randy Newman' },
  { answer: 'Cars', category: 'disney', query: 'Life is a Highway Rascal Flatts Cars' },
  { answer: 'Rebelle', category: 'disney', query: 'Touch the Sky Brave Pixar' },
  { answer: 'Vice-Versa', category: 'disney', query: 'Bundle of Joy Inside Out Michael Giacchino' },
  { answer: 'Soul', category: 'disney', query: 'Soul Trent Reznor Atticus Ross' },
  { answer: 'Zootopie', category: 'disney', query: 'Try Everything Shakira Zootopia' },
  { answer: 'Les Mondes de Ralph', category: 'disney', query: 'Wreck-It Ralph Theme' },
  { answer: 'Kuzco', category: 'disney', query: "Perfect World Sting Emperor's New Groove" },
  { answer: 'Mulan 2', category: 'disney', query: 'Lesson Number One Mulan 2' },
  { answer: 'Hannah Montana', category: 'disney', query: 'The Best of Both Worlds Hannah Montana' },
  { answer: 'High School Musical', category: 'disney', query: "We're All in This Together High School Musical" },
  { answer: 'Camp Rock', category: 'disney', query: 'This Is Me Demi Lovato Camp Rock' },
  { answer: 'Descendants', category: 'disney', query: 'Rotten to the Core Descendants' },
  { answer: 'Luca', category: 'disney', query: 'Luca Dan Romer Pixar' },
  { answer: 'En avant', category: 'disney', query: 'Onward Mychael Danna Pixar' },
];

export const BLINDTEST_ENTRIES: BlindtestEntry[] = [
  ...ANIME, ...CARTOON, ...MUSIC, ...FILM, ...JEUXVIDEO, ...DISNEY,
];

export const BLINDTEST_ROUNDS = 10;
export const BLINDTEST_LISTEN_MS = 20000;
export const BLINDTEST_REVEAL_MS = 6500;

/** Points for a correct answer, rewarding speed (≈100 slow → 1100 instant). */
export function scoreFor(correct: boolean, elapsedMs: number): number {
  if (!correct) return 0;
  const frac = Math.max(0, Math.min(1, elapsedMs / BLINDTEST_LISTEN_MS));
  return Math.round(1000 * (1 - frac)) + 100;
}
