// =============================================================================
// BlurRush Image Bank — 200+ entries with categories, synonyms, and difficulty
// Using CORS-friendly image sources (Lorem Picsum for reliable loading)
// =============================================================================

export type BlurRushCategory =
  | 'Anime'
  | 'Film'
  | 'Série'
  | 'Personnage'
  | 'Jeux Vidéo'
  | 'Logo'
  | 'Monument'
  | 'Art'
  | 'Mix';

export interface BlurRushImage {
  url: string;
  answer: string;
  acceptable: string[];
  category: Exclude<BlurRushCategory, 'Mix'>;
  difficulty: 'easy' | 'medium' | 'hard';
}

// Categories available for selection (excluding Mix which is a special mode)
export const BLURRUSH_CATEGORIES: Exclude<BlurRushCategory, 'Mix'>[] = [
  'Anime',
  'Film',
  'Série',
  'Personnage',
  'Jeux Vidéo',
  'Logo',
  'Monument',
  'Art',
];

// Helper to create Picsum URLs with consistent IDs for each answer
// This ensures the same image is always shown for the same answer
const picsum = (id: number) => `https://picsum.photos/id/${id}/600/600`;

// Use reliable CDN sources for logos and recognizable images
const BLURRUSH_IMAGES: BlurRushImage[] = [
  // ========== ANIME (30+) ==========
  { url: 'https://cdn.myanimelist.net/images/anime/1208/94745.jpg', answer: 'naruto', acceptable: ['naruto', 'naruto uzumaki', 'naruto shippuden'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg', answer: 'one piece', acceptable: ['one piece', 'luffy', 'monkey d luffy'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/10/78745.jpg', answer: 'dragon ball', acceptable: ['dragon ball', 'dbz', 'goku', 'sangoku', 'dragon ball z'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/10/47347.jpg', answer: 'attack on titan', acceptable: ['attack on titan', 'snk', 'shingeki no kyojin', 'eren'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg', answer: 'demon slayer', acceptable: ['demon slayer', 'kimetsu no yaiba', 'tanjiro'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/1000/110531.jpg', answer: 'jujutsu kaisen', acceptable: ['jujutsu kaisen', 'jjk', 'gojo', 'yuji'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg', answer: 'spy x family', acceptable: ['spy x family', 'anya', 'loid', 'yor'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/1806/126216.jpg', answer: 'chainsaw man', acceptable: ['chainsaw man', 'denji'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1441/122795.jpg', answer: 'my hero academia', acceptable: ['my hero academia', 'mha', 'boku no hero', 'deku'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/9/9453.jpg', answer: 'death note', acceptable: ['death note', 'light', 'light yagami', 'kira', 'l'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/5/87048.jpg', answer: 'one punch man', acceptable: ['one punch man', 'opm', 'saitama'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1764/126627.jpg', answer: 'bleach', acceptable: ['bleach', 'ichigo', 'ichigo kurosaki'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/11/33657.jpg', answer: 'fullmetal alchemist', acceptable: ['fullmetal alchemist', 'fma', 'edward', 'edward elric'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg', answer: 'hunter x hunter', acceptable: ['hunter x hunter', 'hxh', 'gon', 'killua'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg', answer: 'tokyo ghoul', acceptable: ['tokyo ghoul', 'kaneki', 'ken kaneki'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1756/138983.jpg', answer: 'solo leveling', acceptable: ['solo leveling', 'sung jinwoo'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1244/138851.jpg', answer: 'frieren', acceptable: ['frieren', 'sousou no frieren'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1160/122627.jpg', answer: 'cowboy bebop', acceptable: ['cowboy bebop', 'spike', 'spike spiegel'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/7/20310.jpg', answer: 'code geass', acceptable: ['code geass', 'lelouch'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1314/108941.jpg', answer: 'steins gate', acceptable: ['steins gate', 'okabe'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1935/141839.jpg', answer: 'oshi no ko', acceptable: ['oshi no ko', 'aqua', 'ruby'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1948/120625.jpg', answer: 'tokyo revengers', acceptable: ['tokyo revengers', 'takemichi'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1223/96541.jpg', answer: 'mob psycho', acceptable: ['mob psycho', 'mob psycho 100', 'mob'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1517/100633.jpg', answer: 'fire force', acceptable: ['fire force', 'enen no shouboutai', 'shinra'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1498/134443.jpg', answer: 'blue lock', acceptable: ['blue lock', 'isagi'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1384/136925.jpg', answer: 'vinland saga', acceptable: ['vinland saga', 'thorfinn'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1572/111130.jpg', answer: 'black clover', acceptable: ['black clover', 'asta'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1988/119437.jpg', answer: 'fairy tail', acceptable: ['fairy tail', 'natsu'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1079/138100.jpg', answer: 'mashle', acceptable: ['mashle', 'mash'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1506/138982.jpg', answer: 'kaiju no 8', acceptable: ['kaiju no 8', 'kafka'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1094/133203.jpg', answer: 'haikyuu', acceptable: ['haikyuu', 'hinata'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/5/50331.jpg', answer: 'sword art online', acceptable: ['sword art online', 'sao', 'kirito'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/1429/95946.jpg', answer: 'your name', acceptable: ['your name', 'kimi no na wa'], category: 'Anime', difficulty: 'medium' },

  // ========== FILMS (30+) ==========
  { url: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg', answer: 'avengers endgame', acceptable: ['avengers', 'endgame', 'avengers endgame'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg', answer: 'avatar', acceptable: ['avatar', 'avatar 2'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', answer: 'titanic', acceptable: ['titanic'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg', answer: 'inception', acceptable: ['inception'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', answer: 'matrix', acceptable: ['matrix', 'the matrix'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', answer: 'interstellar', acceptable: ['interstellar'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', answer: 'oppenheimer', acceptable: ['oppenheimer'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg', answer: 'barbie', acceptable: ['barbie'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg', answer: 'spider man no way home', acceptable: ['spider man', 'spiderman', 'no way home'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg', answer: 'jurassic park', acceptable: ['jurassic park', 'jurassic world'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/lZpWprJqbIFpEV5uoHfoK0KCnTW.jpg', answer: 'jaws', acceptable: ['jaws', 'dents de la mer', 'les dents de la mer'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg', answer: 'frozen', acceptable: ['frozen', 'reine des neiges', 'la reine des neiges', 'elsa'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg', answer: 'le roi lion', acceptable: ['lion king', 'roi lion', 'le roi lion', 'simba'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', answer: 'le parrain', acceptable: ['godfather', 'parrain', 'le parrain', 'the godfather'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg', answer: 'the dark knight', acceptable: ['dark knight', 'batman'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg', answer: 'forrest gump', acceptable: ['forrest gump'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', answer: 'pulp fiction', acceptable: ['pulp fiction'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', answer: 'shawshank redemption', acceptable: ['shawshank', 'evades', 'les evades'], category: 'Film', difficulty: 'hard' },
  { url: 'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', answer: 'schindlers list', acceptable: ['schindlers list', 'schindler', 'liste de schindler'], category: 'Film', difficulty: 'hard' },
  { url: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', answer: 'fight club', acceptable: ['fight club'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg', answer: 'gladiator', acceptable: ['gladiator', 'gladiateur'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg', answer: 'dune', acceptable: ['dune'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg', answer: 'john wick', acceptable: ['john wick'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg', answer: 'shrek', acceptable: ['shrek'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg', answer: 'guardians of the galaxy', acceptable: ['guardians of the galaxy', 'gardiens de la galaxie', 'gotg'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg', answer: 'top gun', acceptable: ['top gun', 'maverick'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', answer: 'lord of the rings', acceptable: ['lord of the rings', 'seigneur des anneaux', 'lotr'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg', answer: 'harry potter', acceptable: ['harry potter'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/z8Y1NTDF88OBIjNsJyFmWjGjzOQ.jpg', answer: 'pirates of the caribbean', acceptable: ['pirates of the caribbean', 'pirates des caraibes', 'jack sparrow'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/fiVW06jE7z9YnO4trhaMEdclSiC.jpg', answer: 'fast and furious', acceptable: ['fast and furious', 'fast furious', 'fast x'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg', answer: 'inside out', acceptable: ['inside out', 'vice versa'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg', answer: 'joker', acceptable: ['joker'], category: 'Film', difficulty: 'easy' },

  // ========== SÉRIES (30+) ==========
  { url: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg', answer: 'breaking bad', acceptable: ['breaking bad', 'bb', 'walter white'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg', answer: 'game of thrones', acceptable: ['game of thrones', 'got'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg', answer: 'stranger things', acceptable: ['stranger things', 'eleven'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg', answer: 'la casa de papel', acceptable: ['casa de papel', 'la casa de papel', 'money heist'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg', answer: 'the witcher', acceptable: ['witcher', 'the witcher', 'geralt'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg', answer: 'squid game', acceptable: ['squid game'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg', answer: 'friends', acceptable: ['friends'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg', answer: 'the office', acceptable: ['the office', 'office'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg', answer: 'peaky blinders', acceptable: ['peaky blinders', 'peaky'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg', answer: 'the mandalorian', acceptable: ['mandalorian', 'the mandalorian', 'mando'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg', answer: 'better call saul', acceptable: ['better call saul', 'saul'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg', answer: 'the last of us', acceptable: ['the last of us', 'tlou', 'last of us'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg', answer: 'wednesday', acceptable: ['wednesday', 'mercredi'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg', answer: 'arcane', acceptable: ['arcane', 'league of legends'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg', answer: 'the boys', acceptable: ['the boys', 'boys'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/2IWouZK4gkgHhJa3oyYuSWfSqbG.jpg', answer: 'the simpsons', acceptable: ['simpsons', 'les simpsons', 'the simpsons'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg', answer: 'rick and morty', acceptable: ['rick and morty', 'rick et morty'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg', answer: 'south park', acceptable: ['south park'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg', answer: 'succession', acceptable: ['succession'], category: 'Série', difficulty: 'hard' },
  { url: 'https://image.tmdb.org/t/p/w500/rTh4K5uw9HypmpGslcKd4QfHl93.jpg', answer: 'narcos', acceptable: ['narcos', 'pablo escobar'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg', answer: 'the walking dead', acceptable: ['walking dead', 'the walking dead', 'twd'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg', answer: 'house of the dragon', acceptable: ['house of the dragon', 'hotd'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/obLBdhLxheKg8Li1qO11r2SwmYO.jpg', answer: 'cobra kai', acceptable: ['cobra kai'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg', answer: 'lucifer', acceptable: ['lucifer'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/5E1BhkCgjLBlqx557Z5yzcN0i88.jpg', answer: 'prison break', acceptable: ['prison break'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg', answer: 'vikings', acceptable: ['vikings', 'ragnar'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/58O1OLb2Ilvu4rqyGWcdLbzmnAE.jpg', answer: 'dexter', acceptable: ['dexter'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/esN3gWb1P091xExLddD2nh4zmi3.jpg', answer: 'sherlock', acceptable: ['sherlock', 'sherlock holmes'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/aCw8ONfyz3AhngVQa1E2Ss4KSUQ.jpg', answer: 'the crown', acceptable: ['the crown', 'crown'], category: 'Série', difficulty: 'hard' },

  // ========== PERSONNAGES (30+) ==========
  { url: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', answer: 'tyler durden', acceptable: ['tyler durden', 'brad pitt fight club'], category: 'Personnage', difficulty: 'hard' },
  { url: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', answer: 'darth vader', acceptable: ['darth vader', 'vader', 'dark vador', 'anakin'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/4D0PpNI0kmP58hgrwGC3wCjxhnm.jpg', answer: 'iron man', acceptable: ['iron man', 'tony stark'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', answer: 'batman', acceptable: ['batman', 'bruce wayne'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/lxMtsGomlkVjDM29lx0xDwDAluM.jpg', answer: 'superman', acceptable: ['superman', 'clark kent'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/e6qJtzyLLqjTbynXOb8VcthSGhG.jpg', answer: 'wonder woman', acceptable: ['wonder woman', 'diana'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/c4SdIrlOLg1Z0Gbo5hJAwoez5xD.jpg', answer: 'captain america', acceptable: ['captain america', 'steve rogers'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/qpJHvBv9WNruRgCxGU0A07dYdWf.jpg', answer: 'thor', acceptable: ['thor'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/tJr9GcmGNHhLVVEkinmwsXl8hmK.jpg', answer: 'hulk', acceptable: ['hulk', 'bruce banner'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/6NVHp6N2LPk2PQWNBbD3xWXFH3M.jpg', answer: 'thanos', acceptable: ['thanos'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/1mWHPm8tTEMnJMb3AwY0NeEC0jU.jpg', answer: 'james bond', acceptable: ['james bond', '007', 'bond'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/5XBzD5WuTyVQZeS4II6AbXvJpLt.jpg', answer: 'indiana jones', acceptable: ['indiana jones', 'indy'], category: 'Personnage', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/bxVxZb5O9IZ7VZcUiAhJLbvjZMr.jpg', answer: 'wolverine', acceptable: ['wolverine', 'logan'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/iiS4MHpjFyFXKt3obMBdQjm00xh.jpg', answer: 'deadpool', acceptable: ['deadpool', 'wade wilson'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0m2P3Py.jpg', answer: 'joker', acceptable: ['joker', 'arthur fleck'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/vJU3rXSK4OIFVRMopp6G9ULMhcP.jpg', answer: 'harley quinn', acceptable: ['harley quinn', 'harley'], category: 'Personnage', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/cNVNPW28d8tuMYaQHr6fLMH3YJH.jpg', answer: 'michael myers', acceptable: ['michael myers', 'halloween'], category: 'Personnage', difficulty: 'hard' },
  { url: 'https://image.tmdb.org/t/p/w500/wVTYlkKPKrljJfugXN7UlLNjtuJ.jpg', answer: 'freddy krueger', acceptable: ['freddy krueger', 'freddy', 'nightmare'], category: 'Personnage', difficulty: 'hard' },
  { url: 'https://image.tmdb.org/t/p/w500/nRGg2sOTwdLhWsVX8Ahc2LQJW4b.jpg', answer: 'ghostface', acceptable: ['ghostface', 'scream'], category: 'Personnage', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/xy44UvpbTgzs9kWmp5stD7XTlUt.jpg', answer: 'mario', acceptable: ['mario', 'super mario'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/bV3w9zJw6QZ8n64D0bzNuPEEOaD.jpg', answer: 'sonic', acceptable: ['sonic', 'sonic the hedgehog'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/uxj3DTBqRw1FJLynKjQ8Ckd2LlH.jpg', answer: 'pikachu', acceptable: ['pikachu', 'pokemon'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/nN9AvlnfVqijBJIcP1amDxkEHPC.jpg', answer: 'grinch', acceptable: ['grinch', 'le grinch'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/kiIq8xaOPCMPYRYnzNkSm5JdxaH.jpg', answer: 'minions', acceptable: ['minions', 'minion'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg', answer: 'olaf', acceptable: ['olaf', 'frozen'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/6bCplVkhowCjTHXWv49UjRPn0eK.jpg', answer: 'buzz lightyear', acceptable: ['buzz', 'buzz lightyear', 'toy story'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/dZ2aFhTfmHmroRNOfFntyCIBvkq.jpg', answer: 'woody', acceptable: ['woody', 'toy story'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/dNu30xISYbiZVyWOWpuSV0sPgHr.jpg', answer: 'nemo', acceptable: ['nemo', 'finding nemo', 'le monde de nemo'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/iRkq3VXfNbEuxPFFLxpOy9ZLuOh.jpg', answer: 'shrek', acceptable: ['shrek'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/a6aw3JJPp0qnxHWAAX9lm8Epv1L.jpg', answer: 'donkey', acceptable: ['donkey', 'ane', 'shrek donkey'], category: 'Personnage', difficulty: 'medium' },

  // ========== JEUX VIDÉO (30+) ==========
  { url: 'https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg', answer: 'minecraft', acceptable: ['minecraft', 'steve'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/2E03IAGm6y0VPbpGj6kEz0B9FmE.jpg', answer: 'fortnite', acceptable: ['fortnite'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg', answer: 'counter strike', acceptable: ['counter strike', 'csgo', 'cs go', 'cs2'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg', answer: 'pubg', acceptable: ['pubg', 'playerunknown', 'battlegrounds'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg', answer: 'red dead redemption', acceptable: ['red dead', 'red dead redemption', 'rdr2', 'arthur morgan'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg', answer: 'gta 5', acceptable: ['gta', 'gta 5', 'gta v', 'grand theft auto'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg', answer: 'elden ring', acceptable: ['elden ring'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg', answer: 'cyberpunk', acceptable: ['cyberpunk', 'cyberpunk 2077'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg', answer: 'the witcher 3', acceptable: ['witcher 3', 'the witcher 3', 'witcher', 'geralt'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg', answer: 'dota 2', acceptable: ['dota', 'dota 2'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg', answer: 'apex legends', acceptable: ['apex', 'apex legends'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1238810/header.jpg', answer: 'battlefield', acceptable: ['battlefield', 'bf'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/381210/header.jpg', answer: 'dead by daylight', acceptable: ['dead by daylight', 'dbd'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg', answer: 'rust', acceptable: ['rust'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/230410/header.jpg', answer: 'warframe', acceptable: ['warframe'], category: 'Jeux Vidéo', difficulty: 'hard' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/582010/header.jpg', answer: 'monster hunter', acceptable: ['monster hunter', 'monster hunter world', 'mhw'], category: 'Jeux Vidéo', difficulty: 'hard' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/374320/header.jpg', answer: 'dark souls', acceptable: ['dark souls', 'dark souls 3', 'ds3'], category: 'Jeux Vidéo', difficulty: 'hard' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg', answer: 'terraria', acceptable: ['terraria'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg', answer: 'stardew valley', acceptable: ['stardew', 'stardew valley'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/945360/header.jpg', answer: 'among us', acceptable: ['among us', 'amogus'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1599340/header.jpg', answer: 'lost ark', acceptable: ['lost ark'], category: 'Jeux Vidéo', difficulty: 'hard' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1238840/header.jpg', answer: 'battlefield 5', acceptable: ['battlefield 5', 'bf5', 'bfv'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1623730/header.jpg', answer: 'palworld', acceptable: ['palworld'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg', answer: 'baldurs gate', acceptable: ['baldurs gate', 'baldurs gate 3', 'bg3'], category: 'Jeux Vidéo', difficulty: 'hard' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/548430/header.jpg', answer: 'deep rock galactic', acceptable: ['deep rock', 'deep rock galactic', 'drg'], category: 'Jeux Vidéo', difficulty: 'hard' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1203220/header.jpg', answer: 'naraka', acceptable: ['naraka', 'naraka bladepoint'], category: 'Jeux Vidéo', difficulty: 'hard' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/739630/header.jpg', answer: 'phasmophobia', acceptable: ['phasmo', 'phasmophobia'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/892970/header.jpg', answer: 'valheim', acceptable: ['valheim'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1966720/header.jpg', answer: 'lethal company', acceptable: ['lethal company'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1293830/header.jpg', answer: 'fall guys', acceptable: ['fall guys'], category: 'Jeux Vidéo', difficulty: 'easy' },

  // ========== LOGOS (26+) ==========
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png', answer: 'google', acceptable: ['google'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/1200px-Amazon_logo.svg.png', answer: 'amazon', acceptable: ['amazon'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/800px-Apple_logo_black.svg.png', answer: 'apple', acceptable: ['apple'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/1200px-Microsoft_logo.svg.png', answer: 'microsoft', acceptable: ['microsoft'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Facebook_f_logo_%282019%29.svg/1200px-Facebook_f_logo_%282019%29.svg.png', answer: 'facebook', acceptable: ['facebook', 'meta'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Instagram_logo_2016.svg/1200px-Instagram_logo_2016.svg.png', answer: 'instagram', acceptable: ['instagram', 'insta'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Logo_of_Twitter.svg/1200px-Logo_of_Twitter.svg.png', answer: 'twitter', acceptable: ['twitter', 'x'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/YouTube_full-color_icon_%282017%29.svg/1200px-YouTube_full-color_icon_%282017%29.svg.png', answer: 'youtube', acceptable: ['youtube'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Netflix_2015_logo.svg/1200px-Netflix_2015_logo.svg.png', answer: 'netflix', acceptable: ['netflix'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Spotify_logo_without_text.svg/800px-Spotify_logo_without_text.svg.png', answer: 'spotify', acceptable: ['spotify'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Coca-Cola_logo.svg/1200px-Coca-Cola_logo.svg.png', answer: 'coca cola', acceptable: ['coca cola', 'coca', 'coke'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/McDonald%27s_Golden_Arches.svg/800px-McDonald%27s_Golden_Arches.svg.png', answer: 'mcdonalds', acceptable: ['mcdonalds', 'mcdonald', 'mcdo'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Logo_NIKE.svg/1200px-Logo_NIKE.svg.png', answer: 'nike', acceptable: ['nike'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Adidas_Logo.svg/1200px-Adidas_Logo.svg.png', answer: 'adidas', acceptable: ['adidas'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/BMW_logo_%28gray%29.svg/800px-BMW_logo_%28gray%29.svg.png', answer: 'bmw', acceptable: ['bmw'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Logo.svg/800px-Mercedes-Logo.svg.png', answer: 'mercedes', acceptable: ['mercedes', 'mercedes benz'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Starbucks_Coffee.svg/800px-Starbucks_Coffee.svg.png', answer: 'starbucks', acceptable: ['starbucks'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Amazon_icon.svg/800px-Amazon_icon.svg.png', answer: 'amazon prime', acceptable: ['amazon prime', 'prime video'], category: 'Logo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/IKEA_logo.svg/1200px-IKEA_logo.svg.png', answer: 'ikea', acceptable: ['ikea'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/TikTok_logo.svg/800px-TikTok_logo.svg.png', answer: 'tiktok', acceptable: ['tiktok', 'tik tok'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/WhatsApp.svg/800px-WhatsApp.svg.png', answer: 'whatsapp', acceptable: ['whatsapp'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Twitch_logo_%282019%29.svg/1200px-Twitch_logo_%282019%29.svg.png', answer: 'twitch', acceptable: ['twitch'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Discord_Logo_%282022%29.svg/800px-Discord_Logo_%282022%29.svg.png', answer: 'discord', acceptable: ['discord'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Steam_icon_logo.svg/800px-Steam_icon_logo.svg.png', answer: 'steam', acceptable: ['steam'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Logonetflix.png/800px-Logonetflix.png', answer: 'netflix n', acceptable: ['netflix'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Spotify_logo_with_text.svg/1200px-Spotify_logo_with_text.svg.png', answer: 'spotify', acceptable: ['spotify'], category: 'Logo', difficulty: 'easy' },

  // ========== MONUMENTS (20+) ==========
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Tour_eiffel_at_sunrise_from_the_trocadero.jpg/800px-Tour_eiffel_at_sunrise_from_the_trocadero.jpg', answer: 'tour eiffel', acceptable: ['tour eiffel', 'eiffel', 'paris'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Big_Ben_London_12.2016.jpg/800px-Big_Ben_London_12.2016.jpg', answer: 'big ben', acceptable: ['big ben', 'london'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Statue_of_Liberty%2C_NY.jpg/800px-Statue_of_Liberty%2C_NY.jpg', answer: 'statue of liberty', acceptable: ['statue liberte', 'statue of liberty', 'liberty', 'new york'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Morning_From_the_Colosseum%21_%285901247416%29.jpg/1200px-Good_Morning_From_the_Colosseum%21_%285901247416%29.jpg', answer: 'colisee', acceptable: ['colisee', 'colosseum', 'rome'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Machu_Picchu%2C_Peru.jpg/1200px-Machu_Picchu%2C_Peru.jpg', answer: 'machu picchu', acceptable: ['machu picchu', 'perou'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Taj_Mahal_in_India_-_Tekniska_museet_-_Sweden_-_2021-04-20.jpg/1200px-Taj_Mahal_in_India_-_Tekniska_museet_-_Sweden_-_2021-04-20.jpg', answer: 'taj mahal', acceptable: ['taj mahal', 'inde'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/1200px-Kheops-Pyramid.jpg', answer: 'pyramide', acceptable: ['pyramide', 'pyramides', 'egypte', 'gizeh', 'cheops'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/GoldenGateBridge-001.jpg/1200px-GoldenGateBridge-001.jpg', answer: 'golden gate', acceptable: ['golden gate', 'golden gate bridge', 'san francisco'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Sydney_Opera_House_-_Dec_2008.jpg/1200px-Sydney_Opera_House_-_Dec_2008.jpg', answer: 'opera sydney', acceptable: ['opera sydney', 'sydney opera house', 'sydney'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Christ_the_Redeemer_-_Cristo_Redentor.jpg/800px-Christ_the_Redeemer_-_Cristo_Redentor.jpg', answer: 'christ redempteur', acceptable: ['christ redempteur', 'rio', 'bresil', 'christ the redeemer'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Great_Wall_of_China_%2824192017545%29.jpg/1200px-Great_Wall_of_China_%2824192017545%29.jpg', answer: 'muraille de chine', acceptable: ['muraille de chine', 'grande muraille', 'great wall', 'chine'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Cour_Napoleon_du_Louvre.jpg/1200px-Cour_Napoleon_du_Louvre.jpg', answer: 'louvre', acceptable: ['louvre', 'pyramide du louvre', 'musee du louvre', 'paris'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Leaning_tower_of_pisa_2.jpg/800px-Leaning_tower_of_pisa_2.jpg', answer: 'tour de pise', acceptable: ['tour de pise', 'pise', 'pisa'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Parthenon_from_west.jpg/1200px-Parthenon_from_west.jpg', answer: 'parthenon', acceptable: ['parthenon', 'acropole', 'athenes'], category: 'Monument', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Petra_Jordan_BW_21.JPG/1200px-Petra_Jordan_BW_21.JPG', answer: 'petra', acceptable: ['petra', 'jordanie'], category: 'Monument', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Kremlin_birds_eye_view-1.jpg/1200px-Kremlin_birds_eye_view-1.jpg', answer: 'kremlin', acceptable: ['kremlin', 'moscou', 'russie'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Stonehenge%2C_Salisbury_retance.jpg/1200px-Stonehenge%2C_Salisbury_retance.jpg', answer: 'stonehenge', acceptable: ['stonehenge'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Empire_State_Building_%28aerial_view%29.jpg/800px-Empire_State_Building_%28aerial_view%29.jpg', answer: 'empire state building', acceptable: ['empire state', 'empire state building', 'new york'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Sagrada_Familia_01.jpg/800px-Sagrada_Familia_01.jpg', answer: 'sagrada familia', acceptable: ['sagrada familia', 'barcelone'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Burj_Khalifa.jpg/800px-Burj_Khalifa.jpg', answer: 'burj khalifa', acceptable: ['burj khalifa', 'dubai'], category: 'Monument', difficulty: 'medium' },

  // ========== ART (15+) ==========
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg', answer: 'joconde', acceptable: ['joconde', 'mona lisa', 'da vinci', 'vinci'], category: 'Art', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1200px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg', answer: 'nuit etoilee', acceptable: ['nuit etoilee', 'starry night', 'van gogh'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/VanGogh-starry_night_ballance1.jpg/1200px-VanGogh-starry_night_ballance1.jpg', answer: 'van gogh', acceptable: ['van gogh', 'nuit etoilee'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/The_Scream.jpg/800px-The_Scream.jpg', answer: 'le cri', acceptable: ['le cri', 'the scream', 'munch'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/American_Gothic.jpg/800px-American_Gothic.jpg', answer: 'american gothic', acceptable: ['american gothic'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/David_by_Michelangelo_Fir_JBU002.jpg/800px-David_by_Michelangelo_Fir_JBU002.jpg', answer: 'david', acceptable: ['david', 'michelangelo', 'michel ange'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Creation_of_Adam_%28Michelangelo%29_Detail.jpg/1200px-Creation_of_Adam_%28Michelangelo%29_Detail.jpg', answer: 'creation dadam', acceptable: ['creation dadam', 'adam', 'chapelle sixtine', 'sistine'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Sunflowers_by_Van_Gogh.jpg/800px-Sunflowers_by_Van_Gogh.jpg', answer: 'tournesols', acceptable: ['tournesols', 'sunflowers', 'van gogh'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1200px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg', answer: 'naissance de venus', acceptable: ['naissance venus', 'venus', 'botticelli'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/La_Libert%C3%A9_guidant_le_peuple_-_Eug%C3%A8ne_Delacroix_-_Mus%C3%A9e_du_Louvre_Peintures_RF_129_-_apr%C3%A8s_restauration_2024.jpg/1200px-La_Libert%C3%A9_guidant_le_peuple_-_Eug%C3%A8ne_Delacroix_-_Mus%C3%A9e_du_Louvre_Peintures_RF_129_-_apr%C3%A8s_restauration_2024.jpg', answer: 'liberte guidant le peuple', acceptable: ['liberte guidant le peuple', 'delacroix', 'marianne'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/The_Scream.jpg/800px-The_Scream.jpg', answer: 'the scream', acceptable: ['the scream', 'le cri', 'munch'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Pieta_di_Michelangelo_-_St._Peter%27s_Basilica_-_Vatican_City.jpg/800px-Pieta_di_Michelangelo_-_St._Peter%27s_Basilica_-_Vatican_City.jpg', answer: 'pieta', acceptable: ['pieta', 'michelangelo', 'pietà'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Meisje_met_de_parel.jpg/800px-Meisje_met_de_parel.jpg', answer: 'jeune fille a la perle', acceptable: ['jeune fille perle', 'girl with pearl earring', 'vermeer'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg', answer: 'chat', acceptable: ['chat', 'cat'], category: 'Art', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/1200px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg', answer: 'nympheas', acceptable: ['nympheas', 'water lilies', 'monet'], category: 'Art', difficulty: 'hard' },

  // ========== WAVE 1 — Extensions massives ==========
  // ANIME +30
  { url: 'https://cdn.myanimelist.net/images/anime/1517/142105.jpg', answer: 'jojo bizarre adventure', acceptable: ['jojo', 'jojos bizarre adventure', 'jojo bizarre adventure'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1908/135431.jpg', answer: 'spy x family', acceptable: ['spy x family', 'spy family'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/1259/110227.jpg', answer: 'evangelion', acceptable: ['evangelion', 'neon genesis evangelion', 'eva'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/2/73245.jpg', answer: 'pokemon', acceptable: ['pokemon', 'pikachu', 'sacha'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/1295/106551.jpg', answer: 'beastars', acceptable: ['beastars', 'legoshi'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1564/127378.jpg', answer: 'erased', acceptable: ['erased', 'boku dake ga inai machi'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/9/74398.jpg', answer: 'tokyo magnitude', acceptable: ['tokyo magnitude', 'tokyo magnitude 8'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1764/126627.jpg', answer: 'bleach tybw', acceptable: ['bleach', 'bleach thousand year', 'tybw'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1170/124312.jpg', answer: 'rezero', acceptable: ['re zero', 'rezero', 'subaru'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1916/137984.jpg', answer: 'oshi no ko saison 2', acceptable: ['oshi no ko', 'aqua', 'ruby'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1934/127823.jpg', answer: 'wind breaker', acceptable: ['wind breaker', 'windbreaker'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1908/108943.jpg', answer: 'overlord', acceptable: ['overlord', 'ainz'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1564/95390.jpg', answer: 'no game no life', acceptable: ['no game no life', 'sora shiro'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/5/64449.jpg', answer: 'fate stay night', acceptable: ['fate stay night', 'fate', 'fate zero'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1614/90408.jpg', answer: 'made in abyss', acceptable: ['made in abyss', 'riko'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/13/22128.jpg', answer: 'psycho pass', acceptable: ['psycho pass', 'psychopass'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1480/103018.jpg', answer: 'beyblade', acceptable: ['beyblade'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/8/13713.jpg', answer: 'nichijou', acceptable: ['nichijou'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/4/19644.jpg', answer: 'k on', acceptable: ['k on', 'kon', 'k-on'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1764/79262.jpg', answer: 'a silent voice', acceptable: ['silent voice', 'a silent voice', 'koe no katachi'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1614/124943.jpg', answer: 'suzume', acceptable: ['suzume'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1872/95475.jpg', answer: 'weathering with you', acceptable: ['weathering with you', 'tenki no ko'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1614/90395.jpg', answer: 'mononoke', acceptable: ['mononoke', 'princesse mononoke', 'princess mononoke'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/3/14559.jpg', answer: 'spirited away', acceptable: ['spirited away', 'chihiro', 'voyage de chihiro'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/1614/116681.jpg', answer: 'totoro', acceptable: ['totoro', 'mon voisin totoro', 'my neighbor totoro'], category: 'Anime', difficulty: 'easy' },
  { url: 'https://cdn.myanimelist.net/images/anime/1856/142253.jpg', answer: 'dandadan', acceptable: ['dandadan'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1019/138286.jpg', answer: 'shangri la frontier', acceptable: ['shangri la frontier', 'shangri-la'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1335/138110.jpg', answer: 'classroom of the elite', acceptable: ['classroom of the elite', 'cote'], category: 'Anime', difficulty: 'hard' },
  { url: 'https://cdn.myanimelist.net/images/anime/1182/127239.jpg', answer: 'konosuba', acceptable: ['konosuba', 'kazuma'], category: 'Anime', difficulty: 'medium' },
  { url: 'https://cdn.myanimelist.net/images/anime/1271/137062.jpg', answer: 'the eminence in shadow', acceptable: ['eminence in shadow', 'shadow garden'], category: 'Anime', difficulty: 'hard' },

  // FILMS +30
  { url: 'https://image.tmdb.org/t/p/w500/4woSOUD0equAYzvwhWBHIJDCM88.jpg', answer: 'avengers infinity war', acceptable: ['avengers', 'infinity war'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/eqxgmqugjLDb4d9bC1msIxbnVgB.jpg', answer: 'doctor strange', acceptable: ['doctor strange', 'strange'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/qjFXGFXSkYIQYqyKK6TVjeOMlnZ.jpg', answer: 'deadpool', acceptable: ['deadpool'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/A7EByudX0eOzlkQ2FIbogzyazm2.jpg', answer: 'wonder woman', acceptable: ['wonder woman'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/8aF0iAKH9MJMYAZdi0Slg77RYa2.jpg', answer: 'wolverine', acceptable: ['wolverine', 'logan'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/9hofu3LXKzECxEjnoVuXjcEZsBT.jpg', answer: 'la la land', acceptable: ['la la land'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/3IhGkkalwXguTlceGSl8XUJZOVI.jpg', answer: 'whiplash', acceptable: ['whiplash'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', answer: 'parasite', acceptable: ['parasite'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/iIvQnZyzgx9TkbrOgcXx0Z9KJVA.jpg', answer: 'everything everywhere all at once', acceptable: ['everything everywhere', 'eeaao'], category: 'Film', difficulty: 'hard' },
  { url: 'https://image.tmdb.org/t/p/w500/aDUOiEwlV5XYP1lvLBgKfM3F3Iv.jpg', answer: 'wall-e', acceptable: ['wall-e', 'wall e'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg', answer: 'up', acceptable: ['up', 'la haut'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg', answer: 'finding nemo', acceptable: ['nemo', 'finding nemo', 'monde de nemo'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg', answer: 'ratatouille', acceptable: ['ratatouille'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/jD7VMxJyf1pZkUEXfeUjjkflEUJ.jpg', answer: 'coco', acceptable: ['coco'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/qzM3yPCwZ4DXEMzljjSfgKxYdo7.jpg', answer: 'soul', acceptable: ['soul'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/db32LaOibwEliAmSL2jjDF6oDdj.jpg', answer: 'moana', acceptable: ['moana', 'vaiana'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/3Nn5BOM1EVs1travJuUBXrG6xLT.jpg', answer: 'tangled', acceptable: ['tangled', 'raiponce'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg', answer: 'aladdin', acceptable: ['aladdin'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/5UDdaWALOQhBpdMxsSqaTtb5MVT.jpg', answer: 'la belle et la bete', acceptable: ['belle et la bete', 'beauty and the beast'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/sTKcVkS3I2efJ7r0lWVMHQumXh.jpg', answer: 'encanto', acceptable: ['encanto'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg', answer: 'spider-man into the spider-verse', acceptable: ['spider verse', 'spider-verse', 'spiderverse'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/dvBCdCohwWbsP5qAaglOXagDMtk.jpg', answer: 'minions', acceptable: ['minions'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/aTvePCU7exLepwg5hWySjwxojQK.jpg', answer: 'kung fu panda', acceptable: ['kung fu panda'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/wXsQvli6tWqja51pYxXNG1mFQKQ.jpg', answer: 'how to train your dragon', acceptable: ['how to train your dragon', 'dragons'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/sZgQmuvyqHWl5HMkOC4kdpDgyek.jpg', answer: 'mission impossible', acceptable: ['mission impossible', 'mi'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg', answer: 'james bond', acceptable: ['james bond', 'bond', '007'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/q3MAOcoYwDqp7iDjs8sTrtnNg7t.jpg', answer: 'fight club', acceptable: ['fight club'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg', answer: 'the truman show', acceptable: ['truman show', 'the truman show'], category: 'Film', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/5MfRPjbm9C7ETIa9mPnvKMyrjuw.jpg', answer: 'pirates des caraibes', acceptable: ['pirates des caraibes', 'pirates of the caribbean', 'jack sparrow'], category: 'Film', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg', answer: 'star wars', acceptable: ['star wars'], category: 'Film', difficulty: 'easy' },

  // SÉRIES +30
  { url: 'https://image.tmdb.org/t/p/w500/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg', answer: 'house md', acceptable: ['house', 'doctor house', 'house md'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/9TZHK6XEYqI3wKlpGSqsRJUgZwI.jpg', answer: 'how i met your mother', acceptable: ['himym', 'how i met your mother'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/2DXIQss0Lzef5JaZ9z7BgxgxQbV.jpg', answer: 'big bang theory', acceptable: ['big bang theory', 'tbbt'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/85cWkCVftiVs0BVey6pxX8uNmLt.jpg', answer: 'modern family', acceptable: ['modern family'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/c7TQqIeoCBjNqAdfHGcD5BiAyKL.jpg', answer: 'brooklyn nine nine', acceptable: ['brooklyn 99', 'brooklyn nine nine', 'b99'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg', answer: 'lost', acceptable: ['lost'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/2gE7lKuQH6yiC9SkdlOcUYUWooi.jpg', answer: 'westworld', acceptable: ['westworld'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/gSGiZj9bQ5b4uYUNlPLm5VtvSDD.jpg', answer: 'true detective', acceptable: ['true detective'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/3Jl6Q0lZAOFLLk0OXBxN8jZmEzz.jpg', answer: 'mr robot', acceptable: ['mr robot', 'mister robot'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/8X9iZAJgnQE5ngBdiC2yfgPotXp.jpg', answer: 'black mirror', acceptable: ['black mirror'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/35SS0nlBhu28cSe7DTcQ7CGiTzJ.jpg', answer: 'love death robots', acceptable: ['love death robots', 'love death + robots'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/jHRf7uMNVE8aZH0vsRcoPXJ6oQQ.jpg', answer: 'the umbrella academy', acceptable: ['umbrella academy'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/jWLOPzCnvqRcfdvJDBwIb87QXm9.jpg', answer: 'euphoria', acceptable: ['euphoria'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/A48b9OBcMqcfM2Aw9TGuhJpkSGE.jpg', answer: 'lupin', acceptable: ['lupin'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/du8GbgyJ6yjJqVcJZqGTC4xfDfL.jpg', answer: 'dark', acceptable: ['dark'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg', answer: 'ozark', acceptable: ['ozark'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/iCmGcjQXxXuRSjsKqHePc7hzdt7.jpg', answer: 'you', acceptable: ['you'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg', answer: 'severance', acceptable: ['severance'], category: 'Série', difficulty: 'hard' },
  { url: 'https://image.tmdb.org/t/p/w500/49DZeJtmShdNQbZFf1JFXmH53yp.jpg', answer: 'the white lotus', acceptable: ['white lotus', 'the white lotus'], category: 'Série', difficulty: 'hard' },
  { url: 'https://image.tmdb.org/t/p/w500/rfV3IzhUuvyB7zJUhqWBSbDfH2j.jpg', answer: 'ted lasso', acceptable: ['ted lasso'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/7vQEr3jrAUiyRtnPYZBNkjQ7M4N.jpg', answer: 'shameless', acceptable: ['shameless'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/9LX1OYbsl3pcaFpVuyRWAcQ8Heh.jpg', answer: 'gossip girl', acceptable: ['gossip girl'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/wq3RM6jcvJaQHcAjlEz6Lq8jHnD.jpg', answer: 'pretty little liars', acceptable: ['pretty little liars', 'pll'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/sX4nPahREuvfAVHkrWfXcZcTppV.jpg', answer: 'riverdale', acceptable: ['riverdale'], category: 'Série', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/wXSnajAZ5ppTKa8Z5zwfdHrPwYU.jpg', answer: 'the 100', acceptable: ['the 100', '100'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/9lhWZH3RhSPCveQOZbqKzbXdMwI.jpg', answer: 'la chronique des bridgerton', acceptable: ['bridgerton', 'chronique des bridgerton'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/y2ssrnHdEAv3W6Tlfl9oZ1AscJG.jpg', answer: 'fleabag', acceptable: ['fleabag'], category: 'Série', difficulty: 'hard' },
  { url: 'https://image.tmdb.org/t/p/w500/h2H7OmrZ5pYPbsHkXtwm5gCfFD0.jpg', answer: 'chernobyl', acceptable: ['chernobyl', 'tchernobyl'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/eWXJEh1JTuyN6Pp6X22UrqAfQNL.jpg', answer: 'rings of power', acceptable: ['rings of power', 'anneaux de pouvoir'], category: 'Série', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/qC0VRBpRsHrwTpqL3SbjVdLk9G8.jpg', answer: 'the bear', acceptable: ['the bear', 'bear'], category: 'Série', difficulty: 'medium' },

  // PERSONNAGES +25
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Mickey_Mouse.png/600px-Mickey_Mouse.png', answer: 'mickey mouse', acceptable: ['mickey', 'mickey mouse'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/3/3b/SpongeBob_SquarePants_character.svg', answer: 'bob leponge', acceptable: ['bob leponge', 'spongebob', 'sponge bob'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/d/d8/Bart_Simpson_200px.png', answer: 'bart simpson', acceptable: ['bart simpson', 'bart'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/0/02/Homer_Simpson_2006.png', answer: 'homer simpson', acceptable: ['homer simpson', 'homer'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Pikachu_artwork_for_Pok%C3%A9mon_Red_and_Blue.png', answer: 'pikachu', acceptable: ['pikachu'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/0/05/Sonic_modern_and_classic_designs.png', answer: 'sonic', acceptable: ['sonic'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/8/80/Mario_Series_Logo.svg', answer: 'mario', acceptable: ['mario', 'super mario'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/1/16/Luigi_-_Super_Mario.png', answer: 'luigi', acceptable: ['luigi'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/0/0d/Link_%28Tears_of_the_Kingdom%29.png', answer: 'link', acceptable: ['link', 'zelda'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/9/99/MarvelLogo.svg', answer: 'marvel', acceptable: ['marvel'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/g7ip2LKbcKBKDC3UbsxC4D38jtj.jpg', answer: 'thor', acceptable: ['thor'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/9O1Iy9od7uGEFFkrJOLcMZsBLn.jpg', answer: 'captain america', acceptable: ['captain america', 'cap'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg', answer: 'star lord', acceptable: ['star lord', 'star-lord', 'peter quill'], category: 'Personnage', difficulty: 'medium' },
  { url: 'https://image.tmdb.org/t/p/w500/jpngsX1lAYBjjzwODlnRmsfFlxF.jpg', answer: 'hulk', acceptable: ['hulk', 'bruce banner'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/0/00/Superman_S_symbol.svg', answer: 'superman', acceptable: ['superman', 'clark kent'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Batman_Logo.svg/1200px-Batman_Logo.svg.png', answer: 'batman', acceptable: ['batman', 'bruce wayne'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Yoda_Christmas_lights.png/600px-Yoda_Christmas_lights.png', answer: 'yoda', acceptable: ['yoda', 'maitre yoda'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/d/d6/Kratos_God_of_War_Ragnarok.png', answer: 'kratos', acceptable: ['kratos', 'god of war'], category: 'Personnage', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/f/f6/Aloy_Horizon_Forbidden_West.png', answer: 'aloy', acceptable: ['aloy', 'horizon'], category: 'Personnage', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/5/57/Lara_Croft_Survivor.png', answer: 'lara croft', acceptable: ['lara croft', 'tomb raider'], category: 'Personnage', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/1/16/Master_Chief_helmet_off.png', answer: 'master chief', acceptable: ['master chief', 'halo'], category: 'Personnage', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/4/4d/Cloud_Strife_Remake.png', answer: 'cloud strife', acceptable: ['cloud', 'cloud strife', 'ff7'], category: 'Personnage', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/1/15/Geralt_of_Rivia_render.png', answer: 'geralt', acceptable: ['geralt', 'witcher', 'geralt de riv'], category: 'Personnage', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/2/22/SolidSnake.jpg', answer: 'solid snake', acceptable: ['solid snake', 'snake', 'metal gear'], category: 'Personnage', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/c/c1/Crash_Bandicoot.png', answer: 'crash bandicoot', acceptable: ['crash bandicoot', 'crash'], category: 'Personnage', difficulty: 'medium' },

  // JEUX VIDÉO +30
  { url: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg', answer: 'the witcher 3', acceptable: ['witcher 3', 'the witcher 3', 'witcher'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/4/46/Cyberpunk_2077_box_art.jpg', answer: 'cyberpunk 2077', acceptable: ['cyberpunk', 'cyberpunk 2077'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/0/04/Elden_Ring_Box_art.jpg', answer: 'elden ring', acceptable: ['elden ring'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/4/4a/Dark_Souls_3_cover_art.jpg', answer: 'dark souls 3', acceptable: ['dark souls', 'dark souls 3'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/3/3f/Bloodborne_Cover_Wallpaper.jpg', answer: 'bloodborne', acceptable: ['bloodborne'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/8/87/Sekiro_art.jpg', answer: 'sekiro', acceptable: ['sekiro', 'shadows die twice'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/f/f8/God_of_War_Ragnar%C3%B6k_cover.jpg', answer: 'god of war ragnarok', acceptable: ['god of war', 'ragnarok', 'god of war ragnarok'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Horizon_Zero_Dawn.jpg', answer: 'horizon zero dawn', acceptable: ['horizon zero dawn', 'horizon'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/4/46/The_Last_of_Us_Part_II_cover.png', answer: 'the last of us 2', acceptable: ['last of us 2', 'tlou 2', 'the last of us part 2'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/5/5e/Uncharted_4_box_artwork.jpg', answer: 'uncharted 4', acceptable: ['uncharted', 'uncharted 4'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/1/14/Red_Dead_Redemption_II.jpg', answer: 'red dead redemption 2', acceptable: ['rdr2', 'red dead redemption 2', 'red dead'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png', answer: 'gta 5', acceptable: ['gta', 'gta 5', 'grand theft auto v'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/4/45/Minecraftcover.png', answer: 'minecraft', acceptable: ['minecraft'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Fortnite_cover.jpg', answer: 'fortnite', acceptable: ['fortnite'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/d/d3/Valorant_cover.jpg', answer: 'valorant', acceptable: ['valorant'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/0/04/Overwatch_cover_art.jpg', answer: 'overwatch', acceptable: ['overwatch'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/0/01/Counter-Strike_2_cover_art.jpg', answer: 'counter strike 2', acceptable: ['cs2', 'counter strike', 'counter strike 2'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/d/d8/Among_Us_cover_art.jpg', answer: 'among us', acceptable: ['among us'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/9/94/Fall_Guys_cover.jpg', answer: 'fall guys', acceptable: ['fall guys'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/c/c2/Animal_Crossing_New_Horizons.jpg', answer: 'animal crossing', acceptable: ['animal crossing', 'new horizons'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/3/3e/Hades_cover_art.jpg', answer: 'hades', acceptable: ['hades'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Stardew_Valley_Box_Art.jpg', answer: 'stardew valley', acceptable: ['stardew valley', 'stardew'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/8/83/Hollow_Knight_cover.jpg', answer: 'hollow knight', acceptable: ['hollow knight'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/8/8a/Celeste_box_art_full.png', answer: 'celeste', acceptable: ['celeste'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/e/ed/Cuphead_%28artwork%29.png', answer: 'cuphead', acceptable: ['cuphead'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/d/dd/Portal2cover.jpg', answer: 'portal 2', acceptable: ['portal', 'portal 2'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Half-Life_2_cover.jpg', answer: 'half life 2', acceptable: ['half life', 'half life 2'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/2/25/Bioshock_Cover.jpg', answer: 'bioshock', acceptable: ['bioshock'], category: 'Jeux Vidéo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/2/2a/Halo_-_Combat_Evolved_%28XBox_version_-_box_art%29.jpg', answer: 'halo', acceptable: ['halo'], category: 'Jeux Vidéo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/en/8/82/Forza_Horizon_5_cover_art.jpg', answer: 'forza horizon 5', acceptable: ['forza', 'forza horizon', 'forza horizon 5'], category: 'Jeux Vidéo', difficulty: 'medium' },

  // LOGOS +25
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png', answer: 'google', acceptable: ['google'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/1200px-Amazon_logo.svg.png', answer: 'amazon', acceptable: ['amazon'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/600px-Apple_logo_black.svg.png', answer: 'apple', acceptable: ['apple'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Microsoft_logo_%282012%29.svg/1200px-Microsoft_logo_%282012%29.svg.png', answer: 'microsoft', acceptable: ['microsoft'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Netflix_2015_logo.svg/1200px-Netflix_2015_logo.svg.png', answer: 'netflix', acceptable: ['netflix'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Spotify_logo_with_text.svg/1200px-Spotify_logo_with_text.svg.png', answer: 'spotify', acceptable: ['spotify'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/YouTube_Logo_2017.svg/1200px-YouTube_Logo_2017.svg.png', answer: 'youtube', acceptable: ['youtube'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Facebook_f_logo_%282019%29.svg/600px-Facebook_f_logo_%282019%29.svg.png', answer: 'facebook', acceptable: ['facebook', 'fb', 'meta'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/600px-Instagram_icon.png', answer: 'instagram', acceptable: ['instagram', 'insta', 'ig'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/X_logo_2023.svg/600px-X_logo_2023.svg.png', answer: 'x twitter', acceptable: ['twitter', 'x'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Tiktok-logo.png/600px-Tiktok-logo.png', answer: 'tiktok', acceptable: ['tiktok', 'tik tok'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Logo_2013_Google.png/1200px-Logo_2013_Google.png', answer: 'google old', acceptable: ['google'], category: 'Logo', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Coca-Cola_logo.svg/1200px-Coca-Cola_logo.svg.png', answer: 'coca cola', acceptable: ['coca cola', 'coca', 'coke'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Pepsi_logo_2014.svg/1200px-Pepsi_logo_2014.svg.png', answer: 'pepsi', acceptable: ['pepsi'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/McDonald%27s_Golden_Arches.svg/600px-McDonald%27s_Golden_Arches.svg.png', answer: 'mcdonalds', acceptable: ['mcdo', 'mcdonalds', 'mcdonald'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Burger_King_Logo.svg/600px-Burger_King_Logo.svg.png', answer: 'burger king', acceptable: ['burger king', 'bk'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/600px-Starbucks_Corporation_Logo_2011.svg.png', answer: 'starbucks', acceptable: ['starbucks'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Logo_NIKE.svg/1200px-Logo_NIKE.svg.png', answer: 'nike', acceptable: ['nike'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Adidas_Logo.svg/1200px-Adidas_Logo.svg.png', answer: 'adidas', acceptable: ['adidas'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/PUMA_logo.svg/1200px-PUMA_logo.svg.png', answer: 'puma', acceptable: ['puma'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/BMW.svg/600px-BMW.svg.png', answer: 'bmw', acceptable: ['bmw'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Logo.svg/600px-Mercedes-Logo.svg.png', answer: 'mercedes', acceptable: ['mercedes', 'mercedes benz'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Audi-Logo_2016.svg/1200px-Audi-Logo_2016.svg.png', answer: 'audi', acceptable: ['audi'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Ferrari-Logo.svg/600px-Ferrari-Logo.svg.png', answer: 'ferrari', acceptable: ['ferrari'], category: 'Logo', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Tesla_T_symbol.svg/600px-Tesla_T_symbol.svg.png', answer: 'tesla', acceptable: ['tesla'], category: 'Logo', difficulty: 'easy' },

  // MONUMENTS +20
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg/600px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg', answer: 'tour eiffel', acceptable: ['tour eiffel', 'eiffel', 'paris'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Arc_de_Triomphe_de_l%27%C3%89toile%2C_Paris_21_October_2010.jpg/1200px-Arc_de_Triomphe_de_l%27%C3%89toile%2C_Paris_21_October_2010.jpg', answer: 'arc de triomphe', acceptable: ['arc de triomphe', 'paris'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Notre_Dame_de_Paris_DSC_0846w.jpg/1200px-Notre_Dame_de_Paris_DSC_0846w.jpg', answer: 'notre dame', acceptable: ['notre dame', 'notre dame de paris', 'paris'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Mont-Saint-Michel-Picture.jpg/1200px-Mont-Saint-Michel-Picture.jpg', answer: 'mont saint michel', acceptable: ['mont saint michel'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Versailles_Chateau.jpg/1200px-Versailles_Chateau.jpg', answer: 'chateau de versailles', acceptable: ['versailles', 'chateau de versailles'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Brandenburger_Tor_abends.jpg/1200px-Brandenburger_Tor_abends.jpg', answer: 'porte de brandebourg', acceptable: ['porte de brandebourg', 'brandenburg', 'berlin'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Reichstag_building_Berlin_view_from_west_before_sunset.jpg/1200px-Reichstag_building_Berlin_view_from_west_before_sunset.jpg', answer: 'reichstag', acceptable: ['reichstag', 'berlin'], category: 'Monument', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tower_Bridge_from_Shad_Thames.jpg/1200px-Tower_Bridge_from_Shad_Thames.jpg', answer: 'tower bridge', acceptable: ['tower bridge', 'london'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Buckingham_Palace_from_gardens%2C_London%2C_UK_-_Diliff.jpg/1200px-Buckingham_Palace_from_gardens%2C_London%2C_UK_-_Diliff.jpg', answer: 'buckingham palace', acceptable: ['buckingham', 'buckingham palace'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Big_Ben_2012-1.JPG/600px-Big_Ben_2012-1.JPG', answer: 'big ben', acceptable: ['big ben', 'londres'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Stonehenge_Closeup.jpg/1200px-Stonehenge_Closeup.jpg', answer: 'stonehenge', acceptable: ['stonehenge'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Statue_of_Liberty_7.jpg/600px-Statue_of_Liberty_7.jpg', answer: 'statue de la liberte', acceptable: ['statue de la liberte', 'liberty', 'new york'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Mount_Rushmore_detail_view_%28100MP%29.jpg/1200px-Mount_Rushmore_detail_view_%28100MP%29.jpg', answer: 'mont rushmore', acceptable: ['mont rushmore', 'rushmore'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Hagia_Sophia_Mars_2013.jpg/1200px-Hagia_Sophia_Mars_2013.jpg', answer: 'sainte sophie', acceptable: ['sainte sophie', 'hagia sophia', 'istanbul'], category: 'Monument', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Acropolis_at_Athens.jpg/1200px-Acropolis_at_Athens.jpg', answer: 'acropole athenes', acceptable: ['acropole', 'athenes', 'acropolis'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Angkor_Wat.jpg/1200px-Angkor_Wat.jpg', answer: 'angkor wat', acceptable: ['angkor wat', 'angkor', 'cambodge'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Forbidden_City_Beijing_Shenwumen_Gate.jpg/1200px-Forbidden_City_Beijing_Shenwumen_Gate.jpg', answer: 'cite interdite', acceptable: ['cite interdite', 'forbidden city', 'pekin'], category: 'Monument', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Niagara_Falls_-_USA_side.jpg/1200px-Niagara_Falls_-_USA_side.jpg', answer: 'chutes du niagara', acceptable: ['niagara', 'chutes du niagara', 'niagara falls'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Grand_Canyon_view_from_Pima_Point_2010.jpg/1200px-Grand_Canyon_view_from_Pima_Point_2010.jpg', answer: 'grand canyon', acceptable: ['grand canyon'], category: 'Monument', difficulty: 'easy' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Neuschwanstein_Castle_LOC_print.jpg/1200px-Neuschwanstein_Castle_LOC_print.jpg', answer: 'chateau de neuschwanstein', acceptable: ['neuschwanstein', 'chateau allemagne'], category: 'Monument', difficulty: 'hard' },

  // ART +20
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/The_Persistence_of_Memory.jpg/1200px-The_Persistence_of_Memory.jpg', answer: 'persistance memoire', acceptable: ['persistance memoire', 'dali', 'montres molles'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Meninas_01.jpg/1200px-Meninas_01.jpg', answer: 'les menines', acceptable: ['les menines', 'velazquez'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Guernica_all-In-One_recreation.jpg/1200px-Guernica_all-In-One_recreation.jpg', answer: 'guernica', acceptable: ['guernica', 'picasso'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Edouard_Manet_-_Le_D%C3%A9jeuner_sur_l%27herbe.jpg/1200px-Edouard_Manet_-_Le_D%C3%A9jeuner_sur_l%27herbe.jpg', answer: 'dejeuner sur lherbe', acceptable: ['dejeuner sur lherbe', 'manet'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/800px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg', answer: 'autoportrait van gogh', acceptable: ['autoportrait van gogh', 'van gogh'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Frida_Kahlo_-_Self_Portrait_with_Thorn_Necklace_and_Hummingbird.jpg/800px-Frida_Kahlo_-_Self_Portrait_with_Thorn_Necklace_and_Hummingbird.jpg', answer: 'frida kahlo', acceptable: ['frida kahlo', 'frida'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Klimt_-_Der_Kuss.jpeg/800px-Klimt_-_Der_Kuss.jpeg', answer: 'le baiser klimt', acceptable: ['le baiser', 'klimt', 'der kuss'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Hokusai-Mangwa3-Hannya.jpg/600px-Hokusai-Mangwa3-Hannya.jpg', answer: 'hokusai', acceptable: ['hokusai'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tsunami_by_hokusai_19th_century.jpg/1200px-Tsunami_by_hokusai_19th_century.jpg', answer: 'vague hokusai', acceptable: ['vague hokusai', 'great wave', 'la vague'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Banksy.LoveIsInTheAir.jpg/1200px-Banksy.LoveIsInTheAir.jpg', answer: 'banksy', acceptable: ['banksy', 'love is in the air'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Andy_Warhol_-_Campbells_Soup_Can_1962.jpg/800px-Andy_Warhol_-_Campbells_Soup_Can_1962.jpg', answer: 'campbell soup warhol', acceptable: ['warhol', 'campbell soup', 'andy warhol'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Roy_Lichtenstein_Drowning_Girl_1963.jpg/800px-Roy_Lichtenstein_Drowning_Girl_1963.jpg', answer: 'drowning girl', acceptable: ['drowning girl', 'lichtenstein'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Magritte_TheSonOfMan.jpg/800px-Magritte_TheSonOfMan.jpg', answer: 'fils de lhomme', acceptable: ['fils de lhomme', 'magritte', 'son of man'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg/1200px-The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg', answer: 'jardin des delices', acceptable: ['jardin des delices', 'bosch'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Botticelli-primavera.jpg/1200px-Botticelli-primavera.jpg', answer: 'le printemps botticelli', acceptable: ['printemps', 'primavera', 'botticelli'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Caravaggio_Narciso.jpg/800px-Caravaggio_Narciso.jpg', answer: 'narcisse caravage', acceptable: ['narcisse', 'caravage', 'caravaggio'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Edward_Hopper_-_Nighthawks.jpg/1200px-Edward_Hopper_-_Nighthawks.jpg', answer: 'nighthawks', acceptable: ['nighthawks', 'hopper', 'edward hopper'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Pierre-Auguste_Renoir_-_Le_Moulin_de_la_Galette.jpg/1200px-Pierre-Auguste_Renoir_-_Le_Moulin_de_la_Galette.jpg', answer: 'bal moulin de la galette', acceptable: ['moulin de la galette', 'renoir'], category: 'Art', difficulty: 'hard' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Claude_Monet%2C_Impression%2C_soleil_levant.jpg/1200px-Claude_Monet%2C_Impression%2C_soleil_levant.jpg', answer: 'impression soleil levant', acceptable: ['impression soleil levant', 'monet'], category: 'Art', difficulty: 'medium' },
  { url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Picasso_The_Old_Guitarist.jpg/800px-Picasso_The_Old_Guitarist.jpg', answer: 'vieux guitariste', acceptable: ['vieux guitariste', 'old guitarist', 'picasso'], category: 'Art', difficulty: 'hard' },
];

// Get images filtered by category
export function getImagesByCategory(category: BlurRushCategory): BlurRushImage[] {
  if (category === 'Mix') {
    return BLURRUSH_IMAGES;
  }
  return BLURRUSH_IMAGES.filter(img => img.category === category);
}

// Get random images for a game session
export function getRandomImages(
  count: number,
  categories: BlurRushCategory[] = ['Mix'],
  usedIndices: number[] = []
): { images: BlurRushImage[]; newUsedIndices: number[] } {
  let pool: BlurRushImage[];
  
  if (categories.includes('Mix') || categories.length === 0) {
    pool = [...BLURRUSH_IMAGES];
  } else {
    pool = BLURRUSH_IMAGES.filter(img => categories.includes(img.category));
  }

  // Get available indices
  const availableIndices = pool
    .map((_, i) => i)
    .filter(i => !usedIndices.includes(i));

  // Shuffle and pick
  const shuffled = [...availableIndices].sort(() => Math.random() - 0.5);
  const selectedIndices = shuffled.slice(0, Math.min(count, shuffled.length));
  
  return {
    images: selectedIndices.map(i => pool[i]),
    newUsedIndices: [...usedIndices, ...selectedIndices],
  };
}

export { BLURRUSH_IMAGES };
