// Word pairs for the Undercover game
// Each pair has a civilian word and an undercover word (similar but different)
export interface WordPair {
  civilian: string;
  undercover: string;
  category?: string;
}

export const WORD_PAIRS: WordPair[] = [
  // Animaux
  { civilian: "Chat", undercover: "Chien", category: "animaux" },
  { civilian: "Tigre", undercover: "Lion", category: "animaux" },
  { civilian: "Requin", undercover: "Dauphin", category: "animaux" },
  { civilian: "Serpent", undercover: "Lézard", category: "animaux" },
  { civilian: "Aigle", undercover: "Faucon", category: "animaux" },
  { civilian: "Cheval", undercover: "Âne", category: "animaux" },
  { civilian: "Lapin", undercover: "Hamster", category: "animaux" },
  { civilian: "Loup", undercover: "Renard", category: "animaux" },
  { civilian: "Papillon", undercover: "Libellule", category: "animaux" },
  { civilian: "Crocodile", undercover: "Alligator", category: "animaux" },

  // Nourriture
  { civilian: "Pizza", undercover: "Burger", category: "nourriture" },
  { civilian: "Pomme", undercover: "Poire", category: "nourriture" },
  { civilian: "Chocolat", undercover: "Caramel", category: "nourriture" },
  { civilian: "Croissant", undercover: "Pain au chocolat", category: "nourriture" },
  { civilian: "Hamburger", undercover: "Hot-dog", category: "nourriture" },
  { civilian: "Chips", undercover: "Pop-corn", category: "nourriture" },
  { civilian: "Sushi", undercover: "Maki", category: "nourriture" },
  { civilian: "Glace", undercover: "Sorbet", category: "nourriture" },
  { civilian: "Crêpe", undercover: "Gaufre", category: "nourriture" },
  { civilian: "Frites", undercover: "Potatoes", category: "nourriture" },
  { civilian: "Steak", undercover: "Entrecôte", category: "nourriture" },
  { civilian: "Bonbon", undercover: "Sucette", category: "nourriture" },
  { civilian: "Ketchup", undercover: "Mayonnaise", category: "nourriture" },
  { civilian: "Baguette", undercover: "Pain de mie", category: "nourriture" },

  // Boissons
  { civilian: "Café", undercover: "Thé", category: "boissons" },
  { civilian: "Whisky", undercover: "Rhum", category: "boissons" },
  { civilian: "Bière", undercover: "Vin", category: "boissons" },
  { civilian: "Coca-Cola", undercover: "Pepsi", category: "boissons" },
  { civilian: "Jus d'orange", undercover: "Limonade", category: "boissons" },
  { civilian: "Champagne", undercover: "Prosecco", category: "boissons" },

  // Sport
  { civilian: "Football", undercover: "Rugby", category: "sport" },
  { civilian: "Ski", undercover: "Snowboard", category: "sport" },
  { civilian: "Basket", undercover: "Handball", category: "sport" },
  { civilian: "Tennis", undercover: "Badminton", category: "sport" },
  { civilian: "Boxe", undercover: "MMA", category: "sport" },
  { civilian: "Surf", undercover: "Bodyboard", category: "sport" },
  { civilian: "Natation", undercover: "Plongée", category: "sport" },
  { civilian: "Marathon", undercover: "Sprint", category: "sport" },

  // Technologie / Marques
  { civilian: "iPhone", undercover: "Samsung", category: "tech" },
  { civilian: "Netflix", undercover: "YouTube", category: "tech" },
  { civilian: "TikTok", undercover: "Instagram", category: "tech" },
  { civilian: "Nike", undercover: "Adidas", category: "tech" },
  { civilian: "McDonald's", undercover: "Burger King", category: "tech" },
  { civilian: "PlayStation", undercover: "Xbox", category: "tech" },
  { civilian: "Google", undercover: "Bing", category: "tech" },
  { civilian: "Spotify", undercover: "Deezer", category: "tech" },
  { civilian: "Tesla", undercover: "BMW", category: "tech" },
  { civilian: "Amazon", undercover: "AliExpress", category: "tech" },

  // Pop Culture
  { civilian: "Superman", undercover: "Batman", category: "popculture" },
  { civilian: "Spider-Man", undercover: "Iron Man", category: "popculture" },
  { civilian: "Mario", undercover: "Sonic", category: "popculture" },
  { civilian: "Dragon Ball", undercover: "Naruto", category: "popculture" },
  { civilian: "Fortnite", undercover: "Minecraft", category: "popculture" },
  { civilian: "Manga", undercover: "Comics", category: "popculture" },
  { civilian: "Harry Potter", undercover: "Seigneur des Anneaux", category: "popculture" },
  { civilian: "Star Wars", undercover: "Star Trek", category: "popculture" },
  { civilian: "Disney", undercover: "Pixar", category: "popculture" },
  { civilian: "One Piece", undercover: "Bleach", category: "popculture" },
  { civilian: "Pokémon", undercover: "Digimon", category: "popculture" },
  { civilian: "GTA", undercover: "Red Dead Redemption", category: "popculture" },
  { civilian: "Joker", undercover: "Harley Quinn", category: "popculture" },

  // Musique
  { civilian: "Rap", undercover: "R&B", category: "musique" },
  { civilian: "Guitare", undercover: "Ukulélé", category: "musique" },
  { civilian: "Piano", undercover: "Violon", category: "musique" },
  { civilian: "Rock", undercover: "Metal", category: "musique" },
  { civilian: "DJ", undercover: "Beatmaker", category: "musique" },
  { civilian: "Concert", undercover: "Festival", category: "musique" },

  // Nature / Géographie
  { civilian: "Océan", undercover: "Mer", category: "nature" },
  { civilian: "Soleil", undercover: "Lune", category: "nature" },
  { civilian: "Paris", undercover: "Londres", category: "nature" },
  { civilian: "Montagne", undercover: "Colline", category: "nature" },
  { civilian: "Pluie", undercover: "Neige", category: "nature" },
  { civilian: "Volcan", undercover: "Geyser", category: "nature" },
  { civilian: "Forêt", undercover: "Jungle", category: "nature" },
  { civilian: "Désert", undercover: "Savane", category: "nature" },
  { civilian: "Lac", undercover: "Étang", category: "nature" },
  { civilian: "Île", undercover: "Presqu'île", category: "nature" },
  { civilian: "Tornade", undercover: "Ouragan", category: "nature" },

  // Objets du quotidien
  { civilian: "Couteau", undercover: "Fourchette", category: "objets" },
  { civilian: "Lunettes", undercover: "Lentilles", category: "objets" },
  { civilian: "Bague", undercover: "Bracelet", category: "objets" },
  { civilian: "Chaussettes", undercover: "Chaussures", category: "objets" },
  { civilian: "Rose", undercover: "Tulipe", category: "objets" },
  { civilian: "Canapé", undercover: "Fauteuil", category: "objets" },
  { civilian: "Stylo", undercover: "Crayon", category: "objets" },
  { civilian: "Miroir", undercover: "Vitre", category: "objets" },
  { civilian: "Parapluie", undercover: "Imperméable", category: "objets" },
  { civilian: "Bougie", undercover: "Lampe", category: "objets" },
  { civilian: "Oreiller", undercover: "Coussin", category: "objets" },
  { civilian: "Valise", undercover: "Sac à dos", category: "objets" },

  // Transport
  { civilian: "Train", undercover: "Métro", category: "transport" },
  { civilian: "Vélo", undercover: "Trottinette", category: "transport" },
  { civilian: "Voiture", undercover: "Moto", category: "transport" },
  { civilian: "Avion", undercover: "Hélicoptère", category: "transport" },
  { civilian: "Bus", undercover: "Tramway", category: "transport" },
  { civilian: "Bateau", undercover: "Yacht", category: "transport" },
  { civilian: "Taxi", undercover: "Uber", category: "transport" },

  // Métiers / Lieux
  { civilian: "Dentiste", undercover: "Médecin", category: "metiers" },
  { civilian: "Cinéma", undercover: "Théâtre", category: "metiers" },
  { civilian: "Piscine", undercover: "Lac", category: "metiers" },
  { civilian: "Dictionnaire", undercover: "Encyclopédie", category: "metiers" },
  { civilian: "Clown", undercover: "Magicien", category: "metiers" },
  { civilian: "Fantôme", undercover: "Zombie", category: "metiers" },
  { civilian: "Pompier", undercover: "Policier", category: "metiers" },
  { civilian: "Professeur", undercover: "Directeur", category: "metiers" },
  { civilian: "Hôpital", undercover: "Clinique", category: "metiers" },
  { civilian: "Bibliothèque", undercover: "Librairie", category: "metiers" },
  { civilian: "Restaurant", undercover: "Brasserie", category: "metiers" },
  { civilian: "Prison", undercover: "Caserne", category: "metiers" },

  // Concepts abstraits / fun
  { civilian: "Rêve", undercover: "Cauchemar", category: "concepts" },
  { civilian: "Amour", undercover: "Amitié", category: "concepts" },
  { civilian: "Courage", undercover: "Témérité", category: "concepts" },
  { civilian: "Vacances", undercover: "Week-end", category: "concepts" },
  { civilian: "Anniversaire", undercover: "Mariage", category: "concepts" },
  { civilian: "Noël", undercover: "Nouvel An", category: "concepts" },
  { civilian: "Examen", undercover: "Contrôle", category: "concepts" },
  { civilian: "Blague", undercover: "Devinette", category: "concepts" },

  // Anime / Manga — paires subtiles (même concept, univers différent)
  { civilian: "Kamehameha", undercover: "Rasengan", category: "anime" },
  { civilian: "Sharingan", undercover: "Byakugan", category: "anime" },
  { civilian: "Bankai", undercover: "Gear 5", category: "anime" },
  { civilian: "Titan", undercover: "Kaiju", category: "anime" },
  { civilian: "Hokage", undercover: "Roi des Pirates", category: "anime" },
  { civilian: "Akatsuki", undercover: "Espada", category: "anime" },
  { civilian: "Quirk", undercover: "Nen", category: "anime" },
  { civilian: "Gomu Gomu", undercover: "Mera Mera", category: "anime" },
  { civilian: "Senzu", undercover: "Potion", category: "anime" },
  { civilian: "Zanpakuto", undercover: "Katana", category: "anime" },
  { civilian: "Capsule Corp", undercover: "Stark Industries", category: "anime" },
  { civilian: "Konoha", undercover: "Gotham", category: "anime" },
  { civilian: "Saiyan", undercover: "Kryptonien", category: "anime" },
  { civilian: "Death Note", undercover: "Grimoire", category: "anime" },
  { civilian: "Examen Chunin", undercover: "Tournoi", category: "anime" },
  { civilian: "Invocation", undercover: "Fusion", category: "anime" },
  { civilian: "Genjutsu", undercover: "Hypnose", category: "anime" },
  { civilian: "Mangekyou", undercover: "Rinnegan", category: "anime" },
  { civilian: "Hollow", undercover: "Akuma", category: "anime" },
  { civilian: "Chakra", undercover: "Ki", category: "anime" },

  // Films / Séries — paires subtiles (même type d'objet/concept)
  { civilian: "Lightsaber", undercover: "Baguette magique", category: "films" },
  { civilian: "Infinity Stones", undercover: "Horcruxes", category: "films" },
  { civilian: "Batmobile", undercover: "DeLorean", category: "films" },
  { civilian: "Mjolnir", undercover: "Excalibur", category: "films" },
  { civilian: "Anneau unique", undercover: "Vif d'or", category: "films" },
  { civilian: "Étoile de la Mort", undercover: "Helicarrier", category: "films" },
  { civilian: "Poudlard", undercover: "Xavier School", category: "films" },
  { civilian: "Wakanda", undercover: "Asgard", category: "films" },
  { civilian: "Multivers", undercover: "Matrice", category: "films" },
  { civilian: "Portail", undercover: "Téléportation", category: "films" },
  { civilian: "Masque de fer", undercover: "Masque de V", category: "films" },
  { civilian: "Trône de fer", undercover: "Table ronde", category: "films" },
  { civilian: "Upside Down", undercover: "Monde des morts", category: "films" },
  { civilian: "Capsule temporelle", undercover: "Machine à voyager", category: "films" },
  { civilian: "Sérum", undercover: "Mutation", category: "films" },
  { civilian: "Kryptonite", undercover: "Vibranium", category: "films" },
  { civilian: "Bat-Signal", undercover: "Patronus", category: "films" },
  { civilian: "Costume", undercover: "Armure", category: "films" },
  { civilian: "Sidekick", undercover: "Mentor", category: "films" },
  { civilian: "Némésis", undercover: "Rival", category: "films" },

  // Jeux vidéo — paires subtiles (même mécanique/concept)
  { civilian: "Respawn", undercover: "Résurrection", category: "jeux" },
  { civilian: "Loot box", undercover: "Coffre au trésor", category: "jeux" },
  { civilian: "Battle Royale", undercover: "Deathmatch", category: "jeux" },
  { civilian: "Speedrun", undercover: "Time trial", category: "jeux" },
  { civilian: "Boss final", undercover: "Mini-boss", category: "jeux" },
  { civilian: "Easter egg", undercover: "Secret", category: "jeux" },
  { civilian: "Skin", undercover: "Costume", category: "jeux" },
  { civilian: "Headshot", undercover: "Critical hit", category: "jeux" },
  { civilian: "Rage quit", undercover: "AFK", category: "jeux" },
  { civilian: "Noob", undercover: "Tryhard", category: "jeux" },
  { civilian: "Clutch", undercover: "Ace", category: "jeux" },
  { civilian: "Nerf", undercover: "Buff", category: "jeux" },
  { civilian: "Lag", undercover: "Bug", category: "jeux" },
  { civilian: "Craft", undercover: "Forge", category: "jeux" },
  { civilian: "Open world", undercover: "Sandbox", category: "jeux" },

  // Célébrités / Culture — paires subtiles (même domaine, pas le même)
  { civilian: "Ballon d'Or", undercover: "Grammy", category: "celebs" },
  { civilian: "Champions League", undercover: "Super Bowl", category: "celebs" },
  { civilian: "Freestyle", undercover: "Improvisation", category: "celebs" },
  { civilian: "Feat", undercover: "Collab", category: "celebs" },
  { civilian: "Clip", undercover: "Court-métrage", category: "celebs" },
  { civilian: "Album", undercover: "Mixtape", category: "celebs" },
  { civilian: "Platine", undercover: "Or", category: "celebs" },
  { civilian: "Flow", undercover: "Groove", category: "celebs" },
  { civilian: "Beef", undercover: "Clash", category: "celebs" },
  { civilian: "Ghostwriter", undercover: "Featuring", category: "celebs" },
  { civilian: "Streaming", undercover: "Podcast", category: "celebs" },
  { civilian: "Viral", undercover: "Trending", category: "celebs" },
  { civilian: "Cancel", undercover: "Boycott", category: "celebs" },
  { civilian: "Stan", undercover: "Fan", category: "celebs" },
  { civilian: "Hype", undercover: "Buzz", category: "celebs" },

  // Memes / Internet — paires subtiles
  { civilian: "Ratio", undercover: "Flop", category: "memes" },
  { civilian: "Sigma", undercover: "Lone wolf", category: "memes" },
  { civilian: "NPC", undercover: "Figurant", category: "memes" },
  { civilian: "Ghosting", undercover: "Ignorer", category: "memes" },
  { civilian: "Flex", undercover: "Show off", category: "memes" },
  { civilian: "Cringe", undercover: "Malaise", category: "memes" },
  { civilian: "Based", undercover: "Woke", category: "memes" },
  { civilian: "Salty", undercover: "Tilté", category: "memes" },
  { civilian: "Carry", undercover: "Boost", category: "memes" },
  { civilian: "Troll", undercover: "Provocateur", category: "memes" },
];

export function getRandomWordPair(): WordPair {
  return WORD_PAIRS[Math.floor(Math.random() * WORD_PAIRS.length)];
}
