project_id = "gvslrjkliipibnvnxybw"

[functions.generate-subtitles]
verify_jwt = false

[functions.generate-quiz-question]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.generate-adaptive-music]
verify_jwt = true

[functions.refine-rhythmo-text]
verify_jwt = false

[functions.transcribe-clip]
verify_jwt = false

[functions.transcribe-clip-status]
verify_jwt = false
