// French Quiz Questions Bank - 1000+ questions
// Categories: general, anime, histoire, sport, musique, cinema, science, geographie, jeux_video, art

export interface Question {
  question: string;
  answer: string;
  options: string[];
  difficulty: 'facile' | 'moyen' | 'difficile';
}

export interface QuestionBank {
  [category: string]: Question[];
}

export const QUESTIONS_BANK: QuestionBank = {
  general: [
    // FACILE
    { question: "Quelle est la couleur du cheval blanc d'Henri IV ?", answer: "Blanc", options: ["Blanc", "Noir", "Gris", "Marron"], difficulty: "facile" },
    { question: "Combien de jours y a-t-il dans une semaine ?", answer: "7", options: ["7", "5", "6", "8"], difficulty: "facile" },
    { question: "Quelle est la langue officielle du Brésil ?", answer: "Portugais", options: ["Portugais", "Espagnol", "Anglais", "Français"], difficulty: "facile" },
    { question: "Quel animal est le roi de la jungle ?", answer: "Le lion", options: ["Le lion", "Le tigre", "L'éléphant", "Le gorille"], difficulty: "facile" },
    { question: "Combien de continents y a-t-il sur Terre ?", answer: "7", options: ["7", "5", "6", "8"], difficulty: "facile" },
    { question: "Quelle est la planète la plus proche du Soleil ?", answer: "Mercure", options: ["Mercure", "Vénus", "Mars", "Terre"], difficulty: "facile" },
    { question: "Quel est l'océan le plus grand du monde ?", answer: "Pacifique", options: ["Pacifique", "Atlantique", "Indien", "Arctique"], difficulty: "facile" },
    { question: "Combien de pattes a une araignée ?", answer: "8", options: ["8", "6", "10", "4"], difficulty: "facile" },
    { question: "Quelle est la capitale de l'Italie ?", answer: "Rome", options: ["Rome", "Milan", "Venise", "Florence"], difficulty: "facile" },
    { question: "Quel est le plus grand mammifère marin ?", answer: "La baleine bleue", options: ["La baleine bleue", "Le requin", "L'orque", "Le dauphin"], difficulty: "facile" },
    { question: "Combien de mois ont 31 jours ?", answer: "7", options: ["7", "6", "5", "4"], difficulty: "facile" },
    { question: "Quel est le symbole chimique de l'eau ?", answer: "H2O", options: ["H2O", "CO2", "O2", "NaCl"], difficulty: "facile" },
    { question: "Quelle couleur obtient-on en mélangeant bleu et jaune ?", answer: "Vert", options: ["Vert", "Orange", "Violet", "Marron"], difficulty: "facile" },
    { question: "Quel est le plus petit pays du monde ?", answer: "Vatican", options: ["Vatican", "Monaco", "San Marin", "Liechtenstein"], difficulty: "facile" },
    { question: "Combien y a-t-il de lettres dans l'alphabet français ?", answer: "26", options: ["26", "24", "28", "25"], difficulty: "facile" },
    { question: "Quel est le plus long fleuve de France ?", answer: "La Loire", options: ["La Loire", "La Seine", "Le Rhône", "La Garonne"], difficulty: "facile" },
    { question: "Quel animal produit le miel ?", answer: "L'abeille", options: ["L'abeille", "La guêpe", "Le bourdon", "Le papillon"], difficulty: "facile" },
    { question: "Combien de joueurs composent une équipe de football ?", answer: "11", options: ["11", "10", "9", "12"], difficulty: "facile" },
    { question: "Quelle est la monnaie du Japon ?", answer: "Le yen", options: ["Le yen", "Le yuan", "Le won", "Le dollar"], difficulty: "facile" },
    { question: "Quel est le plus haut sommet du monde ?", answer: "L'Everest", options: ["L'Everest", "Le K2", "Le Mont Blanc", "Le Kilimandjaro"], difficulty: "facile" },
    // MOYEN
    { question: "En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?", answer: "1969", options: ["1969", "1965", "1972", "1968"], difficulty: "moyen" },
    { question: "Qui a peint La Joconde ?", answer: "Léonard de Vinci", options: ["Léonard de Vinci", "Michel-Ange", "Raphaël", "Botticelli"], difficulty: "moyen" },
    { question: "Quel est le nom de la fusée qui a emmené Apollo 11 ?", answer: "Saturn V", options: ["Saturn V", "Apollo", "Columbia", "Falcon"], difficulty: "moyen" },
    { question: "Combien d'os possède le corps humain adulte ?", answer: "206", options: ["206", "186", "226", "196"], difficulty: "moyen" },
    { question: "Quel pays a le plus grand nombre d'habitants ?", answer: "Inde", options: ["Inde", "Chine", "États-Unis", "Indonésie"], difficulty: "moyen" },
    { question: "Quelle est la vitesse de la lumière en km/s ?", answer: "300 000 km/s", options: ["300 000 km/s", "150 000 km/s", "500 000 km/s", "200 000 km/s"], difficulty: "moyen" },
    { question: "Qui a écrit Les Misérables ?", answer: "Victor Hugo", options: ["Victor Hugo", "Émile Zola", "Honoré de Balzac", "Alexandre Dumas"], difficulty: "moyen" },
    { question: "Quelle est la capitale de l'Australie ?", answer: "Canberra", options: ["Canberra", "Sydney", "Melbourne", "Brisbane"], difficulty: "moyen" },
    { question: "En quelle année a eu lieu la Révolution française ?", answer: "1789", options: ["1789", "1792", "1776", "1799"], difficulty: "moyen" },
    { question: "Quel est l'élément chimique le plus abondant dans l'univers ?", answer: "Hydrogène", options: ["Hydrogène", "Hélium", "Oxygène", "Carbone"], difficulty: "moyen" },
    { question: "Quelle est la devise de la France ?", answer: "Liberté, Égalité, Fraternité", options: ["Liberté, Égalité, Fraternité", "Unité, Force, Progrès", "Justice, Paix, Liberté", "Honneur, Patrie, Valeur"], difficulty: "moyen" },
    { question: "Quel océan sépare l'Europe de l'Amérique ?", answer: "Atlantique", options: ["Atlantique", "Pacifique", "Indien", "Arctique"], difficulty: "moyen" },
    { question: "Qui a découvert la pénicilline ?", answer: "Alexander Fleming", options: ["Alexander Fleming", "Louis Pasteur", "Marie Curie", "Robert Koch"], difficulty: "moyen" },
    { question: "Combien de dents a un adulte ?", answer: "32", options: ["32", "28", "30", "36"], difficulty: "moyen" },
    { question: "Quel est le plus grand désert du monde ?", answer: "Antarctique", options: ["Antarctique", "Sahara", "Gobi", "Kalahari"], difficulty: "moyen" },
    { question: "Quelle est la langue la plus parlée au monde ?", answer: "Mandarin", options: ["Mandarin", "Anglais", "Espagnol", "Hindi"], difficulty: "moyen" },
    { question: "En quelle année le mur de Berlin est-il tombé ?", answer: "1989", options: ["1989", "1991", "1987", "1990"], difficulty: "moyen" },
    { question: "Quel est le symbole chimique de l'or ?", answer: "Au", options: ["Au", "Ag", "Or", "Go"], difficulty: "moyen" },
    { question: "Qui a inventé le téléphone ?", answer: "Alexander Graham Bell", options: ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"], difficulty: "moyen" },
    { question: "Quelle est la température d'ébullition de l'eau en degrés Celsius ?", answer: "100°C", options: ["100°C", "90°C", "110°C", "95°C"], difficulty: "moyen" },
    // DIFFICILE
    { question: "Quel est le nom du premier satellite artificiel lancé en 1957 ?", answer: "Spoutnik 1", options: ["Spoutnik 1", "Explorer 1", "Vanguard 1", "Luna 1"], difficulty: "difficile" },
    { question: "Combien de vertèbres possède un humain ?", answer: "33", options: ["33", "26", "28", "30"], difficulty: "difficile" },
    { question: "Quel est le plus grand lac d'eau douce du monde ?", answer: "Lac Supérieur", options: ["Lac Supérieur", "Lac Victoria", "Lac Baïkal", "Lac Michigan"], difficulty: "difficile" },
    { question: "En quelle année Christophe Colomb a-t-il découvert l'Amérique ?", answer: "1492", options: ["1492", "1498", "1488", "1502"], difficulty: "difficile" },
    { question: "Quel est le diamètre approximatif de la Terre ?", answer: "12 742 km", options: ["12 742 km", "10 000 km", "15 000 km", "8 000 km"], difficulty: "difficile" },
    { question: "Qui a formulé la théorie de la relativité ?", answer: "Albert Einstein", options: ["Albert Einstein", "Isaac Newton", "Niels Bohr", "Max Planck"], difficulty: "difficile" },
    { question: "Quelle est la plus longue guerre de l'histoire ?", answer: "Guerre de Cent Ans", options: ["Guerre de Cent Ans", "Guerre de Trente Ans", "Guerre de Sept Ans", "Guerre de Reconquista"], difficulty: "difficile" },
    { question: "Quel est le point le plus profond des océans ?", answer: "Fosse des Mariannes", options: ["Fosse des Mariannes", "Fosse de Porto Rico", "Fosse des Philippines", "Fosse de Java"], difficulty: "difficile" },
    { question: "En quelle année a été créé l'ONU ?", answer: "1945", options: ["1945", "1948", "1950", "1942"], difficulty: "difficile" },
    { question: "Quel philosophe grec a été le professeur d'Alexandre le Grand ?", answer: "Aristote", options: ["Aristote", "Platon", "Socrate", "Héraclite"], difficulty: "difficile" },
    { question: "Combien de pays composent l'Union Européenne en 2024 ?", answer: "27", options: ["27", "28", "25", "30"], difficulty: "difficile" },
    { question: "Quelle est la distance moyenne entre la Terre et la Lune ?", answer: "384 400 km", options: ["384 400 km", "300 000 km", "450 000 km", "250 000 km"], difficulty: "difficile" },
    { question: "Qui a découvert l'Amérique avant Christophe Colomb ?", answer: "Leif Erikson", options: ["Leif Erikson", "Marco Polo", "Amerigo Vespucci", "Vasco de Gama"], difficulty: "difficile" },
    { question: "Quel est le nom de la première femme dans l'espace ?", answer: "Valentina Terechkova", options: ["Valentina Terechkova", "Sally Ride", "Svetlana Savitskaya", "Peggy Whitson"], difficulty: "difficile" },
    { question: "En quelle année a été fondée Rome selon la légende ?", answer: "753 av. J.-C.", options: ["753 av. J.-C.", "800 av. J.-C.", "700 av. J.-C.", "650 av. J.-C."], difficulty: "difficile" }
  ],
  
  anime: [
    // FACILE
    { question: "Quel est le nom du héros de Dragon Ball ?", answer: "Goku", options: ["Goku", "Vegeta", "Gohan", "Piccolo"], difficulty: "facile" },
    { question: "Dans quel anime trouve-t-on un garçon pirate avec un chapeau de paille ?", answer: "One Piece", options: ["One Piece", "Naruto", "Fairy Tail", "Bleach"], difficulty: "facile" },
    { question: "Quel Pokémon est le compagnon de Sacha ?", answer: "Pikachu", options: ["Pikachu", "Évoli", "Salamèche", "Bulbizarre"], difficulty: "facile" },
    { question: "Comment s'appelle le ninja blond de Konoha ?", answer: "Naruto", options: ["Naruto", "Sasuke", "Kakashi", "Gaara"], difficulty: "facile" },
    { question: "Dans Death Note, quel est le nom du cahier mortel ?", answer: "Death Note", options: ["Death Note", "Life Book", "Shinigami Diary", "Kira's Journal"], difficulty: "facile" },
    { question: "Quel titan peut se transformer en Titan Assaillant ?", answer: "Eren", options: ["Eren", "Reiner", "Bertolt", "Annie"], difficulty: "facile" },
    { question: "Dans quel anime voit-on des chasseurs de démons avec des sabres ?", answer: "Demon Slayer", options: ["Demon Slayer", "Bleach", "Inuyasha", "Blue Exorcist"], difficulty: "facile" },
    { question: "Comment s'appelle la guilde de Natsu dans Fairy Tail ?", answer: "Fairy Tail", options: ["Fairy Tail", "Blue Pegasus", "Sabertooth", "Phantom Lord"], difficulty: "facile" },
    { question: "Quel est le nom du protagoniste de My Hero Academia ?", answer: "Izuku Midoriya", options: ["Izuku Midoriya", "Katsuki Bakugo", "Shoto Todoroki", "All Might"], difficulty: "facile" },
    { question: "Dans One Punch Man, combien de coups faut-il à Saitama pour vaincre ses ennemis ?", answer: "Un", options: ["Un", "Deux", "Trois", "Zéro"], difficulty: "facile" },
    { question: "Quel est le nom du géant de l'anime L'Attaque des Titans ?", answer: "Titan", options: ["Titan", "Géant", "Colosse", "Monstre"], difficulty: "facile" },
    { question: "Dans quel anime les personnages utilisent le Chakra ?", answer: "Naruto", options: ["Naruto", "Dragon Ball", "Bleach", "One Piece"], difficulty: "facile" },
    { question: "Quel est le rêve de Luffy dans One Piece ?", answer: "Devenir le roi des pirates", options: ["Devenir le roi des pirates", "Trouver un trésor", "Devenir marine", "Explorer le monde"], difficulty: "facile" },
    { question: "Comment s'appelle l'organisation criminelle de Naruto ?", answer: "Akatsuki", options: ["Akatsuki", "Kara", "Sound", "Anbu"], difficulty: "facile" },
    { question: "Quel est le vrai nom de Kira dans Death Note ?", answer: "Light Yagami", options: ["Light Yagami", "L Lawliet", "Misa Amane", "Near"], difficulty: "facile" },
    { question: "Dans quel anime trouve-t-on les alchimistes ?", answer: "Fullmetal Alchemist", options: ["Fullmetal Alchemist", "Fairy Tail", "Blue Exorcist", "Soul Eater"], difficulty: "facile" },
    { question: "Quel est le nom du petit renard à neuf queues de Naruto ?", answer: "Kurama", options: ["Kurama", "Kyubi", "Shukaku", "Gyuki"], difficulty: "facile" },
    { question: "Dans Tokyo Ghoul, de quoi se nourrissent les goules ?", answer: "Chair humaine", options: ["Chair humaine", "Sang", "Âmes", "Énergie"], difficulty: "facile" },
    { question: "Quel est le pouvoir de Goku ?", answer: "Ki/Énergie", options: ["Ki/Énergie", "Chakra", "Magie", "Alchimie"], difficulty: "facile" },
    { question: "Comment s'appelle le bateau de Luffy ?", answer: "Thousand Sunny", options: ["Thousand Sunny", "Going Merry", "Red Force", "Moby Dick"], difficulty: "facile" },
    // MOYEN
    { question: "Quel est le Bankai de Ichigo dans Bleach ?", answer: "Tensa Zangetsu", options: ["Tensa Zangetsu", "Senbonzakura", "Hyorinmaru", "Zabimaru"], difficulty: "moyen" },
    { question: "Dans Hunter x Hunter, quel est le nom du pouvoir spirituel ?", answer: "Nen", options: ["Nen", "Chi", "Chakra", "Reiatsu"], difficulty: "moyen" },
    { question: "Quel est le nom du robot de Evangelion Unit-01 ?", answer: "Eva-01", options: ["Eva-01", "Gundam", "Mecha", "Voltron"], difficulty: "moyen" },
    { question: "Dans Jujutsu Kaisen, qui est le roi des malédictions ?", answer: "Sukuna", options: ["Sukuna", "Gojo", "Mahito", "Jogo"], difficulty: "moyen" },
    { question: "Quel est le nom du créateur de One Piece ?", answer: "Eiichiro Oda", options: ["Eiichiro Oda", "Masashi Kishimoto", "Akira Toriyama", "Tite Kubo"], difficulty: "moyen" },
    { question: "Dans Code Geass, quel est le pouvoir de Lelouch ?", answer: "Geass", options: ["Geass", "Sharingan", "Death Note", "Nen"], difficulty: "moyen" },
    { question: "Quel anime a été créé par le studio Ghibli avec une maison volante ?", answer: "Le Château Ambulant", options: ["Le Château Ambulant", "Mon voisin Totoro", "Princesse Mononoke", "Le Voyage de Chihiro"], difficulty: "moyen" },
    { question: "Dans Steins;Gate, quel est l'objet qui permet de voyager dans le temps ?", answer: "Micro-ondes", options: ["Micro-ondes", "Téléphone", "DeLorean", "Machine"], difficulty: "moyen" },
    { question: "Quel est le nom du groupe de Rock Lee dans Naruto ?", answer: "Team Guy", options: ["Team Guy", "Team Kakashi", "Team Asuma", "Team Kurenai"], difficulty: "moyen" },
    { question: "Dans Sword Art Online, comment s'appelle le monde virtuel ?", answer: "Aincrad", options: ["Aincrad", "ALO", "GGO", "Underworld"], difficulty: "moyen" },
    { question: "Quel est le nom de l'organisation de chasseurs de démons dans Demon Slayer ?", answer: "Corps des Pourfendeurs de Démons", options: ["Corps des Pourfendeurs de Démons", "Ordre des Chasseurs", "Brigade Anti-Démons", "Escouade Lumière"], difficulty: "moyen" },
    { question: "Dans Black Clover, quel grimoire possède Asta ?", answer: "Grimoire à cinq feuilles", options: ["Grimoire à cinq feuilles", "Grimoire noir", "Grimoire du diable", "Grimoire anti-magie"], difficulty: "moyen" },
    { question: "Quel est le nom du titan originel dans L'Attaque des Titans ?", answer: "Ymir Fritz", options: ["Ymir Fritz", "Karl Fritz", "Eren Yeager", "Zeke Yeager"], difficulty: "moyen" },
    { question: "Dans Mob Psycho 100, quel est le pourcentage maximum de Mob ?", answer: "???%", options: ["???%", "100%", "1000%", "Infinity"], difficulty: "moyen" },
    { question: "Quel est le vrai nom de Killua dans Hunter x Hunter ?", answer: "Killua Zoldyck", options: ["Killua Zoldyck", "Killua Freecss", "Killua Hunter", "Killua Silva"], difficulty: "moyen" },
    { question: "Dans Re:Zero, combien de fois Subaru peut-il mourir ?", answer: "Illimité", options: ["Illimité", "3 fois", "7 fois", "Une seule"], difficulty: "moyen" },
    { question: "Quel est le nom de l'académie dans My Hero Academia ?", answer: "UA", options: ["UA", "Shiketsu", "Hero Academy", "Ketsubutsu"], difficulty: "moyen" },
    { question: "Dans Chainsaw Man, en quoi Denji peut-il se transformer ?", answer: "Homme-Tronçonneuse", options: ["Homme-Tronçonneuse", "Démon", "Diable", "Monstre"], difficulty: "moyen" },
    { question: "Quel studio a produit les films de Demon Slayer ?", answer: "Ufotable", options: ["Ufotable", "Mappa", "Wit Studio", "Bones"], difficulty: "moyen" },
    { question: "Dans JoJo's Bizarre Adventure, comment s'appelle le pouvoir spirituel ?", answer: "Stand", options: ["Stand", "Hamon", "Ripple", "Ki"], difficulty: "moyen" },
    // DIFFICILE
    { question: "Quel est le vrai nom de L dans Death Note ?", answer: "L Lawliet", options: ["L Lawliet", "Rue Ryuzaki", "Hideki Ryuga", "Watari"], difficulty: "difficile" },
    { question: "Dans Hunter x Hunter, quel est le numéro de licence de Gon ?", answer: "405", options: ["405", "404", "406", "99"], difficulty: "difficile" },
    { question: "Combien de respirations principales existe-t-il dans Demon Slayer ?", answer: "5", options: ["5", "7", "10", "3"], difficulty: "difficile" },
    { question: "Quel est le nom complet du créateur de Dragon Ball ?", answer: "Akira Toriyama", options: ["Akira Toriyama", "Akira Kurosawa", "Toriyama Sensei", "Akira Oda"], difficulty: "difficile" },
    { question: "Dans Berserk, quel est le nom de l'épée de Guts ?", answer: "Dragon Slayer", options: ["Dragon Slayer", "Buster Sword", "Dragonslayer", "Great Sword"], difficulty: "difficile" },
    { question: "Quel est le nombre total de respirations dans Demon Slayer (dérivées comprises) ?", answer: "14", options: ["14", "12", "16", "10"], difficulty: "difficile" },
    { question: "Dans One Piece, quel est le vrai nom de Gold Roger ?", answer: "Gol D. Roger", options: ["Gol D. Roger", "Gold Roger", "Gol Roger", "Roger D. Gol"], difficulty: "difficile" },
    { question: "Combien de Homonculus y a-t-il dans Fullmetal Alchemist ?", answer: "7", options: ["7", "8", "6", "9"], difficulty: "difficile" },
    { question: "Dans Neon Genesis Evangelion, quelle année marque le Second Impact ?", answer: "2000", options: ["2000", "2001", "1999", "2015"], difficulty: "difficile" },
    { question: "Quel est le vrai nom de Tobi dans Naruto ?", answer: "Obito Uchiha", options: ["Obito Uchiha", "Madara Uchiha", "Zetsu", "Kakashi"], difficulty: "difficile" },
    { question: "Dans Made in Abyss, quelle est la profondeur de la 6ème couche ?", answer: "13 000 mètres", options: ["13 000 mètres", "7 000 mètres", "15 500 mètres", "20 000 mètres"], difficulty: "difficile" },
    { question: "Combien de titans changeants existent dans L'Attaque des Titans ?", answer: "9", options: ["9", "7", "13", "10"], difficulty: "difficile" },
    { question: "Quel est le nom japonais de Dragon Ball Z ?", answer: "ドラゴンボールZ", options: ["ドラゴンボールZ", "ドラゴンボール", "ドラゴンボールGT", "ドラゴンボール超"], difficulty: "difficile" },
    { question: "Dans Naruto, combien y a-t-il de bijuu ?", answer: "9", options: ["9", "7", "10", "8"], difficulty: "difficile" },
    { question: "Quel est le nom du 4ème Hokage ?", answer: "Minato Namikaze", options: ["Minato Namikaze", "Hiruzen Sarutobi", "Tobirama Senju", "Hashirama Senju"], difficulty: "difficile" }
  ],

  histoire: [
    // FACILE  
    { question: "Qui était le premier président des États-Unis ?", answer: "George Washington", options: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"], difficulty: "facile" },
    { question: "En quelle année la Seconde Guerre mondiale a-t-elle pris fin ?", answer: "1945", options: ["1945", "1944", "1946", "1943"], difficulty: "facile" },
    { question: "Qui a construit la Tour Eiffel ?", answer: "Gustave Eiffel", options: ["Gustave Eiffel", "Auguste Rodin", "Le Baron Haussmann", "Napoléon III"], difficulty: "facile" },
    { question: "Quel empereur romain a brûlé Rome ?", answer: "Néron", options: ["Néron", "Caligula", "César", "Auguste"], difficulty: "facile" },
    { question: "En quelle année Christophe Colomb a-t-il découvert l'Amérique ?", answer: "1492", options: ["1492", "1500", "1488", "1510"], difficulty: "facile" },
    { question: "Qui était surnommé le Roi-Soleil ?", answer: "Louis XIV", options: ["Louis XIV", "Louis XVI", "Louis XV", "Napoléon"], difficulty: "facile" },
    { question: "Quelle reine d'Égypte était célèbre pour sa beauté ?", answer: "Cléopâtre", options: ["Cléopâtre", "Néfertiti", "Hatchepsout", "Isis"], difficulty: "facile" },
    { question: "Quel pays a construit le mur de Berlin ?", answer: "Allemagne de l'Est", options: ["Allemagne de l'Est", "URSS", "Allemagne de l'Ouest", "États-Unis"], difficulty: "facile" },
    { question: "Qui a écrit la Déclaration d'Indépendance américaine ?", answer: "Thomas Jefferson", options: ["Thomas Jefferson", "George Washington", "Benjamin Franklin", "John Adams"], difficulty: "facile" },
    { question: "Quel conquérant a créé le plus grand empire de l'histoire ?", answer: "Gengis Khan", options: ["Gengis Khan", "Alexandre le Grand", "Napoléon", "César"], difficulty: "facile" },
    { question: "En quelle année a eu lieu la prise de la Bastille ?", answer: "1789", options: ["1789", "1790", "1788", "1791"], difficulty: "facile" },
    { question: "Qui a découvert l'Amérique avant Colomb ?", answer: "Les Vikings", options: ["Les Vikings", "Les Chinois", "Les Portugais", "Les Phéniciens"], difficulty: "facile" },
    { question: "Quel pharaon est connu pour sa tombe découverte intacte ?", answer: "Toutânkhamon", options: ["Toutânkhamon", "Ramsès II", "Khéops", "Akhenaton"], difficulty: "facile" },
    { question: "Quelle civilisation a inventé l'écriture cunéiforme ?", answer: "Sumériens", options: ["Sumériens", "Égyptiens", "Babyloniens", "Assyriens"], difficulty: "facile" },
    { question: "Qui était le leader de la Révolution russe de 1917 ?", answer: "Lénine", options: ["Lénine", "Staline", "Trotsky", "Nicolas II"], difficulty: "facile" },
    { question: "Quel événement a déclenché la Première Guerre mondiale ?", answer: "Assassinat de François-Ferdinand", options: ["Assassinat de François-Ferdinand", "Invasion de la Pologne", "Traité de Versailles", "Révolution russe"], difficulty: "facile" },
    { question: "Quelle dynastie a régné le plus longtemps en France ?", answer: "Capétiens", options: ["Capétiens", "Bourbons", "Carolingiens", "Mérovingiens"], difficulty: "facile" },
    { question: "Qui a unifié l'Italie ?", answer: "Garibaldi", options: ["Garibaldi", "Mussolini", "Victor-Emmanuel II", "Cavour"], difficulty: "facile" },
    { question: "En quelle année l'esclavage a-t-il été aboli en France ?", answer: "1848", options: ["1848", "1789", "1830", "1870"], difficulty: "facile" },
    { question: "Qui était le premier empereur de Chine ?", answer: "Qin Shi Huang", options: ["Qin Shi Huang", "Liu Bang", "Confucius", "Sun Tzu"], difficulty: "facile" },
    // MOYEN
    { question: "En quelle année le Titanic a-t-il coulé ?", answer: "1912", options: ["1912", "1910", "1915", "1908"], difficulty: "moyen" },
    { question: "Qui a été le dernier pharaon d'Égypte ?", answer: "Cléopâtre VII", options: ["Cléopâtre VII", "Ptolémée XV", "Ramsès XI", "Néfertiti"], difficulty: "moyen" },
    { question: "Quelle bataille a mis fin à Napoléon ?", answer: "Waterloo", options: ["Waterloo", "Austerlitz", "Trafalgar", "Borodino"], difficulty: "moyen" },
    { question: "En quelle année l'Empire romain d'Occident est-il tombé ?", answer: "476", options: ["476", "410", "395", "500"], difficulty: "moyen" },
    { question: "Qui a signé l'Édit de Nantes ?", answer: "Henri IV", options: ["Henri IV", "Louis XIII", "Louis XIV", "François Ier"], difficulty: "moyen" },
    { question: "Quelle guerre a duré de 1337 à 1453 ?", answer: "Guerre de Cent Ans", options: ["Guerre de Cent Ans", "Guerre de Trente Ans", "Croisades", "Guerre des Roses"], difficulty: "moyen" },
    { question: "En quelle année Jules César a-t-il été assassiné ?", answer: "44 av. J.-C.", options: ["44 av. J.-C.", "27 av. J.-C.", "31 av. J.-C.", "49 av. J.-C."], difficulty: "moyen" },
    { question: "Qui a été couronné empereur en 800 ?", answer: "Charlemagne", options: ["Charlemagne", "Pépin le Bref", "Louis le Pieux", "Charles Martel"], difficulty: "moyen" },
    { question: "Quelle civilisation a construit Machu Picchu ?", answer: "Incas", options: ["Incas", "Mayas", "Aztèques", "Olmèques"], difficulty: "moyen" },
    { question: "En quelle année a eu lieu la chute de Constantinople ?", answer: "1453", options: ["1453", "1204", "1492", "1517"], difficulty: "moyen" },
    { question: "Qui a fondé l'Empire mongol ?", answer: "Gengis Khan", options: ["Gengis Khan", "Kubilai Khan", "Tamerlan", "Attila"], difficulty: "moyen" },
    { question: "Quelle révolution a eu lieu en 1917 en Russie ?", answer: "Révolution d'Octobre", options: ["Révolution d'Octobre", "Révolution de Février", "Révolution bolchévique", "Révolution rouge"], difficulty: "moyen" },
    { question: "En quelle année la peste noire a-t-elle frappé l'Europe ?", answer: "1347", options: ["1347", "1350", "1340", "1360"], difficulty: "moyen" },
    { question: "Qui a peint le plafond de la Chapelle Sixtine ?", answer: "Michel-Ange", options: ["Michel-Ange", "Léonard de Vinci", "Raphaël", "Botticelli"], difficulty: "moyen" },
    { question: "Quelle bataille a vu la défaite de Vercingétorix ?", answer: "Alésia", options: ["Alésia", "Gergovie", "Bibracte", "Lugdunum"], difficulty: "moyen" },
    { question: "En quelle année Jeanne d'Arc a-t-elle été brûlée ?", answer: "1431", options: ["1431", "1429", "1435", "1420"], difficulty: "moyen" },
    { question: "Qui a été le premier homme à faire le tour du monde ?", answer: "Magellan", options: ["Magellan", "Christophe Colomb", "Vasco de Gama", "Drake"], difficulty: "moyen" },
    { question: "Quelle civilisation a inventé la démocratie ?", answer: "Grecs", options: ["Grecs", "Romains", "Égyptiens", "Perses"], difficulty: "moyen" },
    { question: "En quelle année Louis XVI a-t-il été exécuté ?", answer: "1793", options: ["1793", "1789", "1792", "1794"], difficulty: "moyen" },
    { question: "Qui a découvert la pénicilline ?", answer: "Alexander Fleming", options: ["Alexander Fleming", "Louis Pasteur", "Robert Koch", "Joseph Lister"], difficulty: "moyen" },
    // DIFFICILE
    { question: "En quelle année le traité de Westphalie a-t-il été signé ?", answer: "1648", options: ["1648", "1618", "1659", "1635"], difficulty: "difficile" },
    { question: "Qui était le premier empereur du Saint-Empire ?", answer: "Otton Ier", options: ["Otton Ier", "Charlemagne", "Frédéric Barberousse", "Henri IV"], difficulty: "difficile" },
    { question: "Quelle bataille a marqué la fin de la domination viking en Angleterre ?", answer: "Stamford Bridge", options: ["Stamford Bridge", "Hastings", "Edington", "Maldon"], difficulty: "difficile" },
    { question: "En quelle année le Code Justinien a-t-il été promulgué ?", answer: "529", options: ["529", "476", "565", "395"], difficulty: "difficile" },
    { question: "Qui a fondé la dynastie des Han en Chine ?", answer: "Liu Bang", options: ["Liu Bang", "Qin Shi Huang", "Wu Zetian", "Cao Cao"], difficulty: "difficile" },
    { question: "Quelle était la capitale de l'Empire byzantin ?", answer: "Constantinople", options: ["Constantinople", "Rome", "Athènes", "Alexandrie"], difficulty: "difficile" },
    { question: "En quelle année la Grande Charte a-t-elle été signée ?", answer: "1215", options: ["1215", "1066", "1295", "1189"], difficulty: "difficile" },
    { question: "Qui a été le dernier empereur romain d'Occident ?", answer: "Romulus Augustule", options: ["Romulus Augustule", "Néron", "Constantin", "Théodose"], difficulty: "difficile" },
    { question: "Quelle dynastie a précédé les Capétiens en France ?", answer: "Carolingiens", options: ["Carolingiens", "Mérovingiens", "Valois", "Bourbons"], difficulty: "difficile" },
    { question: "En quelle année le schisme d'Orient a-t-il eu lieu ?", answer: "1054", options: ["1054", "1095", "1204", "800"], difficulty: "difficile" },
    { question: "Qui a été le premier calife de l'Islam ?", answer: "Abou Bakr", options: ["Abou Bakr", "Omar", "Ali", "Uthman"], difficulty: "difficile" },
    { question: "Quelle bataille a mis fin à l'Empire perse achéménide ?", answer: "Gaugamèles", options: ["Gaugamèles", "Issos", "Marathon", "Salamine"], difficulty: "difficile" },
    { question: "En quelle année Carthage a-t-elle été détruite ?", answer: "146 av. J.-C.", options: ["146 av. J.-C.", "202 av. J.-C.", "264 av. J.-C.", "133 av. J.-C."], difficulty: "difficile" },
    { question: "Qui a été le fondateur de l'Empire ottoman ?", answer: "Osman Ier", options: ["Osman Ier", "Mehmed II", "Soliman", "Murad Ier"], difficulty: "difficile" },
    { question: "Quelle était la monnaie de l'Empire romain ?", answer: "Aureus", options: ["Aureus", "Denarius", "Sesterce", "As"], difficulty: "difficile" }
  ],

  sport: [
    // FACILE
    { question: "Combien de joueurs y a-t-il dans une équipe de football ?", answer: "11", options: ["11", "10", "9", "12"], difficulty: "facile" },
    { question: "Quel pays a gagné la Coupe du Monde 2022 ?", answer: "Argentine", options: ["Argentine", "France", "Brésil", "Croatie"], difficulty: "facile" },
    { question: "Dans quel sport utilise-t-on une raquette et un volant ?", answer: "Badminton", options: ["Badminton", "Tennis", "Squash", "Ping-pong"], difficulty: "facile" },
    { question: "Combien de points vaut un touchdown au football américain ?", answer: "6", options: ["6", "7", "3", "4"], difficulty: "facile" },
    { question: "Quel est le sport national du Japon ?", answer: "Sumo", options: ["Sumo", "Judo", "Karaté", "Baseball"], difficulty: "facile" },
    { question: "Combien de sets faut-il gagner pour remporter un match de tennis (Grand Chelem hommes) ?", answer: "3", options: ["3", "2", "4", "5"], difficulty: "facile" },
    { question: "Quel joueur de basketball est surnommé 'Air' ?", answer: "Michael Jordan", options: ["Michael Jordan", "LeBron James", "Kobe Bryant", "Magic Johnson"], difficulty: "facile" },
    { question: "Dans quel pays les Jeux Olympiques modernes ont-ils été créés ?", answer: "Grèce", options: ["Grèce", "France", "États-Unis", "Angleterre"], difficulty: "facile" },
    { question: "Quel est le nombre maximum de joueurs dans une équipe de rugby à XV ?", answer: "15", options: ["15", "13", "11", "17"], difficulty: "facile" },
    { question: "Quel footballeur portugais joue pour Al-Nassr ?", answer: "Cristiano Ronaldo", options: ["Cristiano Ronaldo", "Neymar", "Messi", "Mbappé"], difficulty: "facile" },
    { question: "Combien de temps dure un match de football ?", answer: "90 minutes", options: ["90 minutes", "60 minutes", "120 minutes", "80 minutes"], difficulty: "facile" },
    { question: "Dans quel sport trouve-t-on le Tour de France ?", answer: "Cyclisme", options: ["Cyclisme", "Course à pied", "Natation", "Ski"], difficulty: "facile" },
    { question: "Quel pays a remporté le plus de Coupes du Monde de football ?", answer: "Brésil", options: ["Brésil", "Allemagne", "Italie", "Argentine"], difficulty: "facile" },
    { question: "Combien de trous y a-t-il dans un parcours de golf standard ?", answer: "18", options: ["18", "9", "12", "21"], difficulty: "facile" },
    { question: "Quel sport se pratique sur glace avec un palet ?", answer: "Hockey", options: ["Hockey", "Curling", "Patinage", "Bobsleigh"], difficulty: "facile" },
    { question: "Qui est le meilleur buteur de l'histoire de la Ligue des Champions ?", answer: "Cristiano Ronaldo", options: ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], difficulty: "facile" },
    { question: "Combien de joueurs composent une équipe de basketball ?", answer: "5", options: ["5", "6", "7", "4"], difficulty: "facile" },
    { question: "Quel pays accueillera les JO 2024 ?", answer: "France", options: ["France", "États-Unis", "Japon", "Australie"], difficulty: "facile" },
    { question: "Dans quel sport utilise-t-on un ballon ovale ?", answer: "Rugby", options: ["Rugby", "Football américain", "Les deux", "Handball"], difficulty: "facile" },
    { question: "Qui a remporté le plus de Ballons d'Or ?", answer: "Lionel Messi", options: ["Lionel Messi", "Cristiano Ronaldo", "Johan Cruyff", "Michel Platini"], difficulty: "facile" },
    // MOYEN
    { question: "En quelle année la France a-t-elle gagné sa première Coupe du Monde ?", answer: "1998", options: ["1998", "2006", "2018", "1984"], difficulty: "moyen" },
    { question: "Quel joueur détient le record du 100m ?", answer: "Usain Bolt", options: ["Usain Bolt", "Carl Lewis", "Tyson Gay", "Justin Gatlin"], difficulty: "moyen" },
    { question: "Combien de Grand Chelem Rafael Nadal a-t-il remportés ?", answer: "22", options: ["22", "20", "21", "23"], difficulty: "moyen" },
    { question: "Quel boxeur était surnommé 'The Greatest' ?", answer: "Muhammad Ali", options: ["Muhammad Ali", "Mike Tyson", "Sugar Ray Leonard", "Joe Frazier"], difficulty: "moyen" },
    { question: "Dans quel stade joue le FC Barcelone ?", answer: "Camp Nou", options: ["Camp Nou", "Santiago Bernabéu", "Wanda Metropolitano", "San Siro"], difficulty: "moyen" },
    { question: "Quel nageur a gagné le plus de médailles olympiques ?", answer: "Michael Phelps", options: ["Michael Phelps", "Ryan Lochte", "Ian Thorpe", "Mark Spitz"], difficulty: "moyen" },
    { question: "En quelle année Zinedine Zidane a-t-il pris sa retraite ?", answer: "2006", options: ["2006", "2004", "2008", "2002"], difficulty: "moyen" },
    { question: "Quel est le record du monde du marathon ?", answer: "2h00'35\"", options: ["2h00'35\"", "2h01'09\"", "2h02'57\"", "1h59'40\""], difficulty: "moyen" },
    { question: "Combien de championnats du monde Max Verstappen a-t-il remportés jusqu'en 2023 ?", answer: "3", options: ["3", "2", "4", "1"], difficulty: "moyen" },
    { question: "Quel joueur de tennis a remporté le plus de titres en Grand Chelem ?", answer: "Novak Djokovic", options: ["Novak Djokovic", "Roger Federer", "Rafael Nadal", "Pete Sampras"], difficulty: "moyen" },
    { question: "Dans quelle ville se trouve le stade Old Trafford ?", answer: "Manchester", options: ["Manchester", "Liverpool", "Londres", "Birmingham"], difficulty: "moyen" },
    { question: "Quel pays a inventé le basketball ?", answer: "États-Unis", options: ["États-Unis", "Canada", "France", "Angleterre"], difficulty: "moyen" },
    { question: "Combien de fois l'Allemagne a-t-elle gagné la Coupe du Monde ?", answer: "4", options: ["4", "3", "5", "2"], difficulty: "moyen" },
    { question: "Quel pilote F1 a le plus de victoires en Grand Prix ?", answer: "Lewis Hamilton", options: ["Lewis Hamilton", "Michael Schumacher", "Sebastian Vettel", "Ayrton Senna"], difficulty: "moyen" },
    { question: "En quelle année ont eu lieu les premiers Jeux Olympiques modernes ?", answer: "1896", options: ["1896", "1900", "1892", "1904"], difficulty: "moyen" },
    { question: "Quel joueur de football a marqué le plus de buts en une année civile ?", answer: "Lionel Messi", options: ["Lionel Messi", "Cristiano Ronaldo", "Gerd Müller", "Robert Lewandowski"], difficulty: "moyen" },
    { question: "Combien de fois Roger Federer a-t-il remporté Wimbledon ?", answer: "8", options: ["8", "7", "9", "6"], difficulty: "moyen" },
    { question: "Quel club a remporté le plus de Ligues des Champions ?", answer: "Real Madrid", options: ["Real Madrid", "AC Milan", "Bayern Munich", "Liverpool"], difficulty: "moyen" },
    { question: "Dans quel sport Kylian Mbappé évolue-t-il ?", answer: "Football", options: ["Football", "Basketball", "Rugby", "Handball"], difficulty: "moyen" },
    { question: "Quel est le surnom de l'équipe de France de football ?", answer: "Les Bleus", options: ["Les Bleus", "Les Tricolores", "Les Coqs", "Les Gaulois"], difficulty: "moyen" },
    // DIFFICILE
    { question: "En quelle année Pelé a-t-il pris sa retraite internationale ?", answer: "1971", options: ["1971", "1974", "1970", "1977"], difficulty: "difficile" },
    { question: "Quel est le record de buts en Ligue des Champions en une saison ?", answer: "17", options: ["17", "15", "14", "16"], difficulty: "difficile" },
    { question: "Combien de Coupes du Monde Miroslav Klose a-t-il disputées ?", answer: "4", options: ["4", "3", "5", "2"], difficulty: "difficile" },
    { question: "Quel athlète a remporté 9 médailles d'or olympiques en athlétisme ?", answer: "Carl Lewis", options: ["Carl Lewis", "Usain Bolt", "Jesse Owens", "Paavo Nurmi"], difficulty: "difficile" },
    { question: "En quelle année le PSG a-t-il été fondé ?", answer: "1970", options: ["1970", "1968", "1972", "1975"], difficulty: "difficile" },
    { question: "Quel joueur de cricket détient le record de runs en Test ?", answer: "Sachin Tendulkar", options: ["Sachin Tendulkar", "Ricky Ponting", "Jacques Kallis", "Rahul Dravid"], difficulty: "difficile" },
    { question: "Combien de points Wilt Chamberlain a-t-il marqués en un seul match NBA ?", answer: "100", options: ["100", "82", "75", "91"], difficulty: "difficile" },
    { question: "Quel est le nombre exact de médailles olympiques de Michael Phelps ?", answer: "28", options: ["28", "23", "25", "30"], difficulty: "difficile" },
    { question: "En quelle année Diego Maradona a-t-il marqué la 'Main de Dieu' ?", answer: "1986", options: ["1986", "1982", "1990", "1994"], difficulty: "difficile" },
    { question: "Quel cycliste a remporté le plus de Tours de France ?", answer: "Jacques Anquetil/Eddy Merckx/Bernard Hinault/Miguel Indurain", options: ["Tous les 4 avec 5 victoires", "Lance Armstrong avec 7", "Chris Froome avec 6", "Jan Ullrich avec 4"], difficulty: "difficile" },
    { question: "Combien de Grands Chelems Bill Russell a-t-il remportés ?", answer: "11", options: ["11", "9", "13", "8"], difficulty: "difficile" },
    { question: "Quel est le record de home runs en une saison MLB ?", answer: "73", options: ["73", "70", "74", "61"], difficulty: "difficile" },
    { question: "En quelle année le premier Super Bowl a-t-il eu lieu ?", answer: "1967", options: ["1967", "1965", "1970", "1960"], difficulty: "difficile" },
    { question: "Quel golfeur a remporté le plus de Majeurs ?", answer: "Jack Nicklaus", options: ["Jack Nicklaus", "Tiger Woods", "Arnold Palmer", "Gary Player"], difficulty: "difficile" },
    { question: "Combien de secondes a duré le combat de boxe le plus court de l'histoire ?", answer: "4 secondes", options: ["4 secondes", "7 secondes", "10 secondes", "15 secondes"], difficulty: "difficile" }
  ],

  musique: [
    // FACILE
    { question: "Qui a chanté 'Thriller' ?", answer: "Michael Jackson", options: ["Michael Jackson", "Prince", "Whitney Houston", "Stevie Wonder"], difficulty: "facile" },
    { question: "Quel groupe a chanté 'Bohemian Rhapsody' ?", answer: "Queen", options: ["Queen", "The Beatles", "Led Zeppelin", "Pink Floyd"], difficulty: "facile" },
    { question: "Combien de membres y avait-il dans les Beatles ?", answer: "4", options: ["4", "3", "5", "6"], difficulty: "facile" },
    { question: "Qui est la 'Reine de la Pop' ?", answer: "Madonna", options: ["Madonna", "Lady Gaga", "Britney Spears", "Beyoncé"], difficulty: "facile" },
    { question: "Quel rappeur français a chanté 'Bande organisée' ?", answer: "Jul", options: ["Jul", "PNL", "Booba", "Kaaris"], difficulty: "facile" },
    { question: "Quelle chanteuse barbadienne a chanté 'Umbrella' ?", answer: "Rihanna", options: ["Rihanna", "Beyoncé", "Nicki Minaj", "Cardi B"], difficulty: "facile" },
    { question: "Quel est le prénom d'Elvis... ?", answer: "Presley", options: ["Presley", "Jackson", "Williams", "Johnson"], difficulty: "facile" },
    { question: "Qui a chanté 'Je t'aime... moi non plus' avec Jane Birkin ?", answer: "Serge Gainsbourg", options: ["Serge Gainsbourg", "Johnny Hallyday", "Charles Aznavour", "Jacques Brel"], difficulty: "facile" },
    { question: "Quel groupe a chanté 'Smells Like Teen Spirit' ?", answer: "Nirvana", options: ["Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains"], difficulty: "facile" },
    { question: "Quelle chanteuse américaine est surnommée 'Queen B' ?", answer: "Beyoncé", options: ["Beyoncé", "Rihanna", "Lady Gaga", "Taylor Swift"], difficulty: "facile" },
    { question: "Quel rappeur américain est marié à Kim Kardashian (anciennement) ?", answer: "Kanye West", options: ["Kanye West", "Jay-Z", "Drake", "Travis Scott"], difficulty: "facile" },
    { question: "Qui a chanté 'La vie en rose' ?", answer: "Édith Piaf", options: ["Édith Piaf", "Dalida", "Barbara", "Françoise Hardy"], difficulty: "facile" },
    { question: "Quel groupe britannique a chanté 'Yellow' ?", answer: "Coldplay", options: ["Coldplay", "Oasis", "Radiohead", "Muse"], difficulty: "facile" },
    { question: "Qui est le 'King of Pop' ?", answer: "Michael Jackson", options: ["Michael Jackson", "Elvis Presley", "Prince", "Bruno Mars"], difficulty: "facile" },
    { question: "Quel duo français a chanté 'Get Lucky' ?", answer: "Daft Punk", options: ["Daft Punk", "Justice", "Air", "Cassius"], difficulty: "facile" },
    { question: "Quelle chanteuse a chanté 'Hello' en 2015 ?", answer: "Adele", options: ["Adele", "Taylor Swift", "Sia", "Sam Smith"], difficulty: "facile" },
    { question: "Quel rappeur est surnommé 'Slim Shady' ?", answer: "Eminem", options: ["Eminem", "50 Cent", "Dr. Dre", "Snoop Dogg"], difficulty: "facile" },
    { question: "Qui a chanté 'Shape of You' ?", answer: "Ed Sheeran", options: ["Ed Sheeran", "Justin Bieber", "Shawn Mendes", "Sam Smith"], difficulty: "facile" },
    { question: "Quel groupe coréen est surnommé BTS ?", answer: "Bangtan Boys", options: ["Bangtan Boys", "Beyond The Scene", "Big Time Stars", "Best Top Stars"], difficulty: "facile" },
    { question: "Qui a composé 'Pour Élise' ?", answer: "Beethoven", options: ["Beethoven", "Mozart", "Bach", "Chopin"], difficulty: "facile" },
    // MOYEN
    { question: "En quelle année Michael Jackson est-il décédé ?", answer: "2009", options: ["2009", "2011", "2007", "2010"], difficulty: "moyen" },
    { question: "Quel est le vrai nom de Lady Gaga ?", answer: "Stefani Germanotta", options: ["Stefani Germanotta", "Elizabeth Grant", "Robyn Fenty", "Alicia Moore"], difficulty: "moyen" },
    { question: "Combien d'albums studio les Beatles ont-ils sortis ?", answer: "13", options: ["13", "12", "15", "10"], difficulty: "moyen" },
    { question: "Quel rappeur français a fondé le label 92i ?", answer: "Booba", options: ["Booba", "Kaaris", "Rohff", "La Fouine"], difficulty: "moyen" },
    { question: "En quelle année 'Nevermind' de Nirvana est-il sorti ?", answer: "1991", options: ["1991", "1989", "1993", "1990"], difficulty: "moyen" },
    { question: "Quel est le nom du premier album de Stromae ?", answer: "Cheese", options: ["Cheese", "Racine Carrée", "Multitude", "Silence"], difficulty: "moyen" },
    { question: "Qui a produit l'album 'Yeezus' de Kanye West ?", answer: "Kanye West", options: ["Kanye West", "Rick Rubin", "Pharrell Williams", "Dr. Dre"], difficulty: "moyen" },
    { question: "Quel groupe a vendu le plus d'albums dans l'histoire ?", answer: "The Beatles", options: ["The Beatles", "Led Zeppelin", "Pink Floyd", "Eagles"], difficulty: "moyen" },
    { question: "En quelle année Daft Punk s'est-il séparé ?", answer: "2021", options: ["2021", "2020", "2019", "2022"], difficulty: "moyen" },
    { question: "Quel est le vrai nom du rappeur PNL (Ademo) ?", answer: "Tarik Andrieu", options: ["Tarik Andrieu", "Nabil Andrieu", "Karim Andrieu", "Yassine Andrieu"], difficulty: "moyen" },
    { question: "Combien de Grammys Michael Jackson a-t-il remportés ?", answer: "13", options: ["13", "15", "10", "17"], difficulty: "moyen" },
    { question: "Quel album de Pink Floyd présente un prisme sur la pochette ?", answer: "The Dark Side of the Moon", options: ["The Dark Side of the Moon", "The Wall", "Wish You Were Here", "Animals"], difficulty: "moyen" },
    { question: "En quelle année Johnny Hallyday est-il décédé ?", answer: "2017", options: ["2017", "2018", "2016", "2019"], difficulty: "moyen" },
    { question: "Quel est le single le plus vendu de tous les temps ?", answer: "White Christmas", options: ["White Christmas", "Candle in the Wind", "Thriller", "I Will Always Love You"], difficulty: "moyen" },
    { question: "Qui a écrit la chanson 'Imagine' ?", answer: "John Lennon", options: ["John Lennon", "Paul McCartney", "George Harrison", "Ringo Starr"], difficulty: "moyen" },
    { question: "Quel rappeur a lancé le label 'Shady Records' ?", answer: "Eminem", options: ["Eminem", "50 Cent", "Dr. Dre", "Jay-Z"], difficulty: "moyen" },
    { question: "En quelle année le premier album de NTM est-il sorti ?", answer: "1991", options: ["1991", "1990", "1992", "1993"], difficulty: "moyen" },
    { question: "Quel groupe a chanté 'Paranoid' en 1970 ?", answer: "Black Sabbath", options: ["Black Sabbath", "Led Zeppelin", "Deep Purple", "Iron Maiden"], difficulty: "moyen" },
    { question: "Combien d'albums studio Taylor Swift a-t-elle sortis jusqu'en 2023 ?", answer: "10", options: ["10", "8", "12", "9"], difficulty: "moyen" },
    { question: "Quel DJ français a produit 'Titanium' ?", answer: "David Guetta", options: ["David Guetta", "Martin Solveig", "Bob Sinclar", "Joachim Garraud"], difficulty: "moyen" },
    // DIFFICILE
    { question: "En quelle année est sorti le premier album de Radiohead 'Pablo Honey' ?", answer: "1993", options: ["1993", "1992", "1994", "1995"], difficulty: "difficile" },
    { question: "Quel est le nom du batteur de Nirvana ?", answer: "Dave Grohl", options: ["Dave Grohl", "Chad Channing", "Pat Smear", "Krist Novoselic"], difficulty: "difficile" },
    { question: "Combien d'albums studio Prince a-t-il officiellement sortis ?", answer: "39", options: ["39", "35", "42", "30"], difficulty: "difficile" },
    { question: "Quel est le vrai nom de The Weeknd ?", answer: "Abel Tesfaye", options: ["Abel Tesfaye", "Abel Makkonen", "Tesfaye Abel", "Dawit Tesfaye"], difficulty: "difficile" },
    { question: "En quelle année le festival de Woodstock a-t-il eu lieu ?", answer: "1969", options: ["1969", "1967", "1970", "1968"], difficulty: "difficile" },
    { question: "Quel compositeur classique est devenu sourd ?", answer: "Beethoven", options: ["Beethoven", "Mozart", "Bach", "Haydn"], difficulty: "difficile" },
    { question: "Combien de symphonies Beethoven a-t-il composées ?", answer: "9", options: ["9", "7", "10", "12"], difficulty: "difficile" },
    { question: "Quel album de Kendrick Lamar a remporté le Pulitzer ?", answer: "DAMN.", options: ["DAMN.", "To Pimp a Butterfly", "good kid, m.A.A.d city", "Mr. Morale & The Big Steppers"], difficulty: "difficile" },
    { question: "En quelle année Joy Division s'est-il formé ?", answer: "1976", options: ["1976", "1978", "1975", "1977"], difficulty: "difficile" },
    { question: "Quel est le nom complet du rappeur IAM (Akhenaton) ?", answer: "Philippe Fragione", options: ["Philippe Fragione", "Pascal Perez", "Éric Mazel", "Geoffroy Mussard"], difficulty: "difficile" },
    { question: "Combien de Brit Awards Adele a-t-elle remportés ?", answer: "12", options: ["12", "9", "15", "10"], difficulty: "difficile" },
    { question: "En quelle année le groupe Kraftwerk a-t-il été formé ?", answer: "1970", options: ["1970", "1968", "1972", "1974"], difficulty: "difficile" },
    { question: "Quel est le nom du premier single de Madonna ?", answer: "Everybody", options: ["Everybody", "Holiday", "Lucky Star", "Borderline"], difficulty: "difficile" },
    { question: "Combien de numéros 1 au Billboard Hot 100 les Beatles ont-ils eus ?", answer: "20", options: ["20", "17", "23", "15"], difficulty: "difficile" },
    { question: "Quel producteur est connu sous le nom de 'Dr. Dre' ?", answer: "Andre Young", options: ["Andre Young", "Andre Johnson", "Andrew Williams", "Andre Jackson"], difficulty: "difficile" }
  ],

  cinema: [
    // FACILE
    { question: "Qui joue Iron Man dans les films Marvel ?", answer: "Robert Downey Jr.", options: ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"], difficulty: "facile" },
    { question: "Quel film a pour personnage principal un lion nommé Simba ?", answer: "Le Roi Lion", options: ["Le Roi Lion", "Madagascar", "Zootopie", "Bambi"], difficulty: "facile" },
    { question: "Qui a réalisé Titanic ?", answer: "James Cameron", options: ["James Cameron", "Steven Spielberg", "Christopher Nolan", "Martin Scorsese"], difficulty: "facile" },
    { question: "Dans quel film trouve-t-on Darth Vader ?", answer: "Star Wars", options: ["Star Wars", "Star Trek", "Alien", "Blade Runner"], difficulty: "facile" },
    { question: "Quel acteur joue Jack Sparrow ?", answer: "Johnny Depp", options: ["Johnny Depp", "Orlando Bloom", "Geoffrey Rush", "Javier Bardem"], difficulty: "facile" },
    { question: "Combien de films Harry Potter y a-t-il ?", answer: "8", options: ["8", "7", "9", "6"], difficulty: "facile" },
    { question: "Qui joue le Joker dans The Dark Knight ?", answer: "Heath Ledger", options: ["Heath Ledger", "Jack Nicholson", "Jared Leto", "Joaquin Phoenix"], difficulty: "facile" },
    { question: "Quel studio a créé Toy Story ?", answer: "Pixar", options: ["Pixar", "DreamWorks", "Disney", "Illumination"], difficulty: "facile" },
    { question: "Dans quel film Leonardo DiCaprio est-il sur un bateau qui coule ?", answer: "Titanic", options: ["Titanic", "The Revenant", "Inception", "Shutter Island"], difficulty: "facile" },
    { question: "Quel acteur joue James Bond le plus souvent ?", answer: "Roger Moore", options: ["Roger Moore", "Sean Connery", "Daniel Craig", "Pierce Brosnan"], difficulty: "facile" },
    { question: "Qui a réalisé Jurassic Park ?", answer: "Steven Spielberg", options: ["Steven Spielberg", "James Cameron", "George Lucas", "Ridley Scott"], difficulty: "facile" },
    { question: "Dans quel film trouve-t-on le personnage de Forrest Gump ?", answer: "Forrest Gump", options: ["Forrest Gump", "Cast Away", "The Green Mile", "Philadelphia"], difficulty: "facile" },
    { question: "Qui joue Thor dans les films Marvel ?", answer: "Chris Hemsworth", options: ["Chris Hemsworth", "Chris Evans", "Chris Pratt", "Tom Hiddleston"], difficulty: "facile" },
    { question: "Quel film Disney met en scène une sirène ?", answer: "La Petite Sirène", options: ["La Petite Sirène", "Pocahontas", "Moana", "Cendrillon"], difficulty: "facile" },
    { question: "Dans quel film trouve-t-on E.T. ?", answer: "E.T. l'extra-terrestre", options: ["E.T. l'extra-terrestre", "Alien", "Close Encounters", "Independence Day"], difficulty: "facile" },
    { question: "Qui joue Neo dans Matrix ?", answer: "Keanu Reeves", options: ["Keanu Reeves", "Brad Pitt", "Nicolas Cage", "Tom Cruise"], difficulty: "facile" },
    { question: "Quel film de Pixar met en scène des émotions ?", answer: "Vice-Versa", options: ["Vice-Versa", "Soul", "Coco", "Ratatouille"], difficulty: "facile" },
    { question: "Qui joue Wolverine dans X-Men ?", answer: "Hugh Jackman", options: ["Hugh Jackman", "Patrick Stewart", "Ian McKellen", "James McAvoy"], difficulty: "facile" },
    { question: "Dans quel film trouve-t-on le personnage de Shrek ?", answer: "Shrek", options: ["Shrek", "L'Âne", "Madagascar", "Dragons"], difficulty: "facile" },
    { question: "Qui a réalisé Avatar ?", answer: "James Cameron", options: ["James Cameron", "Steven Spielberg", "Peter Jackson", "Christopher Nolan"], difficulty: "facile" },
    // MOYEN
    { question: "En quelle année est sorti le premier film Star Wars ?", answer: "1977", options: ["1977", "1980", "1983", "1975"], difficulty: "moyen" },
    { question: "Quel film a remporté l'Oscar du meilleur film en 2020 ?", answer: "Parasite", options: ["Parasite", "1917", "Joker", "Once Upon a Time in Hollywood"], difficulty: "moyen" },
    { question: "Combien de films composent la trilogie du Seigneur des Anneaux ?", answer: "3", options: ["3", "4", "2", "5"], difficulty: "moyen" },
    { question: "Qui a réalisé Pulp Fiction ?", answer: "Quentin Tarantino", options: ["Quentin Tarantino", "Martin Scorsese", "Guy Ritchie", "David Fincher"], difficulty: "moyen" },
    { question: "Quel acteur a joué dans Fight Club et Se7en ?", answer: "Brad Pitt", options: ["Brad Pitt", "Edward Norton", "Morgan Freeman", "Kevin Spacey"], difficulty: "moyen" },
    { question: "En quelle année Titanic est-il sorti ?", answer: "1997", options: ["1997", "1998", "1996", "1999"], difficulty: "moyen" },
    { question: "Quel film détient le record du box-office mondial ?", answer: "Avatar", options: ["Avatar", "Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"], difficulty: "moyen" },
    { question: "Qui joue le rôle principal dans Interstellar ?", answer: "Matthew McConaughey", options: ["Matthew McConaughey", "Christian Bale", "Leonardo DiCaprio", "Brad Pitt"], difficulty: "moyen" },
    { question: "Dans quel film trouve-t-on le personnage de Tyler Durden ?", answer: "Fight Club", options: ["Fight Club", "Se7en", "The Game", "Zodiac"], difficulty: "moyen" },
    { question: "Qui a réalisé Inception ?", answer: "Christopher Nolan", options: ["Christopher Nolan", "Denis Villeneuve", "David Fincher", "Ridley Scott"], difficulty: "moyen" },
    { question: "Quel acteur joue le Parrain ?", answer: "Marlon Brando", options: ["Marlon Brando", "Al Pacino", "Robert De Niro", "Joe Pesci"], difficulty: "moyen" },
    { question: "Combien de films Avengers y a-t-il ?", answer: "4", options: ["4", "3", "5", "6"], difficulty: "moyen" },
    { question: "Qui joue Hermione dans Harry Potter ?", answer: "Emma Watson", options: ["Emma Watson", "Emma Roberts", "Emma Stone", "Bonnie Wright"], difficulty: "moyen" },
    { question: "En quelle année le premier film Marvel (MCU) est-il sorti ?", answer: "2008", options: ["2008", "2010", "2005", "2012"], difficulty: "moyen" },
    { question: "Quel réalisateur est connu pour les films Kill Bill ?", answer: "Quentin Tarantino", options: ["Quentin Tarantino", "Robert Rodriguez", "Zack Snyder", "Guy Ritchie"], difficulty: "moyen" },
    { question: "Dans quel film trouve-t-on la phrase 'I'll be back' ?", answer: "Terminator", options: ["Terminator", "Predator", "RoboCop", "Total Recall"], difficulty: "moyen" },
    { question: "Qui joue Katniss dans Hunger Games ?", answer: "Jennifer Lawrence", options: ["Jennifer Lawrence", "Emma Stone", "Kristen Stewart", "Scarlett Johansson"], difficulty: "moyen" },
    { question: "Quel film de Pixar met en scène des voitures ?", answer: "Cars", options: ["Cars", "Turbo", "Planes", "Hot Wheels"], difficulty: "moyen" },
    { question: "En quelle année Le Parrain est-il sorti ?", answer: "1972", options: ["1972", "1974", "1970", "1975"], difficulty: "moyen" },
    { question: "Qui a réalisé les films Batman The Dark Knight ?", answer: "Christopher Nolan", options: ["Christopher Nolan", "Tim Burton", "Zack Snyder", "Matt Reeves"], difficulty: "moyen" },
    // DIFFICILE
    { question: "En quelle année Citizen Kane est-il sorti ?", answer: "1941", options: ["1941", "1939", "1944", "1946"], difficulty: "difficile" },
    { question: "Quel acteur a remporté le plus d'Oscars du meilleur acteur ?", answer: "Daniel Day-Lewis", options: ["Daniel Day-Lewis", "Jack Nicholson", "Marlon Brando", "Tom Hanks"], difficulty: "difficile" },
    { question: "Combien de films Alfred Hitchcock a-t-il réalisés ?", answer: "53", options: ["53", "45", "60", "38"], difficulty: "difficile" },
    { question: "Quel film a le plus long générique de fin ?", answer: "Matrix Resurrections", options: ["Matrix Resurrections", "Avengers: Endgame", "Return of the King", "Avatar 2"], difficulty: "difficile" },
    { question: "En quelle année le premier film parlant (The Jazz Singer) est-il sorti ?", answer: "1927", options: ["1927", "1929", "1925", "1930"], difficulty: "difficile" },
    { question: "Quel réalisateur a le plus de nominations aux Oscars ?", answer: "Walt Disney", options: ["Walt Disney", "Steven Spielberg", "William Wyler", "John Ford"], difficulty: "difficile" },
    { question: "Combien de temps dure le film le plus long de tous les temps (Logistics) ?", answer: "857 heures", options: ["857 heures", "720 heures", "240 heures", "96 heures"], difficulty: "difficile" },
    { question: "En quelle année le premier film en couleur a-t-il été réalisé ?", answer: "1935", options: ["1935", "1939", "1941", "1932"], difficulty: "difficile" },
    { question: "Quel film a remporté le plus d'Oscars en une seule cérémonie ?", answer: "Ben-Hur/Titanic/Le Seigneur des Anneaux", options: ["11 Oscars (les 3)", "12 Oscars", "10 Oscars", "13 Oscars"], difficulty: "difficile" },
    { question: "Qui a inventé le cinématographe ?", answer: "Les frères Lumière", options: ["Les frères Lumière", "Thomas Edison", "Georges Méliès", "Eadweard Muybridge"], difficulty: "difficile" },
    { question: "Quel est le premier film d'animation des studios Disney ?", answer: "Blanche-Neige et les Sept Nains", options: ["Blanche-Neige et les Sept Nains", "Fantasia", "Pinocchio", "Dumbo"], difficulty: "difficile" },
    { question: "Combien de films Stanley Kubrick a-t-il réalisés ?", answer: "13", options: ["13", "15", "10", "17"], difficulty: "difficile" },
    { question: "En quelle année Metropolis de Fritz Lang est-il sorti ?", answer: "1927", options: ["1927", "1925", "1930", "1922"], difficulty: "difficile" },
    { question: "Quel film noir a été réalisé par Billy Wilder en 1944 ?", answer: "Double Indemnity", options: ["Double Indemnity", "Sunset Boulevard", "The Lost Weekend", "Some Like It Hot"], difficulty: "difficile" },
    { question: "Combien de récompenses les films du Seigneur des Anneaux ont-ils reçues au total ?", answer: "17 Oscars", options: ["17 Oscars", "15 Oscars", "20 Oscars", "12 Oscars"], difficulty: "difficile" }
  ],

  science: [
    // FACILE
    { question: "Quel gaz respirons-nous principalement ?", answer: "Oxygène", options: ["Oxygène", "Azote", "Hydrogène", "Carbone"], difficulty: "facile" },
    { question: "Combien de planètes y a-t-il dans notre système solaire ?", answer: "8", options: ["8", "9", "7", "10"], difficulty: "facile" },
    { question: "Quelle est la formule chimique de l'eau ?", answer: "H2O", options: ["H2O", "CO2", "NaCl", "O2"], difficulty: "facile" },
    { question: "Quel est l'organe qui pompe le sang ?", answer: "Le cœur", options: ["Le cœur", "Les poumons", "Le foie", "Les reins"], difficulty: "facile" },
    { question: "Quelle planète est surnommée la planète rouge ?", answer: "Mars", options: ["Mars", "Jupiter", "Vénus", "Mercure"], difficulty: "facile" },
    { question: "Combien de pattes a un insecte ?", answer: "6", options: ["6", "8", "4", "10"], difficulty: "facile" },
    { question: "Quel est le plus grand organe du corps humain ?", answer: "La peau", options: ["La peau", "Le foie", "Les intestins", "Les poumons"], difficulty: "facile" },
    { question: "Quelle est la force qui nous maintient au sol ?", answer: "La gravité", options: ["La gravité", "Le magnétisme", "L'électricité", "La friction"], difficulty: "facile" },
    { question: "Quel scientifique a découvert la gravité ?", answer: "Newton", options: ["Newton", "Einstein", "Galilée", "Copernic"], difficulty: "facile" },
    { question: "Combien de temps met la Terre pour faire le tour du Soleil ?", answer: "1 an", options: ["1 an", "1 mois", "1 jour", "1 semaine"], difficulty: "facile" },
    { question: "Quel est le métal le plus conducteur d'électricité ?", answer: "Argent", options: ["Argent", "Cuivre", "Or", "Aluminium"], difficulty: "facile" },
    { question: "Combien d'os y a-t-il dans le corps humain adulte ?", answer: "206", options: ["206", "186", "226", "196"], difficulty: "facile" },
    { question: "Quelle est la température du corps humain normal ?", answer: "37°C", options: ["37°C", "36°C", "38°C", "35°C"], difficulty: "facile" },
    { question: "Quel est le plus grand mammifère terrestre ?", answer: "L'éléphant", options: ["L'éléphant", "La girafe", "Le rhinocéros", "L'hippopotame"], difficulty: "facile" },
    { question: "Combien de dents de lait un enfant possède-t-il ?", answer: "20", options: ["20", "24", "28", "16"], difficulty: "facile" },
    { question: "Quelle vitamine le soleil nous apporte-t-il ?", answer: "Vitamine D", options: ["Vitamine D", "Vitamine C", "Vitamine A", "Vitamine B"], difficulty: "facile" },
    { question: "Quel est l'animal le plus rapide du monde ?", answer: "Le guépard", options: ["Le guépard", "Le faucon", "Le lion", "L'antilope"], difficulty: "facile" },
    { question: "De quoi sont principalement faites les étoiles ?", answer: "Hydrogène", options: ["Hydrogène", "Hélium", "Carbone", "Oxygène"], difficulty: "facile" },
    { question: "Quel est le symbole chimique de l'or ?", answer: "Au", options: ["Au", "Ag", "Or", "Go"], difficulty: "facile" },
    { question: "Combien de poumons avons-nous ?", answer: "2", options: ["2", "1", "3", "4"], difficulty: "facile" },
    // MOYEN
    { question: "Quelle est la vitesse de la lumière ?", answer: "300 000 km/s", options: ["300 000 km/s", "150 000 km/s", "500 000 km/s", "200 000 km/s"], difficulty: "moyen" },
    { question: "Quel est l'élément chimique le plus abondant dans l'univers ?", answer: "Hydrogène", options: ["Hydrogène", "Hélium", "Oxygène", "Carbone"], difficulty: "moyen" },
    { question: "Combien de chromosomes possède un être humain ?", answer: "46", options: ["46", "44", "48", "42"], difficulty: "moyen" },
    { question: "Quelle est la plus grande cellule du corps humain ?", answer: "L'ovule", options: ["L'ovule", "Le neurone", "Le globule rouge", "La cellule musculaire"], difficulty: "moyen" },
    { question: "Quel scientifique a formulé la théorie de la relativité ?", answer: "Albert Einstein", options: ["Albert Einstein", "Isaac Newton", "Niels Bohr", "Max Planck"], difficulty: "moyen" },
    { question: "Quelle est la température du zéro absolu ?", answer: "-273,15°C", options: ["-273,15°C", "-100°C", "-459°C", "0°C"], difficulty: "moyen" },
    { question: "Combien de litres de sang y a-t-il dans le corps humain ?", answer: "5 litres", options: ["5 litres", "3 litres", "7 litres", "10 litres"], difficulty: "moyen" },
    { question: "Quelle est la planète la plus chaude du système solaire ?", answer: "Vénus", options: ["Vénus", "Mercure", "Mars", "Jupiter"], difficulty: "moyen" },
    { question: "Combien de neurones possède le cerveau humain ?", answer: "86 milliards", options: ["86 milliards", "10 milliards", "100 milliards", "1 milliard"], difficulty: "moyen" },
    { question: "Quel est le pH de l'eau pure ?", answer: "7", options: ["7", "0", "14", "1"], difficulty: "moyen" },
    { question: "Quelle est la durée de vie moyenne d'un globule rouge ?", answer: "120 jours", options: ["120 jours", "30 jours", "1 an", "7 jours"], difficulty: "moyen" },
    { question: "Quel est le nom de notre galaxie ?", answer: "Voie lactée", options: ["Voie lactée", "Andromède", "Centaurus A", "Messier 87"], difficulty: "moyen" },
    { question: "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", answer: "8 minutes", options: ["8 minutes", "1 seconde", "1 minute", "24 heures"], difficulty: "moyen" },
    { question: "Quelle est la molécule de base de l'ADN ?", answer: "Nucléotide", options: ["Nucléotide", "Acide aminé", "Protéine", "Enzyme"], difficulty: "moyen" },
    { question: "Quel est l'os le plus long du corps humain ?", answer: "Le fémur", options: ["Le fémur", "Le tibia", "L'humérus", "Le radius"], difficulty: "moyen" },
    { question: "Quelle est la fréquence cardiaque moyenne au repos ?", answer: "60-100 bpm", options: ["60-100 bpm", "40-60 bpm", "100-120 bpm", "20-40 bpm"], difficulty: "moyen" },
    { question: "Combien de groupes sanguins principaux existe-t-il ?", answer: "4", options: ["4", "3", "8", "6"], difficulty: "moyen" },
    { question: "Quel est le muscle le plus puissant du corps humain ?", answer: "Le masséter", options: ["Le masséter", "Le quadriceps", "Le cœur", "Le biceps"], difficulty: "moyen" },
    { question: "Quelle est la distance entre la Terre et la Lune ?", answer: "384 400 km", options: ["384 400 km", "150 000 km", "500 000 km", "250 000 km"], difficulty: "moyen" },
    { question: "Combien de paires de côtes avons-nous ?", answer: "12", options: ["12", "10", "14", "8"], difficulty: "moyen" },
    // DIFFICILE
    { question: "Quel est le nombre d'Avogadro ?", answer: "6,022 × 10²³", options: ["6,022 × 10²³", "3,14159", "2,718", "1,602 × 10⁻¹⁹"], difficulty: "difficile" },
    { question: "Quelle est la constante de Planck ?", answer: "6,626 × 10⁻³⁴ J·s", options: ["6,626 × 10⁻³⁴ J·s", "3 × 10⁸ m/s", "9,8 m/s²", "6,674 × 10⁻¹¹"], difficulty: "difficile" },
    { question: "Combien de quarks y a-t-il ?", answer: "6", options: ["6", "4", "8", "3"], difficulty: "difficile" },
    { question: "Quelle est la masse du Soleil ?", answer: "1,989 × 10³⁰ kg", options: ["1,989 × 10³⁰ kg", "5,972 × 10²⁴ kg", "7,348 × 10²² kg", "6,39 × 10²³ kg"], difficulty: "difficile" },
    { question: "Quel est l'élément le plus dense ?", answer: "Osmium", options: ["Osmium", "Plomb", "Or", "Uranium"], difficulty: "difficile" },
    { question: "Combien de bits y a-t-il dans un octet ?", answer: "8", options: ["8", "16", "4", "2"], difficulty: "difficile" },
    { question: "Quelle est la durée d'une année-lumière ?", answer: "Distance, pas temps", options: ["Distance, pas temps", "1 an", "365 jours", "100 ans"], difficulty: "difficile" },
    { question: "Quel est le nom du premier antibiotique découvert ?", answer: "Pénicilline", options: ["Pénicilline", "Streptomycine", "Tétracycline", "Amoxicilline"], difficulty: "difficile" },
    { question: "Combien d'électrons peut contenir la première couche électronique ?", answer: "2", options: ["2", "8", "18", "1"], difficulty: "difficile" },
    { question: "Quelle est la température à la surface du Soleil ?", answer: "5 500°C", options: ["5 500°C", "15 000°C", "1 000°C", "10 000°C"], difficulty: "difficile" },
    { question: "Quel est le rayon de la Terre ?", answer: "6 371 km", options: ["6 371 km", "12 742 km", "40 000 km", "3 959 km"], difficulty: "difficile" },
    { question: "Combien de paires de bases l'ADN humain contient-il ?", answer: "3 milliards", options: ["3 milliards", "1 million", "100 millions", "10 milliards"], difficulty: "difficile" },
    { question: "Quelle est la masse d'un proton ?", answer: "1,673 × 10⁻²⁷ kg", options: ["1,673 × 10⁻²⁷ kg", "9,109 × 10⁻³¹ kg", "1,675 × 10⁻²⁷ kg", "1 × 10⁻³⁰ kg"], difficulty: "difficile" },
    { question: "Quel est le nombre de dimensions dans la théorie des cordes ?", answer: "10 ou 11", options: ["10 ou 11", "4", "26", "5"], difficulty: "difficile" },
    { question: "Quelle est la température au centre du Soleil ?", answer: "15 millions °C", options: ["15 millions °C", "1 million °C", "100 millions °C", "5 500°C"], difficulty: "difficile" }
  ],

  geographie: [
    // FACILE
    { question: "Quelle est la capitale de la France ?", answer: "Paris", options: ["Paris", "Lyon", "Marseille", "Bordeaux"], difficulty: "facile" },
    { question: "Quel est le plus grand pays du monde ?", answer: "Russie", options: ["Russie", "Canada", "Chine", "États-Unis"], difficulty: "facile" },
    { question: "Sur quel continent se trouve l'Égypte ?", answer: "Afrique", options: ["Afrique", "Asie", "Europe", "Moyen-Orient"], difficulty: "facile" },
    { question: "Quelle est la capitale du Japon ?", answer: "Tokyo", options: ["Tokyo", "Osaka", "Kyoto", "Hiroshima"], difficulty: "facile" },
    { question: "Quel océan sépare l'Europe de l'Amérique ?", answer: "Atlantique", options: ["Atlantique", "Pacifique", "Indien", "Arctique"], difficulty: "facile" },
    { question: "Quelle est la capitale de l'Espagne ?", answer: "Madrid", options: ["Madrid", "Barcelone", "Séville", "Valence"], difficulty: "facile" },
    { question: "Combien de continents y a-t-il ?", answer: "7", options: ["7", "5", "6", "8"], difficulty: "facile" },
    { question: "Quel pays a la forme d'une botte ?", answer: "Italie", options: ["Italie", "Grèce", "Espagne", "Portugal"], difficulty: "facile" },
    { question: "Quelle est la capitale du Royaume-Uni ?", answer: "Londres", options: ["Londres", "Manchester", "Liverpool", "Birmingham"], difficulty: "facile" },
    { question: "Quel est le plus long fleuve du monde ?", answer: "Le Nil", options: ["Le Nil", "L'Amazone", "Le Mississippi", "Le Yangtsé"], difficulty: "facile" },
    { question: "Quelle est la capitale de l'Allemagne ?", answer: "Berlin", options: ["Berlin", "Munich", "Francfort", "Hambourg"], difficulty: "facile" },
    { question: "Sur quel continent se trouve le Brésil ?", answer: "Amérique du Sud", options: ["Amérique du Sud", "Afrique", "Amérique du Nord", "Europe"], difficulty: "facile" },
    { question: "Quelle mer borde la France au sud ?", answer: "Méditerranée", options: ["Méditerranée", "Atlantique", "Manche", "Mer du Nord"], difficulty: "facile" },
    { question: "Quelle est la capitale de la Chine ?", answer: "Pékin", options: ["Pékin", "Shanghai", "Hong Kong", "Canton"], difficulty: "facile" },
    { question: "Quel pays est surnommé le pays du Soleil Levant ?", answer: "Japon", options: ["Japon", "Chine", "Corée", "Thaïlande"], difficulty: "facile" },
    { question: "Quelle est la capitale des États-Unis ?", answer: "Washington D.C.", options: ["Washington D.C.", "New York", "Los Angeles", "Chicago"], difficulty: "facile" },
    { question: "Quel désert est le plus grand du monde ?", answer: "Antarctique", options: ["Antarctique", "Sahara", "Gobi", "Kalahari"], difficulty: "facile" },
    { question: "Quelle est la capitale de l'Inde ?", answer: "New Delhi", options: ["New Delhi", "Mumbai", "Calcutta", "Bangalore"], difficulty: "facile" },
    { question: "Quel pays a le plus d'habitants ?", answer: "Inde", options: ["Inde", "Chine", "États-Unis", "Indonésie"], difficulty: "facile" },
    { question: "Quelle est la capitale du Canada ?", answer: "Ottawa", options: ["Ottawa", "Toronto", "Montréal", "Vancouver"], difficulty: "facile" },
    // MOYEN
    { question: "Quelle est la capitale de l'Australie ?", answer: "Canberra", options: ["Canberra", "Sydney", "Melbourne", "Brisbane"], difficulty: "moyen" },
    { question: "Quel pays traverse l'équateur en Amérique du Sud ?", answer: "Équateur", options: ["Équateur", "Pérou", "Colombie", "Brésil"], difficulty: "moyen" },
    { question: "Quelle est la plus haute montagne d'Europe ?", answer: "Mont Elbrouz", options: ["Mont Elbrouz", "Mont Blanc", "Cervin", "Mont Rose"], difficulty: "moyen" },
    { question: "Combien de pays composent l'Union Européenne en 2024 ?", answer: "27", options: ["27", "28", "25", "30"], difficulty: "moyen" },
    { question: "Quelle est la capitale de la Turquie ?", answer: "Ankara", options: ["Ankara", "Istanbul", "Izmir", "Antalya"], difficulty: "moyen" },
    { question: "Quel détroit sépare l'Europe de l'Afrique ?", answer: "Gibraltar", options: ["Gibraltar", "Bosphore", "Dardanelles", "Magellan"], difficulty: "moyen" },
    { question: "Quelle est la capitale du Maroc ?", answer: "Rabat", options: ["Rabat", "Casablanca", "Marrakech", "Fès"], difficulty: "moyen" },
    { question: "Quel est le plus petit pays d'Afrique ?", answer: "Seychelles", options: ["Seychelles", "Gambie", "Cap-Vert", "Comores"], difficulty: "moyen" },
    { question: "Combien d'États composent les États-Unis ?", answer: "50", options: ["50", "52", "48", "51"], difficulty: "moyen" },
    { question: "Quelle est la capitale de l'Afrique du Sud ?", answer: "Pretoria", options: ["Pretoria", "Le Cap", "Johannesburg", "Durban"], difficulty: "moyen" },
    { question: "Quel pays est traversé par le Mékong ?", answer: "Vietnam", options: ["Vietnam", "Chine", "Thaïlande", "Cambodge"], difficulty: "moyen" },
    { question: "Quelle est la capitale de l'Argentine ?", answer: "Buenos Aires", options: ["Buenos Aires", "Santiago", "Montevideo", "Lima"], difficulty: "moyen" },
    { question: "Quel est le plus grand lac d'Afrique ?", answer: "Lac Victoria", options: ["Lac Victoria", "Lac Tanganyika", "Lac Malawi", "Lac Tchad"], difficulty: "moyen" },
    { question: "Quelle est la capitale de la Pologne ?", answer: "Varsovie", options: ["Varsovie", "Cracovie", "Gdańsk", "Wrocław"], difficulty: "moyen" },
    { question: "Combien de fuseaux horaires la Russie possède-t-elle ?", answer: "11", options: ["11", "9", "7", "13"], difficulty: "moyen" },
    { question: "Quelle est la capitale de la Norvège ?", answer: "Oslo", options: ["Oslo", "Stockholm", "Copenhague", "Helsinki"], difficulty: "moyen" },
    { question: "Quel fleuve traverse Le Caire ?", answer: "Le Nil", options: ["Le Nil", "L'Euphrate", "Le Tigre", "Le Jourdain"], difficulty: "moyen" },
    { question: "Quelle est la capitale du Vietnam ?", answer: "Hanoï", options: ["Hanoï", "Hô Chi Minh-Ville", "Da Nang", "Hué"], difficulty: "moyen" },
    { question: "Quel pays a le plus de frontières terrestres ?", answer: "Chine/Russie", options: ["Chine/Russie (14)", "Brésil (10)", "Allemagne (9)", "France (11)"], difficulty: "moyen" },
    { question: "Quelle est la capitale de la Colombie ?", answer: "Bogota", options: ["Bogota", "Medellín", "Cali", "Carthagène"], difficulty: "moyen" },
    // DIFFICILE
    { question: "Quelle est la capitale du Myanmar ?", answer: "Naypyidaw", options: ["Naypyidaw", "Rangoun", "Mandalay", "Bago"], difficulty: "difficile" },
    { question: "Combien de pays enclavés y a-t-il en Afrique ?", answer: "16", options: ["16", "12", "20", "14"], difficulty: "difficile" },
    { question: "Quelle est la capitale du Bhoutan ?", answer: "Thimphou", options: ["Thimphou", "Paro", "Punakha", "Wangdue"], difficulty: "difficile" },
    { question: "Quel est le point le plus bas de la Terre ?", answer: "Mer Morte", options: ["Mer Morte", "Fosse des Mariannes", "Lac Baïkal", "Vallée de la Mort"], difficulty: "difficile" },
    { question: "Quelle est la capitale du Kazakhstan ?", answer: "Astana", options: ["Astana", "Almaty", "Karaganda", "Chymkent"], difficulty: "difficile" },
    { question: "Combien d'îles composent l'archipel des Philippines ?", answer: "7 641", options: ["7 641", "5 000", "10 000", "3 000"], difficulty: "difficile" },
    { question: "Quelle est la capitale de la Moldavie ?", answer: "Chișinău", options: ["Chișinău", "Tiraspol", "Bălți", "Comrat"], difficulty: "difficile" },
    { question: "Quel est le plus long mur du monde ?", answer: "Grande Muraille de Chine", options: ["Grande Muraille de Chine", "Mur de Berlin", "Mur d'Hadrien", "Mur des Lamentations"], difficulty: "difficile" },
    { question: "Quelle est la capitale du Sri Lanka ?", answer: "Sri Jayawardenepura Kotte", options: ["Sri Jayawardenepura Kotte", "Colombo", "Kandy", "Galle"], difficulty: "difficile" },
    { question: "Combien de pays africains ont l'océan Atlantique comme frontière ?", answer: "23", options: ["23", "20", "18", "25"], difficulty: "difficile" },
    { question: "Quelle est la capitale du Malawi ?", answer: "Lilongwe", options: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba"], difficulty: "difficile" },
    { question: "Quel est le plus haut volcan actif du monde ?", answer: "Ojos del Salado", options: ["Ojos del Salado", "Mont Erebus", "Cotopaxi", "Kilimandjaro"], difficulty: "difficile" },
    { question: "Quelle est la capitale du Brunei ?", answer: "Bandar Seri Begawan", options: ["Bandar Seri Begawan", "Kuala Belait", "Tutong", "Seria"], difficulty: "difficile" },
    { question: "Combien de pays n'ont pas d'armée officielle ?", answer: "Plus de 20", options: ["Plus de 20", "5", "10", "15"], difficulty: "difficile" },
    { question: "Quelle est la capitale de l'Érythrée ?", answer: "Asmara", options: ["Asmara", "Massawa", "Keren", "Assab"], difficulty: "difficile" }
  ],

  jeux_video: [
    // FACILE
    { question: "Dans quel jeu trouve-t-on Mario ?", answer: "Super Mario Bros", options: ["Super Mario Bros", "Sonic", "Zelda", "Metroid"], difficulty: "facile" },
    { question: "Quel est le jeu vidéo le plus vendu de tous les temps ?", answer: "Minecraft", options: ["Minecraft", "GTA V", "Tetris", "Wii Sports"], difficulty: "facile" },
    { question: "Dans quel jeu construit-on avec des blocs ?", answer: "Minecraft", options: ["Minecraft", "Roblox", "Lego Worlds", "Terraria"], difficulty: "facile" },
    { question: "Quel personnage est le rival de Mario ?", answer: "Sonic", options: ["Sonic", "Bowser", "Donkey Kong", "Wario"], difficulty: "facile" },
    { question: "Dans quel jeu trouve-t-on des Pokémon ?", answer: "Pokémon", options: ["Pokémon", "Digimon", "Yu-Gi-Oh", "Monster Hunter"], difficulty: "facile" },
    { question: "Quelle console Nintendo est portable ?", answer: "Switch", options: ["Switch", "Wii", "GameCube", "N64"], difficulty: "facile" },
    { question: "Dans quel jeu de battle royale saute-t-on d'un bus volant ?", answer: "Fortnite", options: ["Fortnite", "PUBG", "Apex Legends", "Warzone"], difficulty: "facile" },
    { question: "Quel plombier porte une casquette rouge ?", answer: "Mario", options: ["Mario", "Luigi", "Wario", "Waluigi"], difficulty: "facile" },
    { question: "Dans quel jeu conduit-on des voitures de course avec des personnages Nintendo ?", answer: "Mario Kart", options: ["Mario Kart", "Need for Speed", "Gran Turismo", "Forza"], difficulty: "facile" },
    { question: "Quelle entreprise a créé PlayStation ?", answer: "Sony", options: ["Sony", "Microsoft", "Nintendo", "Sega"], difficulty: "facile" },
    { question: "Dans quel jeu trouve-t-on Link ?", answer: "Zelda", options: ["Zelda", "Final Fantasy", "Dragon Quest", "Fire Emblem"], difficulty: "facile" },
    { question: "Quel jeu de foot est développé par EA Sports ?", answer: "FIFA/EA FC", options: ["FIFA/EA FC", "PES", "Football Manager", "Rocket League"], difficulty: "facile" },
    { question: "Dans quel jeu tire-t-on sur des terroristes ou contre-terroristes ?", answer: "Counter-Strike", options: ["Counter-Strike", "Call of Duty", "Rainbow Six", "Valorant"], difficulty: "facile" },
    { question: "Quelle est la couleur de Pikachu ?", answer: "Jaune", options: ["Jaune", "Rouge", "Bleu", "Vert"], difficulty: "facile" },
    { question: "Dans quel jeu gère-t-on une ville ?", answer: "SimCity/Cities Skylines", options: ["SimCity/Cities Skylines", "Age of Empires", "Civilization", "Anno"], difficulty: "facile" },
    { question: "Quel personnage de Fortnite fait des danses célèbres ?", answer: "Tous les personnages", options: ["Tous les personnages", "Jonesy", "Peely", "Midas"], difficulty: "facile" },
    { question: "Dans quel jeu trouve-t-on des Creepers ?", answer: "Minecraft", options: ["Minecraft", "Terraria", "Don't Starve", "Rust"], difficulty: "facile" },
    { question: "Quelle console Microsoft a le Game Pass ?", answer: "Xbox", options: ["Xbox", "PlayStation", "Switch", "PC"], difficulty: "facile" },
    { question: "Dans quel jeu catch-t-on des créatures avec des Poké Balls ?", answer: "Pokémon", options: ["Pokémon", "Yokai Watch", "Digimon", "Temtem"], difficulty: "facile" },
    { question: "Quel jeu de rythme utilise une guitare en plastique ?", answer: "Guitar Hero", options: ["Guitar Hero", "Rock Band", "Just Dance", "Beat Saber"], difficulty: "facile" },
    // MOYEN
    { question: "En quelle année Minecraft est-il sorti officiellement ?", answer: "2011", options: ["2011", "2009", "2010", "2012"], difficulty: "moyen" },
    { question: "Quel est le vrai nom de Master Chief ?", answer: "John-117", options: ["John-117", "James-115", "Jack-120", "Jake-118"], difficulty: "moyen" },
    { question: "Dans quel jeu trouve-t-on la ville de Los Santos ?", answer: "GTA V", options: ["GTA V", "GTA IV", "Saints Row", "Watch Dogs"], difficulty: "moyen" },
    { question: "Quelle entreprise a créé Final Fantasy ?", answer: "Square Enix", options: ["Square Enix", "Capcom", "Konami", "Bandai Namco"], difficulty: "moyen" },
    { question: "En quelle année la première PlayStation est-elle sortie ?", answer: "1994", options: ["1994", "1995", "1993", "1996"], difficulty: "moyen" },
    { question: "Quel est le nom du héros de God of War ?", answer: "Kratos", options: ["Kratos", "Atreus", "Zeus", "Baldur"], difficulty: "moyen" },
    { question: "Dans quel jeu trouve-t-on le personnage de Cloud Strife ?", answer: "Final Fantasy VII", options: ["Final Fantasy VII", "Final Fantasy X", "Kingdom Hearts", "Final Fantasy XV"], difficulty: "moyen" },
    { question: "Quelle est la console portable de Sony ?", answer: "PSP/PS Vita", options: ["PSP/PS Vita", "Switch Lite", "3DS", "Game Boy"], difficulty: "moyen" },
    { question: "En quelle année World of Warcraft est-il sorti ?", answer: "2004", options: ["2004", "2005", "2003", "2006"], difficulty: "moyen" },
    { question: "Quel jeu a popularisé le genre battle royale ?", answer: "PUBG", options: ["PUBG", "Fortnite", "H1Z1", "DayZ"], difficulty: "moyen" },
    { question: "Dans quel jeu trouve-t-on la faction des Covenant ?", answer: "Halo", options: ["Halo", "Destiny", "Gears of War", "Mass Effect"], difficulty: "moyen" },
    { question: "Quelle est la durée d'une partie de League of Legends en moyenne ?", answer: "30-40 minutes", options: ["30-40 minutes", "15-20 minutes", "60 minutes", "10 minutes"], difficulty: "moyen" },
    { question: "En quelle année Fortnite Battle Royale est-il sorti ?", answer: "2017", options: ["2017", "2018", "2016", "2019"], difficulty: "moyen" },
    { question: "Quel personnage est le méchant principal de Zelda ?", answer: "Ganondorf", options: ["Ganondorf", "Bowser", "Ridley", "Andross"], difficulty: "moyen" },
    { question: "Dans quel jeu trouve-t-on Solid Snake ?", answer: "Metal Gear Solid", options: ["Metal Gear Solid", "Splinter Cell", "Hitman", "Deus Ex"], difficulty: "moyen" },
    { question: "Combien de champions y a-t-il dans League of Legends (approximativement) ?", answer: "160+", options: ["160+", "100", "120", "200"], difficulty: "moyen" },
    { question: "Quel studio a créé Dark Souls ?", answer: "FromSoftware", options: ["FromSoftware", "Capcom", "Konami", "Bandai Namco"], difficulty: "moyen" },
    { question: "En quelle année la Nintendo Switch est-elle sortie ?", answer: "2017", options: ["2017", "2018", "2016", "2019"], difficulty: "moyen" },
    { question: "Quel est le nom de la monnaie dans Fortnite ?", answer: "V-Bucks", options: ["V-Bucks", "Robux", "Coins", "Credits"], difficulty: "moyen" },
    { question: "Dans quel jeu trouve-t-on les Gardiens ?", answer: "Destiny", options: ["Destiny", "Halo", "Mass Effect", "Borderlands"], difficulty: "moyen" },
    // DIFFICILE
    { question: "En quelle année le premier jeu vidéo 'Pong' est-il sorti ?", answer: "1972", options: ["1972", "1970", "1975", "1968"], difficulty: "difficile" },
    { question: "Combien de copies GTA V a-t-il vendues (approximativement) ?", answer: "190+ millions", options: ["190+ millions", "150 millions", "100 millions", "200 millions"], difficulty: "difficile" },
    { question: "Quel est le nom du créateur de Mario ?", answer: "Shigeru Miyamoto", options: ["Shigeru Miyamoto", "Hideo Kojima", "Satoshi Tajiri", "Masahiro Sakurai"], difficulty: "difficile" },
    { question: "En quelle année Tetris a-t-il été créé ?", answer: "1984", options: ["1984", "1986", "1982", "1988"], difficulty: "difficile" },
    { question: "Quel est le jeu indépendant le plus vendu de l'histoire ?", answer: "Minecraft", options: ["Minecraft", "Terraria", "Stardew Valley", "Hollow Knight"], difficulty: "difficile" },
    { question: "Combien de générations de Pokémon existe-t-il (jusqu'en 2024) ?", answer: "9", options: ["9", "8", "10", "7"], difficulty: "difficile" },
    { question: "Quel est le nom du créateur de Metal Gear Solid ?", answer: "Hideo Kojima", options: ["Hideo Kojima", "Shigeru Miyamoto", "Hidetaka Miyazaki", "Shinji Mikami"], difficulty: "difficile" },
    { question: "En quelle année la Xbox 360 est-elle sortie ?", answer: "2005", options: ["2005", "2006", "2004", "2007"], difficulty: "difficile" },
    { question: "Quel est le plus grand tournoi d'esport en termes de prize pool ?", answer: "The International (Dota 2)", options: ["The International (Dota 2)", "Worlds (LoL)", "Major CS:GO", "Fortnite World Cup"], difficulty: "difficile" },
    { question: "Combien de Colossus y a-t-il dans Shadow of the Colossus ?", answer: "16", options: ["16", "12", "18", "20"], difficulty: "difficile" },
    { question: "Quel studio a développé Elden Ring ?", answer: "FromSoftware", options: ["FromSoftware", "CD Projekt Red", "Bethesda", "Square Enix"], difficulty: "difficile" },
    { question: "En quelle année la Dreamcast est-elle sortie au Japon ?", answer: "1998", options: ["1998", "1999", "1997", "2000"], difficulty: "difficile" },
    { question: "Quel est le premier jeu de la série Silent Hill ?", answer: "Silent Hill (1999)", options: ["Silent Hill (1999)", "Silent Hill 2", "Silent Hill Origins", "Silent Hill: Homecoming"], difficulty: "difficile" },
    { question: "Combien de fins possibles y a-t-il dans Chrono Trigger ?", answer: "13", options: ["13", "10", "15", "8"], difficulty: "difficile" },
    { question: "Quel est le nom du créateur de Resident Evil ?", answer: "Shinji Mikami", options: ["Shinji Mikami", "Hideo Kojima", "Hidetaka Miyazaki", "Hideki Kamiya"], difficulty: "difficile" }
  ],

  art: [
    // FACILE
    { question: "Qui a peint La Joconde ?", answer: "Léonard de Vinci", options: ["Léonard de Vinci", "Michel-Ange", "Raphaël", "Botticelli"], difficulty: "facile" },
    { question: "Dans quel musée se trouve La Joconde ?", answer: "Le Louvre", options: ["Le Louvre", "Le Prado", "Les Offices", "Le British Museum"], difficulty: "facile" },
    { question: "Qui a sculpté le David ?", answer: "Michel-Ange", options: ["Michel-Ange", "Donatello", "Bernin", "Rodin"], difficulty: "facile" },
    { question: "Quel artiste est célèbre pour ses nénuphars ?", answer: "Claude Monet", options: ["Claude Monet", "Vincent Van Gogh", "Pierre-Auguste Renoir", "Édouard Manet"], difficulty: "facile" },
    { question: "Qui a peint La Nuit étoilée ?", answer: "Vincent Van Gogh", options: ["Vincent Van Gogh", "Claude Monet", "Paul Gauguin", "Paul Cézanne"], difficulty: "facile" },
    { question: "Quel mouvement artistique Pablo Picasso a-t-il co-fondé ?", answer: "Cubisme", options: ["Cubisme", "Surréalisme", "Impressionnisme", "Expressionnisme"], difficulty: "facile" },
    { question: "Qui a peint le plafond de la Chapelle Sixtine ?", answer: "Michel-Ange", options: ["Michel-Ange", "Raphaël", "Léonard de Vinci", "Botticelli"], difficulty: "facile" },
    { question: "Quelle technique utilise des petits points de couleur ?", answer: "Pointillisme", options: ["Pointillisme", "Impressionnisme", "Cubisme", "Fauvisme"], difficulty: "facile" },
    { question: "Qui a peint Les Tournesols ?", answer: "Vincent Van Gogh", options: ["Vincent Van Gogh", "Claude Monet", "Paul Gauguin", "Henri Matisse"], difficulty: "facile" },
    { question: "Quel artiste espagnol a peint Guernica ?", answer: "Pablo Picasso", options: ["Pablo Picasso", "Salvador Dalí", "Joan Miró", "Francisco Goya"], difficulty: "facile" },
    { question: "De quel pays Rembrandt est-il originaire ?", answer: "Pays-Bas", options: ["Pays-Bas", "Belgique", "Allemagne", "France"], difficulty: "facile" },
    { question: "Quel artiste est connu pour ses montres molles ?", answer: "Salvador Dalí", options: ["Salvador Dalí", "René Magritte", "Joan Miró", "Max Ernst"], difficulty: "facile" },
    { question: "Qui a créé Le Penseur ?", answer: "Auguste Rodin", options: ["Auguste Rodin", "Michel-Ange", "Bernin", "Camille Claudel"], difficulty: "facile" },
    { question: "Quel mouvement artistique est né à Paris au 19ème siècle ?", answer: "Impressionnisme", options: ["Impressionnisme", "Renaissance", "Baroque", "Romantisme"], difficulty: "facile" },
    { question: "Qui a peint Le Cri ?", answer: "Edvard Munch", options: ["Edvard Munch", "Vincent Van Gogh", "Pablo Picasso", "Francis Bacon"], difficulty: "facile" },
    { question: "Quelle est la couleur préférée de Picasso pendant sa période bleue ?", answer: "Bleu", options: ["Bleu", "Rouge", "Rose", "Noir"], difficulty: "facile" },
    { question: "Qui a peint La Création d'Adam ?", answer: "Michel-Ange", options: ["Michel-Ange", "Raphaël", "Léonard de Vinci", "Botticelli"], difficulty: "facile" },
    { question: "Quel artiste français a peint des danseuses de ballet ?", answer: "Edgar Degas", options: ["Edgar Degas", "Pierre-Auguste Renoir", "Claude Monet", "Édouard Manet"], difficulty: "facile" },
    { question: "De quelle nationalité est Frida Kahlo ?", answer: "Mexicaine", options: ["Mexicaine", "Espagnole", "Argentine", "Brésilienne"], difficulty: "facile" },
    { question: "Quel artiste a créé des tableaux de boîtes de soupe Campbell ?", answer: "Andy Warhol", options: ["Andy Warhol", "Roy Lichtenstein", "Keith Haring", "Jean-Michel Basquiat"], difficulty: "facile" },
    // MOYEN
    { question: "En quelle année Vincent Van Gogh est-il mort ?", answer: "1890", options: ["1890", "1888", "1895", "1885"], difficulty: "moyen" },
    { question: "Qui a fondé le mouvement surréaliste ?", answer: "André Breton", options: ["André Breton", "Salvador Dalí", "René Magritte", "Max Ernst"], difficulty: "moyen" },
    { question: "Combien de tableaux Van Gogh a-t-il vendus de son vivant ?", answer: "1", options: ["1", "0", "3", "10"], difficulty: "moyen" },
    { question: "Qui a peint Le Déjeuner sur l'herbe ?", answer: "Édouard Manet", options: ["Édouard Manet", "Claude Monet", "Pierre-Auguste Renoir", "Gustave Courbet"], difficulty: "moyen" },
    { question: "Quel artiste a coupé une partie de son oreille ?", answer: "Vincent Van Gogh", options: ["Vincent Van Gogh", "Paul Gauguin", "Pablo Picasso", "Edvard Munch"], difficulty: "moyen" },
    { question: "En quelle année la Joconde a-t-elle été volée au Louvre ?", answer: "1911", options: ["1911", "1900", "1920", "1905"], difficulty: "moyen" },
    { question: "Qui a peint La Liberté guidant le peuple ?", answer: "Eugène Delacroix", options: ["Eugène Delacroix", "Jacques-Louis David", "Théodore Géricault", "Francisco Goya"], difficulty: "moyen" },
    { question: "Quel artiste a créé la technique du dripping ?", answer: "Jackson Pollock", options: ["Jackson Pollock", "Willem de Kooning", "Mark Rothko", "Franz Kline"], difficulty: "moyen" },
    { question: "De quel mouvement Kandinsky est-il un pionnier ?", answer: "Art abstrait", options: ["Art abstrait", "Surréalisme", "Expressionnisme", "Cubisme"], difficulty: "moyen" },
    { question: "Qui a sculpté Les Bourgeois de Calais ?", answer: "Auguste Rodin", options: ["Auguste Rodin", "Camille Claudel", "Antoine Bourdelle", "Aristide Maillol"], difficulty: "moyen" },
    { question: "Quel artiste a peint Les Ménines ?", answer: "Diego Vélasquez", options: ["Diego Vélasquez", "Francisco Goya", "El Greco", "Bartolomé Murillo"], difficulty: "moyen" },
    { question: "En quelle année le mouvement Dada a-t-il été fondé ?", answer: "1916", options: ["1916", "1920", "1912", "1918"], difficulty: "moyen" },
    { question: "Qui a peint La Naissance de Vénus ?", answer: "Sandro Botticelli", options: ["Sandro Botticelli", "Raphaël", "Léonard de Vinci", "Michel-Ange"], difficulty: "moyen" },
    { question: "Quel artiste belge est connu pour ses peintures d'hommes en chapeau melon ?", answer: "René Magritte", options: ["René Magritte", "Paul Delvaux", "James Ensor", "Fernand Khnopff"], difficulty: "moyen" },
    { question: "De quelle école Vermeer faisait-il partie ?", answer: "École hollandaise", options: ["École hollandaise", "École flamande", "École italienne", "École espagnole"], difficulty: "moyen" },
    { question: "Qui a créé les Mobiles ?", answer: "Alexander Calder", options: ["Alexander Calder", "Jean Tinguely", "Constantin Brâncuși", "Alberto Giacometti"], difficulty: "moyen" },
    { question: "Quel artiste a peint La Jeune Fille à la perle ?", answer: "Johannes Vermeer", options: ["Johannes Vermeer", "Rembrandt", "Frans Hals", "Jan Steen"], difficulty: "moyen" },
    { question: "En quelle année le Bauhaus a-t-il été fondé ?", answer: "1919", options: ["1919", "1925", "1915", "1923"], difficulty: "moyen" },
    { question: "Qui a créé la fontaine (urinoir) exposée comme art ?", answer: "Marcel Duchamp", options: ["Marcel Duchamp", "Man Ray", "Francis Picabia", "Hans Arp"], difficulty: "moyen" },
    { question: "Quel artiste américain a peint Nighthawks ?", answer: "Edward Hopper", options: ["Edward Hopper", "Grant Wood", "Andrew Wyeth", "Norman Rockwell"], difficulty: "moyen" },
    // DIFFICILE
    { question: "Combien d'œuvres authentifiées de Vermeer existe-t-il ?", answer: "34-36", options: ["34-36", "50", "100", "20"], difficulty: "difficile" },
    { question: "En quelle année Picasso a-t-il peint Guernica ?", answer: "1937", options: ["1937", "1936", "1939", "1935"], difficulty: "difficile" },
    { question: "Quelle est la taille approximative de La Joconde ?", answer: "77 x 53 cm", options: ["77 x 53 cm", "150 x 100 cm", "200 x 150 cm", "50 x 30 cm"], difficulty: "difficile" },
    { question: "Qui a fondé le mouvement De Stijl ?", answer: "Theo van Doesburg", options: ["Theo van Doesburg", "Piet Mondrian", "Gerrit Rietveld", "Bart van der Leck"], difficulty: "difficile" },
    { question: "En quelle année Le Cri d'Edvard Munch a-t-il été peint ?", answer: "1893", options: ["1893", "1890", "1895", "1900"], difficulty: "difficile" },
    { question: "Combien de versions du Cri Munch a-t-il créées ?", answer: "4", options: ["4", "2", "3", "1"], difficulty: "difficile" },
    { question: "Qui a fondé l'école du Bauhaus ?", answer: "Walter Gropius", options: ["Walter Gropius", "Mies van der Rohe", "Le Corbusier", "Wassily Kandinsky"], difficulty: "difficile" },
    { question: "Quel tableau de Da Vinci a été vendu 450 millions de dollars ?", answer: "Salvator Mundi", options: ["Salvator Mundi", "La Joconde", "La Cène", "La Dame à l'hermine"], difficulty: "difficile" },
    { question: "En quelle année Michel-Ange a-t-il commencé le plafond de la Sixtine ?", answer: "1508", options: ["1508", "1512", "1505", "1515"], difficulty: "difficile" },
    { question: "Quel artiste a créé la série des Cathédrales de Rouen ?", answer: "Claude Monet", options: ["Claude Monet", "Camille Pissarro", "Alfred Sisley", "Gustave Caillebotte"], difficulty: "difficile" },
    { question: "Combien de tableaux composent la série des Nymphéas de Monet ?", answer: "250", options: ["250", "100", "50", "500"], difficulty: "difficile" },
    { question: "En quelle année le premier Salon des Refusés a-t-il eu lieu ?", answer: "1863", options: ["1863", "1870", "1855", "1880"], difficulty: "difficile" },
    { question: "Quel artiste a créé The Physical Impossibility of Death ?", answer: "Damien Hirst", options: ["Damien Hirst", "Jeff Koons", "Tracey Emin", "Banksy"], difficulty: "difficile" },
    { question: "Combien de temps Michel-Ange a-t-il mis pour peindre la Sixtine ?", answer: "4 ans", options: ["4 ans", "2 ans", "7 ans", "10 ans"], difficulty: "difficile" },
    { question: "Quel artiste a peint L'Origine du monde ?", answer: "Gustave Courbet", options: ["Gustave Courbet", "Édouard Manet", "Eugène Delacroix", "Jean-Auguste-Dominique Ingres"], difficulty: "difficile" }
  ]
};

export const CATEGORIES = [
  { id: 'general', name: 'Culture Générale', emoji: '🎯' },
  { id: 'anime', name: 'Anime & Manga', emoji: '🎌' },
  { id: 'histoire', name: 'Histoire', emoji: '📜' },
  { id: 'sport', name: 'Sport', emoji: '⚽' },
  { id: 'musique', name: 'Musique', emoji: '🎵' },
  { id: 'cinema', name: 'Cinéma & Séries', emoji: '🎬' },
  { id: 'science', name: 'Science', emoji: '🔬' },
  { id: 'geographie', name: 'Géographie', emoji: '🌍' },
  { id: 'jeux_video', name: 'Jeux Vidéo', emoji: '🎮' },
  { id: 'art', name: 'Art', emoji: '🎨' }
];

export const DIFFICULTIES = [
  { id: 'facile', name: 'Facile', color: 'text-green-400' },
  { id: 'moyen', name: 'Moyen', color: 'text-yellow-400' },
  { id: 'difficile', name: 'Difficile', color: 'text-red-400' }
];
