// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-active-lobbies.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_active_lobbies_default = defineTool({
  name: "list_active_lobbies",
  title: "List active lobbies",
  description: "List currently active public game lobbies (waiting or playing).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Max lobbies to return")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("lobbies").select("id, code, game_mode, game_phase, created_at, host_id").in("game_phase", ["lobby", "playing", "waiting"]).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lobbies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_leaderboard_default = defineTool2({
  name: "get_leaderboard",
  title: "Get global leaderboard",
  description: "Return top players ranked by total XP.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(10).describe("Number of top players")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("player_stats").select("user_id, total_xp, level, games_played, games_won").order("total_xp", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leaderboard: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-recent-social-posts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_recent_social_posts_default = defineTool3({
  name: "get_recent_social_posts",
  title: "Get recent social posts",
  description: "Fetch the most recent public social feed posts.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).describe("Number of posts")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("social_posts").select("id, user_id, caption, game_mode, created_at, likes_count, comments_count").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/do-anything.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb() {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var ACTIONS = [
  "list_lobbies",
  "get_lobby",
  "get_leaderboard",
  "get_profile",
  "search_profiles",
  "get_player_stats",
  "list_recent_posts",
  "get_post",
  "list_post_comments",
  "list_quiz_top_scores",
  "list_video_clips",
  "count_table"
];
var do_anything_default = defineTool4({
  name: "do_anything",
  title: "Do anything (Mimic Madness)",
  description: "Swiss-army read tool for Mimic Madness. Pick an `action` and pass the matching `params` object. Available actions: " + ACTIONS.join(", ") + ". All actions are read-only.",
  inputSchema: {
    action: z4.enum(ACTIONS).describe("Which operation to run"),
    params: z4.record(z4.string(), z4.unknown()).default({}).describe(
      "Parameters for the action. Common: limit (number), user_id (uuid), lobby_id (uuid), post_id (uuid), query (string), table (string)"
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ action, params }) => {
    const p = params ?? {};
    const limit = Math.min(Math.max(Number(p.limit ?? 20), 1), 100);
    const supabase = sb();
    const ok = (data) => ({
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { data }
    });
    const err = (msg) => ({
      content: [{ type: "text", text: msg }],
      isError: true
    });
    try {
      switch (action) {
        case "list_lobbies": {
          const { data, error } = await supabase.from("lobbies").select("id, code, game_mode, game_phase, created_at, host_id").order("created_at", { ascending: false }).limit(limit);
          return error ? err(error.message) : ok(data);
        }
        case "get_lobby": {
          if (!p.lobby_id && !p.code) return err("params.lobby_id or params.code required");
          const q = supabase.from("lobbies").select("*").limit(1);
          const { data, error } = p.lobby_id ? await q.eq("id", p.lobby_id) : await q.eq("code", p.code);
          return error ? err(error.message) : ok(data?.[0] ?? null);
        }
        case "get_leaderboard": {
          const { data, error } = await supabase.from("player_stats").select("user_id, total_xp, level, games_played, games_won").order("total_xp", { ascending: false }).limit(limit);
          return error ? err(error.message) : ok(data);
        }
        case "get_profile": {
          if (!p.user_id) return err("params.user_id required");
          const { data, error } = await supabase.from("profiles").select("*").eq("user_id", p.user_id).maybeSingle();
          return error ? err(error.message) : ok(data);
        }
        case "search_profiles": {
          if (!p.query) return err("params.query required");
          const { data, error } = await supabase.from("profiles").select("user_id, display_name, avatar_url").ilike("display_name", `%${String(p.query)}%`).limit(limit);
          return error ? err(error.message) : ok(data);
        }
        case "get_player_stats": {
          if (!p.user_id) return err("params.user_id required");
          const { data, error } = await supabase.from("player_stats").select("*").eq("user_id", p.user_id).maybeSingle();
          return error ? err(error.message) : ok(data);
        }
        case "list_recent_posts": {
          const { data, error } = await supabase.from("social_posts").select("id, owner_id, owner_name, caption, likes_count, comments_count, created_at").eq("is_hidden", false).order("created_at", { ascending: false }).limit(limit);
          return error ? err(error.message) : ok(data);
        }
        case "get_post": {
          if (!p.post_id) return err("params.post_id required");
          const { data, error } = await supabase.from("social_posts").select("*").eq("id", p.post_id).maybeSingle();
          return error ? err(error.message) : ok(data);
        }
        case "list_post_comments": {
          if (!p.post_id) return err("params.post_id required");
          const { data, error } = await supabase.from("social_post_comments").select("*").eq("post_id", p.post_id).order("created_at", { ascending: true }).limit(limit);
          return error ? err(error.message) : ok(data);
        }
        case "list_quiz_top_scores": {
          const { data, error } = await supabase.from("quiz_scores").select("*").order("score", { ascending: false }).limit(limit);
          return error ? err(error.message) : ok(data);
        }
        case "list_video_clips": {
          let q = supabase.from("video_clips").select("id, player_id, created_at, game_mode").order("created_at", { ascending: false }).limit(limit);
          if (p.player_id) q = q.eq("player_id", p.player_id);
          const { data, error } = await q;
          return error ? err(error.message) : ok(data);
        }
        case "count_table": {
          const allowed = /* @__PURE__ */ new Set([
            "lobbies",
            "profiles",
            "player_stats",
            "social_posts",
            "video_clips",
            "quiz_scores"
          ]);
          const table = String(p.table ?? "");
          if (!allowed.has(table)) return err(`params.table must be one of ${[...allowed].join(", ")}`);
          const { count, error } = await supabase.from(table).select("*", { count: "exact", head: true });
          return error ? err(error.message) : ok({ table, count });
        }
      }
    } catch (e) {
      return err(e?.message ?? "unknown error");
    }
    return err(`Unknown action: ${action}`);
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "mimic-madness-mcp",
  title: "Mimic Madness MCP",
  version: "0.1.0",
  instructions: "Tools to explore the Mimic Madness party game: browse active lobbies, view the global XP leaderboard, and read recent social feed posts.",
  tools: [do_anything_default, list_active_lobbies_default, get_leaderboard_default, get_recent_social_posts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
