// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-active-lobbies.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_active_lobbies_default = defineTool({
  name: "list_active_lobbies",
  title: "List active lobbies",
  description: "List currently active public game lobbies (waiting or playing).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Max lobbies to return")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("lobbies").select("id, code, game_mode, game_phase, created_at, host_id").in("game_phase", ["lobby", "playing", "waiting"]).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lobbies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_leaderboard_default = defineTool2({
  name: "get_leaderboard",
  title: "Get global leaderboard",
  description: "Return top players ranked by total XP.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(10).describe("Number of top players")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("player_stats").select("user_id, total_xp, level, games_played, games_won").order("total_xp", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leaderboard: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-recent-social-posts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_recent_social_posts_default = defineTool3({
  name: "get_recent_social_posts",
  title: "Get recent social posts",
  description: "Fetch the most recent public social feed posts.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).describe("Number of posts")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("social_posts").select("id, user_id, caption, game_mode, created_at, likes_count, comments_count").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "mimic-madness-mcp",
  title: "Mimic Madness MCP",
  version: "0.1.0",
  instructions: "Tools to explore the Mimic Madness party game: browse active lobbies, view the global XP leaderboard, and read recent social feed posts.",
  tools: [list_active_lobbies_default, get_leaderboard_default, get_recent_social_posts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
